# 🏪🛒🏷️⬇️STORE SALES FORECASTING💰💲📊📈💸

This is a continuation notebook from the analysis cleaning and feature engineering of the store sales dataset. This notebook focuses solely on modelling an forecasting or predictions using a `HybridModel`(LinearRegression + XgboostRegressor. The `linearRegression` model would be made to learn the trend and the `XgboostRegressor` model would be made to learn the seasons, cycles and residual components of our timeseries.

## IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import xgboost as xg
from statsmodels.tsa.deterministic import CalendarFourier, DeterministicProcess
from statsmodels.graphics.tsaplots import plot_pacf, seasonal_plot
from scipy.signal import periodogram
from itertools import product

In [2]:
# Display all the columns in the dataset
pd.pandas.set_option('display.max_columns', None)

# Display all the rows in the dataset
# pd.pandas.set_option('display.max_rows', None)

## LOAD DATA

In [3]:
# load the train set
train_df = pd.read_csv("train_set.csv",
                       low_memory = False,
                       dtype = {
                           'store_nbr' : 'category',
                           'family' : 'category',
                           'sales' : 'float32',
                           'onpromotion' : 'uint32',
                           'city' : 'category',
                           'state' : 'category',
                           'type' : 'category',
                           'cluster' : 'category'
                       },
                       parse_dates = ['date'],
                      )

train_df['date'] = train_df.date.dt.to_period('D')
train_df = train_df.set_index(['store_nbr', 'family', 'date']).sort_index()
train_df

                                      id      sales  onpromotion  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01        0   0.000000            0
                     2013-01-02     1782   2.000000            0
                     2013-01-03     3564   3.000000            0
                     2013-01-04     5346   3.000000            0
                     2013-01-05     7128   5.000000            0
...                                  ...        ...          ...
9         SEAFOOD    2017-08-11  2993759  23.830999            0
                     2017-08-12  2995541  16.859001            4
                     2017-08-13  2997323  20.000000            0
                     2017-08-14  2999105  17.000000            0
                     2017-08-15  3000887  16.000000            0

                                 is_regional_holiday  is_local_holiday   city  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                False             False  Quito
                     2013-01-02                False             False  Quito
                     2013-01-03                False             False  Quito
                     2013-01-04                False             False  Quito
                     2013-01-05                False             False  Quito
...                                              ...               ...    ...
9         SEAFOOD    2017-08-11                False             False  Quito
                     2017-08-12                False             False  Quito
                     2017-08-13                False             False  Quito
                     2017-08-14                False             False  Quito
                     2017-08-15                False             False  Quito

                                     state type cluster  const   trend  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01  Pichincha    D      13    1.0     1.0
                     2013-01-02  Pichincha    D      13    1.0     2.0
                     2013-01-03  Pichincha    D      13    1.0     3.0
                     2013-01-04  Pichincha    D      13    1.0     4.0
                     2013-01-05  Pichincha    D      13    1.0     5.0
...                                    ...  ...     ...    ...     ...
9         SEAFOOD    2017-08-11  Pichincha    B       6    1.0  1684.0
                     2017-08-12  Pichincha    B       6    1.0  1685.0
                     2017-08-13  Pichincha    B       6    1.0  1686.0
                     2017-08-14  Pichincha    B       6    1.0  1687.0
                     2017-08-15  Pichincha    B       6    1.0  1688.0

                                 s(2,7)  s(3,7)  s(4,7)  s(5,7)  s(6,7)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01     0.0     0.0     0.0     0.0     0.0
                     2013-01-02     1.0     0.0     0.0     0.0     0.0
                     2013-01-03     0.0     1.0     0.0     0.0     0.0
                     2013-01-04     0.0     0.0     1.0     0.0     0.0
                     2013-01-05     0.0     0.0     0.0     1.0     0.0
...                                 ...     ...     ...     ...     ...
9         SEAFOOD    2017-08-11     0.0     0.0     1.0     0.0     0.0
                     2017-08-12     0.0     0.0     0.0     1.0     0.0
                     2017-08-13     0.0     0.0     0.0     0.0     1.0
                     2017-08-14     0.0     0.0     0.0     0.0     0.0
                     2017-08-15     0.0     0.0     0.0     0.0     0.0

                                 s(7,7)  sin(1,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01     0.0            0.000000
                     2013-01-02     0.0            0.017213
                     2013-01-03     0.0            0.034422
                     2013-01-04     0.0            0.051620
                     2013-01-05     0.0            0.068802
...                                 ...                 ...
9         SEAFOOD    2017-08-11     0.0           -0.628763
                     2017-08-12     0.0           -0.642055
                     2017-08-13     0.0           -0.655156
                     2017-08-14     1.0           -0.668064
                     2017-08-15     0.0           -0.680773

                                 cos(1,freq=YE-DEC)  sin(2,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.999852            0.034422
                     2013-01-03            0.999407            0.068802
                     2013-01-04            0.998667            0.103102
                     2013-01-05            0.997630            0.137279
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.777597            0.977848
                     2017-08-12           -0.766659            0.984474
                     2017-08-13           -0.755493            0.989932
                     2017-08-14           -0.744104            0.994218
                     2017-08-15           -0.732494            0.997325

                                 cos(2,freq=YE-DEC)  sin(3,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.999407            0.051620
                     2013-01-03            0.997630            0.103102
                     2013-01-04            0.994671            0.154309
                     2013-01-05            0.990532            0.205104
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.209315           -0.891981
                     2017-08-12            0.175531           -0.867456
                     2017-08-13            0.141540           -0.840618
                     2017-08-14            0.107381           -0.811539
                     2017-08-15            0.073095           -0.780296

                                 cos(3,freq=YE-DEC)  sin(4,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.998667            0.068802
                     2013-01-03            0.994671            0.137279
                     2013-01-04            0.988023            0.205104
                     2013-01-05            0.978740            0.271958
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.452072            0.409356
                     2017-08-12            0.497513            0.345612
                     2017-08-13            0.541628            0.280231
                     2017-08-14            0.584298            0.213521
                     2017-08-15            0.625411            0.145799

                                 cos(4,freq=YE-DEC)  sin(5,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.997630            0.085965
                     2013-01-03            0.990532            0.171293
                     2013-01-04            0.978740            0.255353
                     2013-01-05            0.962309            0.337523
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.912375            0.255353
                     2017-08-12           -0.938377            0.337523
                     2017-08-13           -0.959933            0.417194
                     2017-08-14           -0.976938            0.493776
                     2017-08-15           -0.989314            0.566702

                                 cos(5,freq=YE-DEC)  sin(1,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.996298            0.069756
                     2013-01-03            0.985220            0.139173
                     2013-01-04            0.966848            0.207912
                     2013-01-05            0.941317            0.275637
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.966848            0.334880
                     2017-08-12            0.941317            0.269797
                     2017-08-13            0.908818            0.203456
                     2017-08-14            0.869589            0.136167
                     2017-08-15            0.823923            0.068242

                                 cos(1,freq=QE-DEC)  sin(2,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.997564            0.139173
                     2013-01-03            0.990268            0.275637
                     2013-01-04            0.978148            0.406737
                     2013-01-05            0.961262            0.529919
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.942261           -0.631088
                     2017-08-12           -0.962917           -0.519584
                     2017-08-13           -0.979084           -0.398401
                     2017-08-14           -0.990686           -0.269797
                     2017-08-15           -0.997669           -0.136167

                                 cos(2,freq=QE-DEC)  is_new_year  dcoilwtico  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            1       93.14
                     2013-01-02            0.990268            0       93.14
                     2013-01-03            0.961262            0       92.97
                     2013-01-04            0.913545            0       93.12
                     2013-01-05            0.848048            0       93.15
...                                             ...          ...         ...
9         SEAFOOD    2017-08-11            0.775711            0       48.81
                     2017-08-12            0.854419            0       48.40
                     2017-08-13            0.917211            0       48.00
                     2017-08-14            0.962917            0       47.59
                     2017-08-15            0.990686            0       47.57

                                 is_national_holiday  holiday_type_Additional  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                 True                    False
                     2013-01-02                False                    False
                     2013-01-03                False                    False
                     2013-01-04                False                    False
                     2013-01-05                 True                    False
...                                              ...                      ...
9         SEAFOOD    2017-08-11                 True                    False
                     2017-08-12                False                    False
                     2017-08-13                False                    False
                     2017-08-14                False                    False
                     2017-08-15                False                    False

                                 holiday_type_Bridge  holiday_type_Event  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                False               False
                     2013-01-02                False               False
                     2013-01-03                False               False
                     2013-01-04                False               False
                     2013-01-05                False               False
...                                              ...                 ...
9         SEAFOOD    2017-08-11                False               False
                     2017-08-12                False               False
                     2017-08-13                False               False
                     2017-08-14                False               False
                     2017-08-15                False               False

                                 holiday_type_Holiday  holiday_type_Transfer  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                  True                  False
                     2013-01-02                 False                  False
                     2013-01-03                 False                  False
                     2013-01-04                 False                  False
                     2013-01-05                 False                  False
...                                               ...                    ...
9         SEAFOOD    2017-08-11                 False                   True
                     2017-08-12                 False                  False
                     2017-08-13                 False                  False
                     2017-08-14                 False                  False
                     2017-08-15                  True                  False

                                 holiday_type_Work Day  holiday_transferred  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                  False                False
                     2013-01-02                  False                False
                     2013-01-03                  False                False
                     2013-01-04                  False                False
                     2013-01-05                   True                False
...                                                ...                  ...
9         SEAFOOD    2017-08-11                  False                False
                     2017-08-12                  False                False
                     2017-08-13                  False                False
                     2017-08-14                  False                False
                     2017-08-15                  False                False

                                 is_holiday  is_christmas  is_payday_15  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01        True         False             0
                     2013-01-02       False         False             0
                     2013-01-03       False         False             0
                     2013-01-04       False         False             0
                     2013-01-05        True         False             0
...                                     ...           ...           ...
9         SEAFOOD    2017-08-11        True         False             0
                     2017-08-12       False         False             0
                     2017-08-13       False         False             0
                     2017-08-14       False         False             0
                     2017-08-15        True         False             1

                                 is_payday_end  is_payday  earthquake_impact  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01              0          0                  0
                     2013-01-02              0          0                  0
                     2013-01-03              0          0                  0
                     2013-01-04              0          0                  0
                     2013-01-05              0          0                  0
...                                        ...        ...                ...
9         SEAFOOD    2017-08-11              0          0                  0
                     2017-08-12              0          0                  0
                     2017-08-13              0          0                  0
                     2017-08-14              0          0                  0
                     2017-08-15              0          1                  0

                                 earthquake_decay  is_new_year_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01               0.0                    0
                     2013-01-02               0.0                    0
                     2013-01-03               0.0                    0
                     2013-01-04               0.0                    0
                     2013-01-05               0.0                    0
...                                           ...                  ...
9         SEAFOOD    2017-08-11               0.0                    0
                     2017-08-12               0.0                    0
                     2017-08-13               0.0                    0
                     2017-08-14               0.0                    0
                     2017-08-15               0.0                    0

                                 is_new_year_lead(2)  is_new_year_lead(3)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                    0
                     2013-01-02                    0                    0
                     2013-01-03                    0                    0
                     2013-01-04                    0                    0
                     2013-01-05                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-11                    0                    0
                     2017-08-12                    0                    0
                     2017-08-13                    0                    0
                     2017-08-14                    0                    0
                     2017-08-15                    0                    0

                                 is_new_year_lag(1)  is_new_year_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                   0                   0
                     2013-01-02                   1                   0
                     2013-01-03                   0                   1
                     2013-01-04                   0                   0
                     2013-01-05                   0                   0
...                                             ...                 ...
9         SEAFOOD    2017-08-11                   0                   0
                     2017-08-12                   0                   0
                     2017-08-13                   0                   0
                     2017-08-14                   0                   0
                     2017-08-15                   0                   0

                                 is_christmas_lag(1)  is_christmas_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                False                False
                     2013-01-02                False                False
                     2013-01-03                False                False
                     2013-01-04                False                False
                     2013-01-05                False                False
...                                              ...                  ...
9         SEAFOOD    2017-08-11                False                False
                     2017-08-12                False                False
                     2017-08-13                False                False
                     2017-08-14                False                False
                     2017-08-15                False                False

                                 is_christmas_lag(3)  is_christmas_lead(1)  \
store_nbr family     date

In [4]:
# Load the test set
test_df = pd.read_csv("test_set.csv",
                      low_memory = False,
                      dtype = {
                          'store_nbr' : 'category',
                          'family' : 'category',
                          'onpromotion' : 'uint32',
                          'city' : 'category',
                          'state' : 'category',
                          'type' : 'category',
                          'cluster' : 'category'
                      },
                      parse_dates = ['date'],
                     )

test_df['date'] = test_df.date.dt.to_period('D')
test_df = test_df.set_index(['store_nbr', 'family', 'date']).sort_index()
test_df

                                      id  onpromotion  is_local_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16  3000888            0             False
                     2017-08-17  3002670            0             False
                     2017-08-18  3004452            0             False
                     2017-08-19  3006234            0             False
                     2017-08-20  3008016            0             False
...                                  ...          ...               ...
9         SEAFOOD    2017-08-27  3022271            0             False
                     2017-08-28  3024053            0             False
                     2017-08-29  3025835            0             False
                     2017-08-30  3027617            0             False
                     2017-08-31  3029399            0             False

                                  city      state type cluster  const   trend  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16  Quito  Pichincha    D      13    1.0  1689.0
                     2017-08-17  Quito  Pichincha    D      13    1.0  1690.0
                     2017-08-18  Quito  Pichincha    D      13    1.0  1691.0
                     2017-08-19  Quito  Pichincha    D      13    1.0  1692.0
                     2017-08-20  Quito  Pichincha    D      13    1.0  1693.0
...                                ...        ...  ...     ...    ...     ...
9         SEAFOOD    2017-08-27  Quito  Pichincha    B       6    1.0  1700.0
                     2017-08-28  Quito  Pichincha    B       6    1.0  1701.0
                     2017-08-29  Quito  Pichincha    B       6    1.0  1702.0
                     2017-08-30  Quito  Pichincha    B       6    1.0  1703.0
                     2017-08-31  Quito  Pichincha    B       6    1.0  1704.0

                                 s(2,7)  s(3,7)  s(4,7)  s(5,7)  s(6,7)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16     1.0     0.0     0.0     0.0     0.0
                     2017-08-17     0.0     1.0     0.0     0.0     0.0
                     2017-08-18     0.0     0.0     1.0     0.0     0.0
                     2017-08-19     0.0     0.0     0.0     1.0     0.0
                     2017-08-20     0.0     0.0     0.0     0.0     1.0
...                                 ...     ...     ...     ...     ...
9         SEAFOOD    2017-08-27     0.0     0.0     0.0     0.0     1.0
                     2017-08-28     0.0     0.0     0.0     0.0     0.0
                     2017-08-29     0.0     0.0     0.0     0.0     0.0
                     2017-08-30     1.0     0.0     0.0     0.0     0.0
                     2017-08-31     0.0     1.0     0.0     0.0     0.0

                                 s(7,7)  sin(1,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16     0.0           -0.693281
                     2017-08-17     0.0           -0.705584
                     2017-08-18     0.0           -0.717677
                     2017-08-19     0.0           -0.729558
                     2017-08-20     0.0           -0.741222
...                                 ...                 ...
9         SEAFOOD    2017-08-27     0.0           -0.816538
                     2017-08-28     1.0           -0.826354
                     2017-08-29     0.0           -0.835925
                     2017-08-30     0.0           -0.845249
                     2017-08-31     0.0           -0.854322

                                 cos(1,freq=YE-DEC)  sin(2,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -0.720667            0.999250
                     2017-08-17           -0.708627            0.999991
                     2017-08-18           -0.696376            0.999546
                     2017-08-19           -0.683919            0.997917
                     2017-08-20           -0.671260            0.995105
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.577292            0.942761
                     2017-08-28           -0.563151            0.930724
                     2017-08-29           -0.548843            0.917584
                     2017-08-30           -0.534373            0.903356
                     2017-08-31           -0.519744            0.888057

                                 cos(2,freq=YE-DEC)  sin(3,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.038722           -0.746972
                     2017-08-17            0.004304           -0.711657
                     2017-08-18           -0.030120           -0.674444
                     2017-08-19           -0.064508           -0.635432
                     2017-08-20           -0.098820           -0.594727
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.333469           -0.271958
                     2017-08-28           -0.365723           -0.221922
                     2017-08-29           -0.397543           -0.171293
                     2017-08-30           -0.428892           -0.120208
                     2017-08-31           -0.459733           -0.068802

                                 cos(3,freq=YE-DEC)  sin(4,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.664855            0.077386
                     2017-08-17            0.702527            0.008607
                     2017-08-18            0.738326           -0.060213
                     2017-08-19            0.772157           -0.128748
                     2017-08-20            0.803928           -0.196673
...                                             ...                 ...
9         SEAFOOD    2017-08-27            0.962309           -0.628763
                     2017-08-28            0.975065           -0.680773
                     2017-08-29            0.985220           -0.729558
                     2017-08-30            0.992749           -0.774884
                     2017-08-31            0.997630           -0.816538

                                 cos(4,freq=YE-DEC)  sin(5,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -0.997001            0.635432
                     2017-08-17           -0.999963            0.699458
                     2017-08-18           -0.998186            0.758306
                     2017-08-19           -0.991677            0.811539
                     2017-08-20           -0.980469            0.858764
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.777597            0.997917
                     2017-08-28           -0.732494            0.988678
                     2017-08-29           -0.683919            0.972118
                     2017-08-30           -0.632103            0.948362
                     2017-08-31           -0.577292            0.917584

                                 cos(5,freq=YE-DEC)  sin(1,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.772157        1.224647e-16
                     2017-08-17            0.714673       -6.824241e-02
                     2017-08-18            0.651899       -1.361666e-01
                     2017-08-19            0.584298       -2.034560e-01
                     2017-08-20            0.512371       -2.697968e-01
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.064508       -6.825531e-01
                     2017-08-28           -0.150055       -7.308360e-01
                     2017-08-29           -0.234491       -7.757113e-01
                     2017-08-30           -0.317191       -8.169699e-01
                     2017-08-31           -0.397543       -8.544194e-01

                                 cos(1,freq=QE-DEC)  sin(2,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -1.000000       -2.449294e-16
                     2017-08-17           -0.997669        1.361666e-01
                     2017-08-18           -0.990686        2.697968e-01
                     2017-08-19           -0.979084        3.984011e-01
                     2017-08-20           -0.962917        5.195840e-01
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.730836        9.976688e-01
                     2017-08-28           -0.682553        9.976688e-01
                     2017-08-29           -0.631088        9.790841e-01
                     2017-08-30           -0.576680        9.422609e-01
                     2017-08-31           -0.519584        8.878852e-01

                                 cos(2,freq=QE-DEC)  is_new_year  dcoilwtico  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            1.000000            0       46.80
                     2017-08-17            0.990686            0       47.07
                     2017-08-18            0.962917            0       48.59
                     2017-08-19            0.917211            0       48.19
                     2017-08-20            0.854419            0       47.79
...                                             ...          ...         ...
9         SEAFOOD    2017-08-27            0.068242            0       46.82
                     2017-08-28           -0.068242            0       46.40
                     2017-08-29           -0.203456            0       46.46
                     2017-08-30           -0.334880            0       45.96
                     2017-08-31           -0.460065            0       47.26

                                 is_national_holiday  is_regional_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                False                False
                     2017-08-17                False                False
                     2017-08-18                False                False
                     2017-08-19                False                False
                     2017-08-20                False                False
...                                              ...                  ...
9         SEAFOOD    2017-08-27                False                False
                     2017-08-28                False                False
                     2017-08-29                False                False
                     2017-08-30                False                False
                     2017-08-31                False                False

                                 holiday_type_Additional  holiday_type_Bridge  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    False                False
                     2017-08-17                    False                False
                     2017-08-18                    False                False
                     2017-08-19                    False                False
                     2017-08-20                    False                False
...                                                  ...                  ...
9         SEAFOOD    2017-08-27                    False                False
                     2017-08-28                    False                False
                     2017-08-29                    False                False
                     2017-08-30                    False                False
                     2017-08-31                    False                False

                                 holiday_type_Event  holiday_type_Holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16               False                 False
                     2017-08-17               False                 False
                     2017-08-18               False                 False
                     2017-08-19               False                 False
                     2017-08-20               False                 False
...                                             ...                   ...
9         SEAFOOD    2017-08-27               False                 False
                     2017-08-28               False                 False
                     2017-08-29               False                 False
                     2017-08-30               False                 False
                     2017-08-31               False                 False

                                 holiday_type_Transfer  holiday_type_Work Day  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                  False                  False
                     2017-08-17                  False                  False
                     2017-08-18                  False                  False
                     2017-08-19                  False                  False
                     2017-08-20                  False                  False
...                                                ...                    ...
9         SEAFOOD    2017-08-27                  False                  False
                     2017-08-28                  False                  False
                     2017-08-29                  False                  False
                     2017-08-30                  False                  False
                     2017-08-31                  False                  False

                                 holiday_transferred  is_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                False       False
                     2017-08-17                False       False
                     2017-08-18                False       False
                     2017-08-19                False       False
                     2017-08-20                False       False
...                                              ...         ...
9         SEAFOOD    2017-08-27                False       False
                     2017-08-28                False       False
                     2017-08-29                False       False
                     2017-08-30                False       False
                     2017-08-31                False       False

                                 is_christmas  is_payday_15  is_payday_end  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16         False             0              0
                     2017-08-17         False             0              0
                     2017-08-18         False             0              0
                     2017-08-19         False             0              0
                     2017-08-20         False             0              0
...                                       ...           ...            ...
9         SEAFOOD    2017-08-27         False             0              0
                     2017-08-28         False             0              0
                     2017-08-29         False             0              0
                     2017-08-30         False             0              0
                     2017-08-31         False             0              1

                                 is_payday  earthquake_impact  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16          0                  0
                     2017-08-17          0                  0
                     2017-08-18          0                  0
                     2017-08-19          0                  0
                     2017-08-20          0                  0
...                                    ...                ...
9         SEAFOOD    2017-08-27          0                  0
                     2017-08-28          0                  0
                     2017-08-29          0                  0
                     2017-08-30          0                  0
                     2017-08-31          1                  0

                                 earthquake_decay  is_new_year_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16               0.0                    0
                     2017-08-17               0.0                    0
                     2017-08-18               0.0                    0
                     2017-08-19               0.0                    0
                     2017-08-20               0.0                    0
...                                           ...                  ...
9         SEAFOOD    2017-08-27               0.0                    0
                     2017-08-28               0.0                    0
                     2017-08-29               0.0                    0
                     2017-08-30               0.0                    0
                     2017-08-31               0.0                    0

                                 is_new_year_lead(2)  is_new_year_lead(3)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                    0
                     2017-08-17                    0                    0
                     2017-08-18                    0                    0
                     2017-08-19                    0                    0
                     2017-08-20                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-27                    0                    0
                     2017-08-28                    0                    0
                     2017-08-29                    0                    0
                     2017-08-30                    0                    0
                     2017-08-31                    0                    0

                                 is_new_year_lag(1)  is_new_year_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                   0                   0
                     2017-08-17                   0                   0
                     2017-08-18                   0                   0
                     2017-08-19                   0                   0
                     2017-08-20                   0                   0
...                                             ...                 ...
9         SEAFOOD    2017-08-27                   0                   0
                     2017-08-28                   0                   0
                     2017-08-29                   0                   0
                     2017-08-30                   0                   0
                     2017-08-31                   0                   0

                                 is_christmas_lag(1)  is_christmas_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                False                False
                     2017-08-17                False                False
                     2017-08-18                False                False
                     2017-08-19                False                False
                     2017-08-20                False                False
...                                              ...                  ...
9         SEAFOOD    2017-08-27                False                False
                     2017-08-28                False                False
                     2017-08-29                False                False
                     2017-08-30                False                False
                     2017-08-31                False                False

                                 is_christmas_lag(3)  is_christmas_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                False                 False
                     2017-08-17                False                 False

In [5]:
# Convert all bool types to int
train_df[train_df.select_dtypes(include = 'bool').columns] = train_df.select_dtypes(include = 'bool').astype(int)
train_df

                                      id      sales  onpromotion  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01        0   0.000000            0
                     2013-01-02     1782   2.000000            0
                     2013-01-03     3564   3.000000            0
                     2013-01-04     5346   3.000000            0
                     2013-01-05     7128   5.000000            0
...                                  ...        ...          ...
9         SEAFOOD    2017-08-11  2993759  23.830999            0
                     2017-08-12  2995541  16.859001            4
                     2017-08-13  2997323  20.000000            0
                     2017-08-14  2999105  17.000000            0
                     2017-08-15  3000887  16.000000            0

                                 is_regional_holiday  is_local_holiday   city  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                 0  Quito
                     2013-01-02                    0                 0  Quito
                     2013-01-03                    0                 0  Quito
                     2013-01-04                    0                 0  Quito
                     2013-01-05                    0                 0  Quito
...                                              ...               ...    ...
9         SEAFOOD    2017-08-11                    0                 0  Quito
                     2017-08-12                    0                 0  Quito
                     2017-08-13                    0                 0  Quito
                     2017-08-14                    0                 0  Quito
                     2017-08-15                    0                 0  Quito

                                     state type cluster  const   trend  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01  Pichincha    D      13    1.0     1.0
                     2013-01-02  Pichincha    D      13    1.0     2.0
                     2013-01-03  Pichincha    D      13    1.0     3.0
                     2013-01-04  Pichincha    D      13    1.0     4.0
                     2013-01-05  Pichincha    D      13    1.0     5.0
...                                    ...  ...     ...    ...     ...
9         SEAFOOD    2017-08-11  Pichincha    B       6    1.0  1684.0
                     2017-08-12  Pichincha    B       6    1.0  1685.0
                     2017-08-13  Pichincha    B       6    1.0  1686.0
                     2017-08-14  Pichincha    B       6    1.0  1687.0
                     2017-08-15  Pichincha    B       6    1.0  1688.0

                                 s(2,7)  s(3,7)  s(4,7)  s(5,7)  s(6,7)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01     0.0     0.0     0.0     0.0     0.0
                     2013-01-02     1.0     0.0     0.0     0.0     0.0
                     2013-01-03     0.0     1.0     0.0     0.0     0.0
                     2013-01-04     0.0     0.0     1.0     0.0     0.0
                     2013-01-05     0.0     0.0     0.0     1.0     0.0
...                                 ...     ...     ...     ...     ...
9         SEAFOOD    2017-08-11     0.0     0.0     1.0     0.0     0.0
                     2017-08-12     0.0     0.0     0.0     1.0     0.0
                     2017-08-13     0.0     0.0     0.0     0.0     1.0
                     2017-08-14     0.0     0.0     0.0     0.0     0.0
                     2017-08-15     0.0     0.0     0.0     0.0     0.0

                                 s(7,7)  sin(1,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01     0.0            0.000000
                     2013-01-02     0.0            0.017213
                     2013-01-03     0.0            0.034422
                     2013-01-04     0.0            0.051620
                     2013-01-05     0.0            0.068802
...                                 ...                 ...
9         SEAFOOD    2017-08-11     0.0           -0.628763
                     2017-08-12     0.0           -0.642055
                     2017-08-13     0.0           -0.655156
                     2017-08-14     1.0           -0.668064
                     2017-08-15     0.0           -0.680773

                                 cos(1,freq=YE-DEC)  sin(2,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.999852            0.034422
                     2013-01-03            0.999407            0.068802
                     2013-01-04            0.998667            0.103102
                     2013-01-05            0.997630            0.137279
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.777597            0.977848
                     2017-08-12           -0.766659            0.984474
                     2017-08-13           -0.755493            0.989932
                     2017-08-14           -0.744104            0.994218
                     2017-08-15           -0.732494            0.997325

                                 cos(2,freq=YE-DEC)  sin(3,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.999407            0.051620
                     2013-01-03            0.997630            0.103102
                     2013-01-04            0.994671            0.154309
                     2013-01-05            0.990532            0.205104
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.209315           -0.891981
                     2017-08-12            0.175531           -0.867456
                     2017-08-13            0.141540           -0.840618
                     2017-08-14            0.107381           -0.811539
                     2017-08-15            0.073095           -0.780296

                                 cos(3,freq=YE-DEC)  sin(4,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.998667            0.068802
                     2013-01-03            0.994671            0.137279
                     2013-01-04            0.988023            0.205104
                     2013-01-05            0.978740            0.271958
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.452072            0.409356
                     2017-08-12            0.497513            0.345612
                     2017-08-13            0.541628            0.280231
                     2017-08-14            0.584298            0.213521
                     2017-08-15            0.625411            0.145799

                                 cos(4,freq=YE-DEC)  sin(5,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.997630            0.085965
                     2013-01-03            0.990532            0.171293
                     2013-01-04            0.978740            0.255353
                     2013-01-05            0.962309            0.337523
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.912375            0.255353
                     2017-08-12           -0.938377            0.337523
                     2017-08-13           -0.959933            0.417194
                     2017-08-14           -0.976938            0.493776
                     2017-08-15           -0.989314            0.566702

                                 cos(5,freq=YE-DEC)  sin(1,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.996298            0.069756
                     2013-01-03            0.985220            0.139173
                     2013-01-04            0.966848            0.207912
                     2013-01-05            0.941317            0.275637
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.966848            0.334880
                     2017-08-12            0.941317            0.269797
                     2017-08-13            0.908818            0.203456
                     2017-08-14            0.869589            0.136167
                     2017-08-15            0.823923            0.068242

                                 cos(1,freq=QE-DEC)  sin(2,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.997564            0.139173
                     2013-01-03            0.990268            0.275637
                     2013-01-04            0.978148            0.406737
                     2013-01-05            0.961262            0.529919
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.942261           -0.631088
                     2017-08-12           -0.962917           -0.519584
                     2017-08-13           -0.979084           -0.398401
                     2017-08-14           -0.990686           -0.269797
                     2017-08-15           -0.997669           -0.136167

                                 cos(2,freq=QE-DEC)  is_new_year  dcoilwtico  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            1       93.14
                     2013-01-02            0.990268            0       93.14
                     2013-01-03            0.961262            0       92.97
                     2013-01-04            0.913545            0       93.12
                     2013-01-05            0.848048            0       93.15
...                                             ...          ...         ...
9         SEAFOOD    2017-08-11            0.775711            0       48.81
                     2017-08-12            0.854419            0       48.40
                     2017-08-13            0.917211            0       48.00
                     2017-08-14            0.962917            0       47.59
                     2017-08-15            0.990686            0       47.57

                                 is_national_holiday  holiday_type_Additional  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    1                        0
                     2013-01-02                    0                        0
                     2013-01-03                    0                        0
                     2013-01-04                    0                        0
                     2013-01-05                    1                        0
...                                              ...                      ...
9         SEAFOOD    2017-08-11                    1                        0
                     2017-08-12                    0                        0
                     2017-08-13                    0                        0
                     2017-08-14                    0                        0
                     2017-08-15                    0                        0

                                 holiday_type_Bridge  holiday_type_Event  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                   0
                     2013-01-02                    0                   0
                     2013-01-03                    0                   0
                     2013-01-04                    0                   0
                     2013-01-05                    0                   0
...                                              ...                 ...
9         SEAFOOD    2017-08-11                    0                   0
                     2017-08-12                    0                   0
                     2017-08-13                    0                   0
                     2017-08-14                    0                   0
                     2017-08-15                    0                   0

                                 holiday_type_Holiday  holiday_type_Transfer  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                     1                      0
                     2013-01-02                     0                      0
                     2013-01-03                     0                      0
                     2013-01-04                     0                      0
                     2013-01-05                     0                      0
...                                               ...                    ...
9         SEAFOOD    2017-08-11                     0                      1
                     2017-08-12                     0                      0
                     2017-08-13                     0                      0
                     2017-08-14                     0                      0
                     2017-08-15                     1                      0

                                 holiday_type_Work Day  holiday_transferred  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                      0                    0
                     2013-01-02                      0                    0
                     2013-01-03                      0                    0
                     2013-01-04                      0                    0
                     2013-01-05                      1                    0
...                                                ...                  ...
9         SEAFOOD    2017-08-11                      0                    0
                     2017-08-12                      0                    0
                     2017-08-13                      0                    0
                     2017-08-14                      0                    0
                     2017-08-15                      0                    0

                                 is_holiday  is_christmas  is_payday_15  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01           1             0             0
                     2013-01-02           0             0             0
                     2013-01-03           0             0             0
                     2013-01-04           0             0             0
                     2013-01-05           1             0             0
...                                     ...           ...           ...
9         SEAFOOD    2017-08-11           1             0             0
                     2017-08-12           0             0             0
                     2017-08-13           0             0             0
                     2017-08-14           0             0             0
                     2017-08-15           1             0             1

                                 is_payday_end  is_payday  earthquake_impact  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01              0          0                  0
                     2013-01-02              0          0                  0
                     2013-01-03              0          0                  0
                     2013-01-04              0          0                  0
                     2013-01-05              0          0                  0
...                                        ...        ...                ...
9         SEAFOOD    2017-08-11              0          0                  0
                     2017-08-12              0          0                  0
                     2017-08-13              0          0                  0
                     2017-08-14              0          0                  0
                     2017-08-15              0          1                  0

                                 earthquake_decay  is_new_year_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01               0.0                    0
                     2013-01-02               0.0                    0
                     2013-01-03               0.0                    0
                     2013-01-04               0.0                    0
                     2013-01-05               0.0                    0
...                                           ...                  ...
9         SEAFOOD    2017-08-11               0.0                    0
                     2017-08-12               0.0                    0
                     2017-08-13               0.0                    0
                     2017-08-14               0.0                    0
                     2017-08-15               0.0                    0

                                 is_new_year_lead(2)  is_new_year_lead(3)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                    0
                     2013-01-02                    0                    0
                     2013-01-03                    0                    0
                     2013-01-04                    0                    0
                     2013-01-05                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-11                    0                    0
                     2017-08-12                    0                    0
                     2017-08-13                    0                    0
                     2017-08-14                    0                    0
                     2017-08-15                    0                    0

                                 is_new_year_lag(1)  is_new_year_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                   0                   0
                     2013-01-02                   1                   0
                     2013-01-03                   0                   1
                     2013-01-04                   0                   0
                     2013-01-05                   0                   0
...                                             ...                 ...
9         SEAFOOD    2017-08-11                   0                   0
                     2017-08-12                   0                   0
                     2017-08-13                   0                   0
                     2017-08-14                   0                   0
                     2017-08-15                   0                   0

                                 is_christmas_lag(1)  is_christmas_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                    0
                     2013-01-02                    0                    0
                     2013-01-03                    0                    0
                     2013-01-04                    0                    0
                     2013-01-05                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-11                    0                    0
                     2017-08-12                    0                    0
                     2017-08-13                    0                    0
                     2017-08-14                    0                    0
                     2017-08-15                    0                    0

                                 is_christmas_lag(3)  is_christmas_lead(1)  \
store_nbr family     date

In [6]:
# Convert all bool types to int
test_df[test_df.select_dtypes(include = 'bool').columns] = test_df.select_dtypes(include = 'bool').astype(int)
test_df

                                      id  onpromotion  is_local_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16  3000888            0                 0
                     2017-08-17  3002670            0                 0
                     2017-08-18  3004452            0                 0
                     2017-08-19  3006234            0                 0
                     2017-08-20  3008016            0                 0
...                                  ...          ...               ...
9         SEAFOOD    2017-08-27  3022271            0                 0
                     2017-08-28  3024053            0                 0
                     2017-08-29  3025835            0                 0
                     2017-08-30  3027617            0                 0
                     2017-08-31  3029399            0                 0

                                  city      state type cluster  const   trend  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16  Quito  Pichincha    D      13    1.0  1689.0
                     2017-08-17  Quito  Pichincha    D      13    1.0  1690.0
                     2017-08-18  Quito  Pichincha    D      13    1.0  1691.0
                     2017-08-19  Quito  Pichincha    D      13    1.0  1692.0
                     2017-08-20  Quito  Pichincha    D      13    1.0  1693.0
...                                ...        ...  ...     ...    ...     ...
9         SEAFOOD    2017-08-27  Quito  Pichincha    B       6    1.0  1700.0
                     2017-08-28  Quito  Pichincha    B       6    1.0  1701.0
                     2017-08-29  Quito  Pichincha    B       6    1.0  1702.0
                     2017-08-30  Quito  Pichincha    B       6    1.0  1703.0
                     2017-08-31  Quito  Pichincha    B       6    1.0  1704.0

                                 s(2,7)  s(3,7)  s(4,7)  s(5,7)  s(6,7)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16     1.0     0.0     0.0     0.0     0.0
                     2017-08-17     0.0     1.0     0.0     0.0     0.0
                     2017-08-18     0.0     0.0     1.0     0.0     0.0
                     2017-08-19     0.0     0.0     0.0     1.0     0.0
                     2017-08-20     0.0     0.0     0.0     0.0     1.0
...                                 ...     ...     ...     ...     ...
9         SEAFOOD    2017-08-27     0.0     0.0     0.0     0.0     1.0
                     2017-08-28     0.0     0.0     0.0     0.0     0.0
                     2017-08-29     0.0     0.0     0.0     0.0     0.0
                     2017-08-30     1.0     0.0     0.0     0.0     0.0
                     2017-08-31     0.0     1.0     0.0     0.0     0.0

                                 s(7,7)  sin(1,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16     0.0           -0.693281
                     2017-08-17     0.0           -0.705584
                     2017-08-18     0.0           -0.717677
                     2017-08-19     0.0           -0.729558
                     2017-08-20     0.0           -0.741222
...                                 ...                 ...
9         SEAFOOD    2017-08-27     0.0           -0.816538
                     2017-08-28     1.0           -0.826354
                     2017-08-29     0.0           -0.835925
                     2017-08-30     0.0           -0.845249
                     2017-08-31     0.0           -0.854322

                                 cos(1,freq=YE-DEC)  sin(2,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -0.720667            0.999250
                     2017-08-17           -0.708627            0.999991
                     2017-08-18           -0.696376            0.999546
                     2017-08-19           -0.683919            0.997917
                     2017-08-20           -0.671260            0.995105
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.577292            0.942761
                     2017-08-28           -0.563151            0.930724
                     2017-08-29           -0.548843            0.917584
                     2017-08-30           -0.534373            0.903356
                     2017-08-31           -0.519744            0.888057

                                 cos(2,freq=YE-DEC)  sin(3,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.038722           -0.746972
                     2017-08-17            0.004304           -0.711657
                     2017-08-18           -0.030120           -0.674444
                     2017-08-19           -0.064508           -0.635432
                     2017-08-20           -0.098820           -0.594727
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.333469           -0.271958
                     2017-08-28           -0.365723           -0.221922
                     2017-08-29           -0.397543           -0.171293
                     2017-08-30           -0.428892           -0.120208
                     2017-08-31           -0.459733           -0.068802

                                 cos(3,freq=YE-DEC)  sin(4,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.664855            0.077386
                     2017-08-17            0.702527            0.008607
                     2017-08-18            0.738326           -0.060213
                     2017-08-19            0.772157           -0.128748
                     2017-08-20            0.803928           -0.196673
...                                             ...                 ...
9         SEAFOOD    2017-08-27            0.962309           -0.628763
                     2017-08-28            0.975065           -0.680773
                     2017-08-29            0.985220           -0.729558
                     2017-08-30            0.992749           -0.774884
                     2017-08-31            0.997630           -0.816538

                                 cos(4,freq=YE-DEC)  sin(5,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -0.997001            0.635432
                     2017-08-17           -0.999963            0.699458
                     2017-08-18           -0.998186            0.758306
                     2017-08-19           -0.991677            0.811539
                     2017-08-20           -0.980469            0.858764
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.777597            0.997917
                     2017-08-28           -0.732494            0.988678
                     2017-08-29           -0.683919            0.972118
                     2017-08-30           -0.632103            0.948362
                     2017-08-31           -0.577292            0.917584

                                 cos(5,freq=YE-DEC)  sin(1,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.772157        1.224647e-16
                     2017-08-17            0.714673       -6.824241e-02
                     2017-08-18            0.651899       -1.361666e-01
                     2017-08-19            0.584298       -2.034560e-01
                     2017-08-20            0.512371       -2.697968e-01
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.064508       -6.825531e-01
                     2017-08-28           -0.150055       -7.308360e-01
                     2017-08-29           -0.234491       -7.757113e-01
                     2017-08-30           -0.317191       -8.169699e-01
                     2017-08-31           -0.397543       -8.544194e-01

                                 cos(1,freq=QE-DEC)  sin(2,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -1.000000       -2.449294e-16
                     2017-08-17           -0.997669        1.361666e-01
                     2017-08-18           -0.990686        2.697968e-01
                     2017-08-19           -0.979084        3.984011e-01
                     2017-08-20           -0.962917        5.195840e-01
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.730836        9.976688e-01
                     2017-08-28           -0.682553        9.976688e-01
                     2017-08-29           -0.631088        9.790841e-01
                     2017-08-30           -0.576680        9.422609e-01
                     2017-08-31           -0.519584        8.878852e-01

                                 cos(2,freq=QE-DEC)  is_new_year  dcoilwtico  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            1.000000            0       46.80
                     2017-08-17            0.990686            0       47.07
                     2017-08-18            0.962917            0       48.59
                     2017-08-19            0.917211            0       48.19
                     2017-08-20            0.854419            0       47.79
...                                             ...          ...         ...
9         SEAFOOD    2017-08-27            0.068242            0       46.82
                     2017-08-28           -0.068242            0       46.40
                     2017-08-29           -0.203456            0       46.46
                     2017-08-30           -0.334880            0       45.96
                     2017-08-31           -0.460065            0       47.26

                                 is_national_holiday  is_regional_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                    0
                     2017-08-17                    0                    0
                     2017-08-18                    0                    0
                     2017-08-19                    0                    0
                     2017-08-20                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-27                    0                    0
                     2017-08-28                    0                    0
                     2017-08-29                    0                    0
                     2017-08-30                    0                    0
                     2017-08-31                    0                    0

                                 holiday_type_Additional  holiday_type_Bridge  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                        0                    0
                     2017-08-17                        0                    0
                     2017-08-18                        0                    0
                     2017-08-19                        0                    0
                     2017-08-20                        0                    0
...                                                  ...                  ...
9         SEAFOOD    2017-08-27                        0                    0
                     2017-08-28                        0                    0
                     2017-08-29                        0                    0
                     2017-08-30                        0                    0
                     2017-08-31                        0                    0

                                 holiday_type_Event  holiday_type_Holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                   0                     0
                     2017-08-17                   0                     0
                     2017-08-18                   0                     0
                     2017-08-19                   0                     0
                     2017-08-20                   0                     0
...                                             ...                   ...
9         SEAFOOD    2017-08-27                   0                     0
                     2017-08-28                   0                     0
                     2017-08-29                   0                     0
                     2017-08-30                   0                     0
                     2017-08-31                   0                     0

                                 holiday_type_Transfer  holiday_type_Work Day  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                      0                      0
                     2017-08-17                      0                      0
                     2017-08-18                      0                      0
                     2017-08-19                      0                      0
                     2017-08-20                      0                      0
...                                                ...                    ...
9         SEAFOOD    2017-08-27                      0                      0
                     2017-08-28                      0                      0
                     2017-08-29                      0                      0
                     2017-08-30                      0                      0
                     2017-08-31                      0                      0

                                 holiday_transferred  is_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0           0
                     2017-08-17                    0           0
                     2017-08-18                    0           0
                     2017-08-19                    0           0
                     2017-08-20                    0           0
...                                              ...         ...
9         SEAFOOD    2017-08-27                    0           0
                     2017-08-28                    0           0
                     2017-08-29                    0           0
                     2017-08-30                    0           0
                     2017-08-31                    0           0

                                 is_christmas  is_payday_15  is_payday_end  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16             0             0              0
                     2017-08-17             0             0              0
                     2017-08-18             0             0              0
                     2017-08-19             0             0              0
                     2017-08-20             0             0              0
...                                       ...           ...            ...
9         SEAFOOD    2017-08-27             0             0              0
                     2017-08-28             0             0              0
                     2017-08-29             0             0              0
                     2017-08-30             0             0              0
                     2017-08-31             0             0              1

                                 is_payday  earthquake_impact  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16          0                  0
                     2017-08-17          0                  0
                     2017-08-18          0                  0
                     2017-08-19          0                  0
                     2017-08-20          0                  0
...                                    ...                ...
9         SEAFOOD    2017-08-27          0                  0
                     2017-08-28          0                  0
                     2017-08-29          0                  0
                     2017-08-30          0                  0
                     2017-08-31          1                  0

                                 earthquake_decay  is_new_year_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16               0.0                    0
                     2017-08-17               0.0                    0
                     2017-08-18               0.0                    0
                     2017-08-19               0.0                    0
                     2017-08-20               0.0                    0
...                                           ...                  ...
9         SEAFOOD    2017-08-27               0.0                    0
                     2017-08-28               0.0                    0
                     2017-08-29               0.0                    0
                     2017-08-30               0.0                    0
                     2017-08-31               0.0                    0

                                 is_new_year_lead(2)  is_new_year_lead(3)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                    0
                     2017-08-17                    0                    0
                     2017-08-18                    0                    0
                     2017-08-19                    0                    0
                     2017-08-20                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-27                    0                    0
                     2017-08-28                    0                    0
                     2017-08-29                    0                    0
                     2017-08-30                    0                    0
                     2017-08-31                    0                    0

                                 is_new_year_lag(1)  is_new_year_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                   0                   0
                     2017-08-17                   0                   0
                     2017-08-18                   0                   0
                     2017-08-19                   0                   0
                     2017-08-20                   0                   0
...                                             ...                 ...
9         SEAFOOD    2017-08-27                   0                   0
                     2017-08-28                   0                   0
                     2017-08-29                   0                   0
                     2017-08-30                   0                   0
                     2017-08-31                   0                   0

                                 is_christmas_lag(1)  is_christmas_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                    0
                     2017-08-17                    0                    0
                     2017-08-18                    0                    0
                     2017-08-19                    0                    0
                     2017-08-20                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-27                    0                    0
                     2017-08-28                    0                    0
                     2017-08-29                    0                    0
                     2017-08-30                    0                    0
                     2017-08-31                    0                    0

                                 is_christmas_lag(3)  is_christmas_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                     0
                     2017-08-17                    0                     0

In [7]:
# Get a list of the columns and rearrange it
col_list = list(test_df.columns)
col_list

['id',
 'onpromotion',
 'is_local_holiday',
 'city',
 'state',
 'type',
 'cluster',
 'const',
 'trend',
 's(2,7)',
 's(3,7)',
 's(4,7)',
 's(5,7)',
 's(6,7)',
 's(7,7)',
 'sin(1,freq=YE-DEC)',
 'cos(1,freq=YE-DEC)',
 'sin(2,freq=YE-DEC)',
 'cos(2,freq=YE-DEC)',
 'sin(3,freq=YE-DEC)',
 'cos(3,freq=YE-DEC)',
 'sin(4,freq=YE-DEC)',
 'cos(4,freq=YE-DEC)',
 'sin(5,freq=YE-DEC)',
 'cos(5,freq=YE-DEC)',
 'sin(1,freq=QE-DEC)',
 'cos(1,freq=QE-DEC)',
 'sin(2,freq=QE-DEC)',
 'cos(2,freq=QE-DEC)',
 'is_new_year',
 'dcoilwtico',
 'is_national_holiday',
 'is_regional_holiday',
 'holiday_type_Additional',
 'holiday_type_Bridge',
 'holiday_type_Event',
 'holiday_type_Holiday',
 'holiday_type_Transfer',
 'holiday_type_Work Day',
 'holiday_transferred',
 'is_holiday',
 'is_christmas',
 'is_payday_15',
 'is_payday_end',
 'is_payday',
 'earthquake_impact',
 'earthquake_decay',
 'is_new_year_lead(1)',
 'is_new_year_lead(2)',
 'is_new_year_lead(3)',
 'is_new_year_lag(1)',
 'is_new_year_lag(2)',
 'is_christmas_lag(1)',
 'is_christmas_lag(2)',
 'is_christmas_lag(3)',
 'is_christmas_lead(1)',
 'is_christmas_lead(2)',
 'dcoilwtico_lag',
 'is_holiday_lag',
 'is_holiday_lead',
 'is_payday_lag',
 'is_payday_lead']

In [8]:
# List for test set
test_list = [
     'city',
     'state',
     'type',
     'cluster',
     'const',
     'trend',
     'id',
     'onpromotion',
     's(2,7)',
     's(3,7)',
     's(4,7)',
     's(5,7)',
     's(6,7)',
     's(7,7)',
     'sin(1,freq=YE-DEC)',
     'cos(1,freq=YE-DEC)',
     'sin(2,freq=YE-DEC)',
     'cos(2,freq=YE-DEC)',
     'sin(3,freq=YE-DEC)',
     'cos(3,freq=YE-DEC)',
     'sin(4,freq=YE-DEC)',
     'cos(4,freq=YE-DEC)',
     'sin(5,freq=YE-DEC)',
     'cos(5,freq=YE-DEC)',
     'sin(1,freq=QE-DEC)',
     'cos(1,freq=QE-DEC)',
     'sin(2,freq=QE-DEC)',
     'cos(2,freq=QE-DEC)',
     'dcoilwtico',
     'dcoilwtico_lag',
     'is_national_holiday',
     'is_regional_holiday',
     'is_local_holiday',
     'holiday_type_Additional',
     'holiday_type_Bridge',
     'holiday_type_Event',
     'holiday_type_Holiday',
     'holiday_type_Transfer',
     'holiday_type_Work Day',
     'holiday_transferred',
     'is_holiday_lead',
     'is_holiday',
     'is_holiday_lag',
     'is_christmas_lead(2)',
     'is_christmas_lead(1)',
     'is_christmas',
     'is_christmas_lag(1)',
     'is_christmas_lag(2)',
     'is_christmas_lag(3)',
     'is_new_year_lead(3)',
     'is_new_year_lead(2)',
     'is_new_year_lead(1)',
     'is_new_year',
     'is_new_year_lag(1)',
     'is_new_year_lag(2)',
     'is_payday_15',
     'is_payday_end',
     'is_payday_lead',
     'is_payday',
     'is_payday_lag',
     'earthquake_impact',
     'earthquake_decay',
]

In [9]:
test_df = test_df[test_list]
test_df

                                  city      state type cluster  const   trend  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16  Quito  Pichincha    D      13    1.0  1689.0
                     2017-08-17  Quito  Pichincha    D      13    1.0  1690.0
                     2017-08-18  Quito  Pichincha    D      13    1.0  1691.0
                     2017-08-19  Quito  Pichincha    D      13    1.0  1692.0
                     2017-08-20  Quito  Pichincha    D      13    1.0  1693.0
...                                ...        ...  ...     ...    ...     ...
9         SEAFOOD    2017-08-27  Quito  Pichincha    B       6    1.0  1700.0
                     2017-08-28  Quito  Pichincha    B       6    1.0  1701.0
                     2017-08-29  Quito  Pichincha    B       6    1.0  1702.0
                     2017-08-30  Quito  Pichincha    B       6    1.0  1703.0
                     2017-08-31  Quito  Pichincha    B       6    1.0  1704.0

                                      id  onpromotion  s(2,7)  s(3,7)  s(4,7)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16  3000888            0     1.0     0.0     0.0
                     2017-08-17  3002670            0     0.0     1.0     0.0
                     2017-08-18  3004452            0     0.0     0.0     1.0
                     2017-08-19  3006234            0     0.0     0.0     0.0
                     2017-08-20  3008016            0     0.0     0.0     0.0
...                                  ...          ...     ...     ...     ...
9         SEAFOOD    2017-08-27  3022271            0     0.0     0.0     0.0
                     2017-08-28  3024053            0     0.0     0.0     0.0
                     2017-08-29  3025835            0     0.0     0.0     0.0
                     2017-08-30  3027617            0     1.0     0.0     0.0
                     2017-08-31  3029399            0     0.0     1.0     0.0

                                 s(5,7)  s(6,7)  s(7,7)  sin(1,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16     0.0     0.0     0.0           -0.693281
                     2017-08-17     0.0     0.0     0.0           -0.705584
                     2017-08-18     0.0     0.0     0.0           -0.717677
                     2017-08-19     1.0     0.0     0.0           -0.729558
                     2017-08-20     0.0     1.0     0.0           -0.741222
...                                 ...     ...     ...                 ...
9         SEAFOOD    2017-08-27     0.0     1.0     0.0           -0.816538
                     2017-08-28     0.0     0.0     1.0           -0.826354
                     2017-08-29     0.0     0.0     0.0           -0.835925
                     2017-08-30     0.0     0.0     0.0           -0.845249
                     2017-08-31     0.0     0.0     0.0           -0.854322

                                 cos(1,freq=YE-DEC)  sin(2,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -0.720667            0.999250
                     2017-08-17           -0.708627            0.999991
                     2017-08-18           -0.696376            0.999546
                     2017-08-19           -0.683919            0.997917
                     2017-08-20           -0.671260            0.995105
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.577292            0.942761
                     2017-08-28           -0.563151            0.930724
                     2017-08-29           -0.548843            0.917584
                     2017-08-30           -0.534373            0.903356
                     2017-08-31           -0.519744            0.888057

                                 cos(2,freq=YE-DEC)  sin(3,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.038722           -0.746972
                     2017-08-17            0.004304           -0.711657
                     2017-08-18           -0.030120           -0.674444
                     2017-08-19           -0.064508           -0.635432
                     2017-08-20           -0.098820           -0.594727
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.333469           -0.271958
                     2017-08-28           -0.365723           -0.221922
                     2017-08-29           -0.397543           -0.171293
                     2017-08-30           -0.428892           -0.120208
                     2017-08-31           -0.459733           -0.068802

                                 cos(3,freq=YE-DEC)  sin(4,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.664855            0.077386
                     2017-08-17            0.702527            0.008607
                     2017-08-18            0.738326           -0.060213
                     2017-08-19            0.772157           -0.128748
                     2017-08-20            0.803928           -0.196673
...                                             ...                 ...
9         SEAFOOD    2017-08-27            0.962309           -0.628763
                     2017-08-28            0.975065           -0.680773
                     2017-08-29            0.985220           -0.729558
                     2017-08-30            0.992749           -0.774884
                     2017-08-31            0.997630           -0.816538

                                 cos(4,freq=YE-DEC)  sin(5,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -0.997001            0.635432
                     2017-08-17           -0.999963            0.699458
                     2017-08-18           -0.998186            0.758306
                     2017-08-19           -0.991677            0.811539
                     2017-08-20           -0.980469            0.858764
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.777597            0.997917
                     2017-08-28           -0.732494            0.988678
                     2017-08-29           -0.683919            0.972118
                     2017-08-30           -0.632103            0.948362
                     2017-08-31           -0.577292            0.917584

                                 cos(5,freq=YE-DEC)  sin(1,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            0.772157        1.224647e-16
                     2017-08-17            0.714673       -6.824241e-02
                     2017-08-18            0.651899       -1.361666e-01
                     2017-08-19            0.584298       -2.034560e-01
                     2017-08-20            0.512371       -2.697968e-01
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.064508       -6.825531e-01
                     2017-08-28           -0.150055       -7.308360e-01
                     2017-08-29           -0.234491       -7.757113e-01
                     2017-08-30           -0.317191       -8.169699e-01
                     2017-08-31           -0.397543       -8.544194e-01

                                 cos(1,freq=QE-DEC)  sin(2,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           -1.000000       -2.449294e-16
                     2017-08-17           -0.997669        1.361666e-01
                     2017-08-18           -0.990686        2.697968e-01
                     2017-08-19           -0.979084        3.984011e-01
                     2017-08-20           -0.962917        5.195840e-01
...                                             ...                 ...
9         SEAFOOD    2017-08-27           -0.730836        9.976688e-01
                     2017-08-28           -0.682553        9.976688e-01
                     2017-08-29           -0.631088        9.790841e-01
                     2017-08-30           -0.576680        9.422609e-01
                     2017-08-31           -0.519584        8.878852e-01

                                 cos(2,freq=QE-DEC)  dcoilwtico  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16            1.000000       46.80
                     2017-08-17            0.990686       47.07
                     2017-08-18            0.962917       48.59
                     2017-08-19            0.917211       48.19
                     2017-08-20            0.854419       47.79
...                                             ...         ...
9         SEAFOOD    2017-08-27            0.068242       46.82
                     2017-08-28           -0.068242       46.40
                     2017-08-29           -0.203456       46.46
                     2017-08-30           -0.334880       45.96
                     2017-08-31           -0.460065       47.26

                                 dcoilwtico_lag  is_national_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           47.57                    0
                     2017-08-17           46.80                    0
                     2017-08-18           47.07                    0
                     2017-08-19           48.59                    0
                     2017-08-20           48.19                    0
...                                         ...                  ...
9         SEAFOOD    2017-08-27           47.23                    0
                     2017-08-28           46.82                    0
                     2017-08-29           46.40                    0
                     2017-08-30           46.46                    0
                     2017-08-31           45.96                    0

                                 is_regional_holiday  is_local_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                 0
                     2017-08-17                    0                 0
                     2017-08-18                    0                 0
                     2017-08-19                    0                 0
                     2017-08-20                    0                 0
...                                              ...               ...
9         SEAFOOD    2017-08-27                    0                 0
                     2017-08-28                    0                 0
                     2017-08-29                    0                 0
                     2017-08-30                    0                 0
                     2017-08-31                    0                 0

                                 holiday_type_Additional  holiday_type_Bridge  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                        0                    0
                     2017-08-17                        0                    0
                     2017-08-18                        0                    0
                     2017-08-19                        0                    0
                     2017-08-20                        0                    0
...                                                  ...                  ...
9         SEAFOOD    2017-08-27                        0                    0
                     2017-08-28                        0                    0
                     2017-08-29                        0                    0
                     2017-08-30                        0                    0
                     2017-08-31                        0                    0

                                 holiday_type_Event  holiday_type_Holiday  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                   0                     0
                     2017-08-17                   0                     0
                     2017-08-18                   0                     0
                     2017-08-19                   0                     0
                     2017-08-20                   0                     0
...                                             ...                   ...
9         SEAFOOD    2017-08-27                   0                     0
                     2017-08-28                   0                     0
                     2017-08-29                   0                     0
                     2017-08-30                   0                     0
                     2017-08-31                   0                     0

                                 holiday_type_Transfer  holiday_type_Work Day  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                      0                      0
                     2017-08-17                      0                      0
                     2017-08-18                      0                      0
                     2017-08-19                      0                      0
                     2017-08-20                      0                      0
...                                                ...                    ...
9         SEAFOOD    2017-08-27                      0                      0
                     2017-08-28                      0                      0
                     2017-08-29                      0                      0
                     2017-08-30                      0                      0
                     2017-08-31                      0                      0

                                 holiday_transferred  is_holiday_lead  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                0
                     2017-08-17                    0                0
                     2017-08-18                    0                0
                     2017-08-19                    0                0
                     2017-08-20                    0                0
...                                              ...              ...
9         SEAFOOD    2017-08-27                    0                0
                     2017-08-28                    0                0
                     2017-08-29                    0                0
                     2017-08-30                    0                0
                     2017-08-31                    0                0

                                 is_holiday  is_holiday_lag  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16           0               1
                     2017-08-17           0               0
                     2017-08-18           0               0
                     2017-08-19           0               0
                     2017-08-20           0               0
...                                     ...             ...
9         SEAFOOD    2017-08-27           0               0
                     2017-08-28           0               0
                     2017-08-29           0               0
                     2017-08-30           0               0
                     2017-08-31           0               0

                                 is_christmas_lead(2)  is_christmas_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                     0                     0
                     2017-08-17                     0                     0
                     2017-08-18                     0                     0
                     2017-08-19                     0                     0
                     2017-08-20                     0                     0
...                                               ...                   ...
9         SEAFOOD    2017-08-27                     0                     0
                     2017-08-28                     0                     0
                     2017-08-29                     0                     0
                     2017-08-30                     0                     0
                     2017-08-31                     0                     0

                                 is_christmas  is_christmas_lag(1)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16             0                    0
                     2017-08-17             0                    0
                     2017-08-18             0                    0
                     2017-08-19             0                    0
                     2017-08-20             0                    0
...                                       ...                  ...
9         SEAFOOD    2017-08-27             0                    0
                     2017-08-28             0                    0
                     2017-08-29             0                    0
                     2017-08-30             0                    0
                     2017-08-31             0                    0

                                 is_christmas_lag(2)  is_christmas_lag(3)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                    0
                     2017-08-17                    0                    0
                     2017-08-18                    0                    0
                     2017-08-19                    0                    0
                     2017-08-20                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-27                    0                    0
                     2017-08-28                    0                    0
                     2017-08-29                    0                    0
                     2017-08-30                    0                    0
                     2017-08-31                    0                    0

                                 is_new_year_lead(3)  is_new_year_lead(2)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0                    0
                     2017-08-17                    0                    0
                     2017-08-18                    0                    0
                     2017-08-19                    0                    0
                     2017-08-20                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-27                    0                    0
                     2017-08-28                    0                    0
                     2017-08-29                    0                    0
                     2017-08-30                    0                    0
                     2017-08-31                    0                    0

                                 is_new_year_lead(1)  is_new_year  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                    0            0
                     2017-08-17                    0            0
                     2017-08-18                    0            0
                     2017-08-19                    0            0
                     2017-08-20                    0            0
...                                              ...          ...
9         SEAFOOD    2017-08-27                    0            0
                     2017-08-28                    0            0
                     2017-08-29                    0            0
                     2017-08-30                    0            0
                     2017-08-31                    0            0

                                 is_new_year_lag(1)  is_new_year_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2017-08-16                   0                   0
                     2017-08-17                   0                   0
                     2017-08-18                   0                   0

In [10]:
# List for train set
train_list = [
     'city',
     'state',
     'type',
     'cluster',
     'const',
     'trend',
     'id',
     'onpromotion',
     's(2,7)',
     's(3,7)',
     's(4,7)',
     's(5,7)',
     's(6,7)',
     's(7,7)',
     'sin(1,freq=YE-DEC)',
     'cos(1,freq=YE-DEC)',
     'sin(2,freq=YE-DEC)',
     'cos(2,freq=YE-DEC)',
     'sin(3,freq=YE-DEC)',
     'cos(3,freq=YE-DEC)',
     'sin(4,freq=YE-DEC)',
     'cos(4,freq=YE-DEC)',
     'sin(5,freq=YE-DEC)',
     'cos(5,freq=YE-DEC)',
     'sin(1,freq=QE-DEC)',
     'cos(1,freq=QE-DEC)',
     'sin(2,freq=QE-DEC)',
     'cos(2,freq=QE-DEC)',
     'dcoilwtico',
     'dcoilwtico_lag',
     'is_national_holiday',
     'is_regional_holiday',
     'is_local_holiday',
     'holiday_type_Additional',
     'holiday_type_Bridge',
     'holiday_type_Event',
     'holiday_type_Holiday',
     'holiday_type_Transfer',
     'holiday_type_Work Day',
     'holiday_transferred',
     'is_holiday_lead',
     'is_holiday',
     'is_holiday_lag',
     'is_christmas_lead(2)',
     'is_christmas_lead(1)',
     'is_christmas',
     'is_christmas_lag(1)',
     'is_christmas_lag(2)',
     'is_christmas_lag(3)',
     'is_new_year_lead(3)',
     'is_new_year_lead(2)',
     'is_new_year_lead(1)',
     'is_new_year',
     'is_new_year_lag(1)',
     'is_new_year_lag(2)',
     'is_payday_15',
     'is_payday_end',
     'is_payday_lead',
     'is_payday',
     'is_payday_lag',
     'earthquake_impact',
     'earthquake_decay',
     'sales'
]

In [11]:
train_df = train_df[train_list]
train_df

                                  city      state type cluster  const   trend  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01  Quito  Pichincha    D      13    1.0     1.0
                     2013-01-02  Quito  Pichincha    D      13    1.0     2.0
                     2013-01-03  Quito  Pichincha    D      13    1.0     3.0
                     2013-01-04  Quito  Pichincha    D      13    1.0     4.0
                     2013-01-05  Quito  Pichincha    D      13    1.0     5.0
...                                ...        ...  ...     ...    ...     ...
9         SEAFOOD    2017-08-11  Quito  Pichincha    B       6    1.0  1684.0
                     2017-08-12  Quito  Pichincha    B       6    1.0  1685.0
                     2017-08-13  Quito  Pichincha    B       6    1.0  1686.0
                     2017-08-14  Quito  Pichincha    B       6    1.0  1687.0
                     2017-08-15  Quito  Pichincha    B       6    1.0  1688.0

                                      id  onpromotion  s(2,7)  s(3,7)  s(4,7)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01        0            0     0.0     0.0     0.0
                     2013-01-02     1782            0     1.0     0.0     0.0
                     2013-01-03     3564            0     0.0     1.0     0.0
                     2013-01-04     5346            0     0.0     0.0     1.0
                     2013-01-05     7128            0     0.0     0.0     0.0
...                                  ...          ...     ...     ...     ...
9         SEAFOOD    2017-08-11  2993759            0     0.0     0.0     1.0
                     2017-08-12  2995541            4     0.0     0.0     0.0
                     2017-08-13  2997323            0     0.0     0.0     0.0
                     2017-08-14  2999105            0     0.0     0.0     0.0
                     2017-08-15  3000887            0     0.0     0.0     0.0

                                 s(5,7)  s(6,7)  s(7,7)  sin(1,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01     0.0     0.0     0.0            0.000000
                     2013-01-02     0.0     0.0     0.0            0.017213
                     2013-01-03     0.0     0.0     0.0            0.034422
                     2013-01-04     0.0     0.0     0.0            0.051620
                     2013-01-05     1.0     0.0     0.0            0.068802
...                                 ...     ...     ...                 ...
9         SEAFOOD    2017-08-11     0.0     0.0     0.0           -0.628763
                     2017-08-12     1.0     0.0     0.0           -0.642055
                     2017-08-13     0.0     1.0     0.0           -0.655156
                     2017-08-14     0.0     0.0     1.0           -0.668064
                     2017-08-15     0.0     0.0     0.0           -0.680773

                                 cos(1,freq=YE-DEC)  sin(2,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.999852            0.034422
                     2013-01-03            0.999407            0.068802
                     2013-01-04            0.998667            0.103102
                     2013-01-05            0.997630            0.137279
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.777597            0.977848
                     2017-08-12           -0.766659            0.984474
                     2017-08-13           -0.755493            0.989932
                     2017-08-14           -0.744104            0.994218
                     2017-08-15           -0.732494            0.997325

                                 cos(2,freq=YE-DEC)  sin(3,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.999407            0.051620
                     2013-01-03            0.997630            0.103102
                     2013-01-04            0.994671            0.154309
                     2013-01-05            0.990532            0.205104
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.209315           -0.891981
                     2017-08-12            0.175531           -0.867456
                     2017-08-13            0.141540           -0.840618
                     2017-08-14            0.107381           -0.811539
                     2017-08-15            0.073095           -0.780296

                                 cos(3,freq=YE-DEC)  sin(4,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.998667            0.068802
                     2013-01-03            0.994671            0.137279
                     2013-01-04            0.988023            0.205104
                     2013-01-05            0.978740            0.271958
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.452072            0.409356
                     2017-08-12            0.497513            0.345612
                     2017-08-13            0.541628            0.280231
                     2017-08-14            0.584298            0.213521
                     2017-08-15            0.625411            0.145799

                                 cos(4,freq=YE-DEC)  sin(5,freq=YE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.997630            0.085965
                     2013-01-03            0.990532            0.171293
                     2013-01-04            0.978740            0.255353
                     2013-01-05            0.962309            0.337523
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.912375            0.255353
                     2017-08-12           -0.938377            0.337523
                     2017-08-13           -0.959933            0.417194
                     2017-08-14           -0.976938            0.493776
                     2017-08-15           -0.989314            0.566702

                                 cos(5,freq=YE-DEC)  sin(1,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.996298            0.069756
                     2013-01-03            0.985220            0.139173
                     2013-01-04            0.966848            0.207912
                     2013-01-05            0.941317            0.275637
...                                             ...                 ...
9         SEAFOOD    2017-08-11            0.966848            0.334880
                     2017-08-12            0.941317            0.269797
                     2017-08-13            0.908818            0.203456
                     2017-08-14            0.869589            0.136167
                     2017-08-15            0.823923            0.068242

                                 cos(1,freq=QE-DEC)  sin(2,freq=QE-DEC)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000            0.000000
                     2013-01-02            0.997564            0.139173
                     2013-01-03            0.990268            0.275637
                     2013-01-04            0.978148            0.406737
                     2013-01-05            0.961262            0.529919
...                                             ...                 ...
9         SEAFOOD    2017-08-11           -0.942261           -0.631088
                     2017-08-12           -0.962917           -0.519584
                     2017-08-13           -0.979084           -0.398401
                     2017-08-14           -0.990686           -0.269797
                     2017-08-15           -0.997669           -0.136167

                                 cos(2,freq=QE-DEC)  dcoilwtico  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01            1.000000       93.14
                     2013-01-02            0.990268       93.14
                     2013-01-03            0.961262       92.97
                     2013-01-04            0.913545       93.12
                     2013-01-05            0.848048       93.15
...                                             ...         ...
9         SEAFOOD    2017-08-11            0.775711       48.81
                     2017-08-12            0.854419       48.40
                     2017-08-13            0.917211       48.00
                     2017-08-14            0.962917       47.59
                     2017-08-15            0.990686       47.57

                                 dcoilwtico_lag  is_national_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01           94.88                    1
                     2013-01-02           93.14                    0
                     2013-01-03           93.14                    0
                     2013-01-04           92.97                    0
                     2013-01-05           93.12                    1
...                                         ...                  ...
9         SEAFOOD    2017-08-11           48.54                    1
                     2017-08-12           48.81                    0
                     2017-08-13           48.40                    0
                     2017-08-14           48.00                    0
                     2017-08-15           47.59                    0

                                 is_regional_holiday  is_local_holiday  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                 0
                     2013-01-02                    0                 0
                     2013-01-03                    0                 0
                     2013-01-04                    0                 0
                     2013-01-05                    0                 0
...                                              ...               ...
9         SEAFOOD    2017-08-11                    0                 0
                     2017-08-12                    0                 0
                     2017-08-13                    0                 0
                     2017-08-14                    0                 0
                     2017-08-15                    0                 0

                                 holiday_type_Additional  holiday_type_Bridge  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                        0                    0
                     2013-01-02                        0                    0
                     2013-01-03                        0                    0
                     2013-01-04                        0                    0
                     2013-01-05                        0                    0
...                                                  ...                  ...
9         SEAFOOD    2017-08-11                        0                    0
                     2017-08-12                        0                    0
                     2017-08-13                        0                    0
                     2017-08-14                        0                    0
                     2017-08-15                        0                    0

                                 holiday_type_Event  holiday_type_Holiday  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                   0                     1
                     2013-01-02                   0                     0
                     2013-01-03                   0                     0
                     2013-01-04                   0                     0
                     2013-01-05                   0                     0
...                                             ...                   ...
9         SEAFOOD    2017-08-11                   0                     0
                     2017-08-12                   0                     0
                     2017-08-13                   0                     0
                     2017-08-14                   0                     0
                     2017-08-15                   0                     1

                                 holiday_type_Transfer  holiday_type_Work Day  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                      0                      0
                     2013-01-02                      0                      0
                     2013-01-03                      0                      0
                     2013-01-04                      0                      0
                     2013-01-05                      0                      1
...                                                ...                    ...
9         SEAFOOD    2017-08-11                      1                      0
                     2017-08-12                      0                      0
                     2017-08-13                      0                      0
                     2017-08-14                      0                      0
                     2017-08-15                      0                      0

                                 holiday_transferred  is_holiday_lead  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                0
                     2013-01-02                    0                0
                     2013-01-03                    0                0
                     2013-01-04                    0                1
                     2013-01-05                    0                0
...                                              ...              ...
9         SEAFOOD    2017-08-11                    0                0
                     2017-08-12                    0                0
                     2017-08-13                    0                0
                     2017-08-14                    0                1
                     2017-08-15                    0                0

                                 is_holiday  is_holiday_lag  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01           1               1
                     2013-01-02           0               1
                     2013-01-03           0               0
                     2013-01-04           0               0
                     2013-01-05           1               0
...                                     ...             ...
9         SEAFOOD    2017-08-11           1               0
                     2017-08-12           0               1
                     2017-08-13           0               0
                     2017-08-14           0               0
                     2017-08-15           1               0

                                 is_christmas_lead(2)  is_christmas_lead(1)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                     0                     0
                     2013-01-02                     0                     0
                     2013-01-03                     0                     0
                     2013-01-04                     0                     0
                     2013-01-05                     0                     0
...                                               ...                   ...
9         SEAFOOD    2017-08-11                     0                     0
                     2017-08-12                     0                     0
                     2017-08-13                     0                     0
                     2017-08-14                     0                     0
                     2017-08-15                     0                     0

                                 is_christmas  is_christmas_lag(1)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01             0                    0
                     2013-01-02             0                    0
                     2013-01-03             0                    0
                     2013-01-04             0                    0
                     2013-01-05             0                    0
...                                       ...                  ...
9         SEAFOOD    2017-08-11             0                    0
                     2017-08-12             0                    0
                     2017-08-13             0                    0
                     2017-08-14             0                    0
                     2017-08-15             0                    0

                                 is_christmas_lag(2)  is_christmas_lag(3)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                    0
                     2013-01-02                    0                    0
                     2013-01-03                    0                    0
                     2013-01-04                    0                    0
                     2013-01-05                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-11                    0                    0
                     2017-08-12                    0                    0
                     2017-08-13                    0                    0
                     2017-08-14                    0                    0
                     2017-08-15                    0                    0

                                 is_new_year_lead(3)  is_new_year_lead(2)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0                    0
                     2013-01-02                    0                    0
                     2013-01-03                    0                    0
                     2013-01-04                    0                    0
                     2013-01-05                    0                    0
...                                              ...                  ...
9         SEAFOOD    2017-08-11                    0                    0
                     2017-08-12                    0                    0
                     2017-08-13                    0                    0
                     2017-08-14                    0                    0
                     2017-08-15                    0                    0

                                 is_new_year_lead(1)  is_new_year  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                    0            1
                     2013-01-02                    0            0
                     2013-01-03                    0            0
                     2013-01-04                    0            0
                     2013-01-05                    0            0
...                                              ...          ...
9         SEAFOOD    2017-08-11                    0            0
                     2017-08-12                    0            0
                     2017-08-13                    0            0
                     2017-08-14                    0            0
                     2017-08-15                    0            0

                                 is_new_year_lag(1)  is_new_year_lag(2)  \
store_nbr family     date
1         AUTOMOTIVE 2013-01-01                   0                   0
                     2013-01-02                   1                   0
                     2013-01-03                   0                   1

In [12]:
# First we would create our Y
y = train_df.reset_index().set_index(["date", "id"]).sales
y

date        id
2013-01-01  0           0.000000
2013-01-02  1782        2.000000
2013-01-03  3564        3.000000
2013-01-04  5346        3.000000
2013-01-05  7128        5.000000
                         ...
2017-08-11  2993759    23.830999
2017-08-12  2995541    16.859001
2017-08-13  2997323    20.000000
2017-08-14  2999105    17.000000
2017-08-15  3000887    16.000000
Name: sales, Length: 3008016, dtype: float32

In [13]:
# test_set to make and combine with our dataset
test_pd = pd.read_csv("test.csv",
                      dtype = {'store_nbr' : 'category',
                               'family' : 'category',
                               'onpromotion' : 'uint32',
                              },
                      parse_dates = ["date"])

test_pd["date"] = test_pd.date.dt.to_period('D')

test_pd = test_pd.set_index(["date", "id"])
test_pd

                   store_nbr                      family  onpromotion
date       id
2017-08-16 3000888         1                  AUTOMOTIVE            0
           3000889         1                   BABY CARE            0
           3000890         1                      BEAUTY            2
           3000891         1                   BEVERAGES           20
           3000892         1                       BOOKS            0
...                      ...                         ...          ...
2017-08-31 3029395         9                     POULTRY            1
           3029396         9              PREPARED FOODS            0
           3029397         9                     PRODUCE            1
           3029398         9  SCHOOL AND OFFICE SUPPLIES            9
           3029399         9                     SEAFOOD            0

[28512 rows x 3 columns]

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [15]:
# Evaluate our models performance
def scoring(y, y_pred):
    mae = mean_absolute_error(y, y_pred)
    mse = mean_squared_error(y, y_pred)
    r2 = r2_score(y, y_pred)
    rmse = np.sqrt(mse)
    return print(f"MAE: {mae:.5f}, RMSE: {rmse:.5f}, R^2:{r2:.5f}")

In [29]:
df_2017 = pd.DataFrame({
    'y' : y,
    'x_pred': xs_pred
})

df_2017 = df_2017.loc[pd.IndexSlice['2017', :], :]
df_2017

                            y      x_pred
date       id
2017-01-01 2596374   0.000000  209.198381
2017-01-02 2598156   5.000000  618.543230
2017-01-03 2599938   4.000000  467.521999
2017-01-04 2601720   1.000000  358.457216
2017-01-05 2603502   2.000000  378.828144
...                       ...         ...
2017-08-11 2993759  23.830999  124.230338
2017-08-12 2995541  16.859001  399.399257
2017-08-13 2997323  20.000000  281.348821
2017-08-14 2999105  17.000000  159.613340
2017-08-15 3000887  16.000000  119.786441

[404514 rows x 2 columns]

In [16]:
# Extract numerical features from our date columns
treet = train_df.copy().reset_index()
treet["date"] = treet["date"].dt.to_timestamp()          # Convert Period to Timestamp

# For train set
treet["day"] = treet.date.dt.day
treet["month"] = treet.date.dt.month
treet["year"] = treet.date.dt.year
treet["dayofweek"] = treet.date.dt.dayofweek

# freq_encode family and store_nbr
treet["family"] = treet["family"].cat.codes
treet["store_nbr"] = treet["store_nbr"].cat.codes

treet = treet.set_index("id").drop('date', axis = 1)

In [17]:
# Extract numerical features from our date columns
tree_test = test_df.copy().reset_index()
tree_test["date"] = tree_test["date"].dt.to_timestamp()          # Convert Period to Timestamp

# For test set
tree_test["day"] = tree_test.date.dt.day
tree_test["month"] = tree_test.date.dt.month
tree_test["year"] = tree_test.date.dt.year
tree_test["dayofweek"] = tree_test.date.dt.dayofweek

# freq_encode family and store_nbr
tree_test["family"] = tree_test["family"].cat.codes
tree_test["store_nbr"] = tree_test["store_nbr"].cat.codes


tree_test = tree_test.set_index("id").drop('date', axis = 1)

In [18]:
# Use frequency encoding for the remaining categorical columns
cat_col = ['city', 'type', 'state', 'cluster']

for col in cat_col:
    freq = treet[col].value_counts(normalize = True)
    treet[col + '_freq'] = treet[col].map(freq)
    tree_test[col + '_freq'] = tree_test[col].map(freq)
    treet = treet.drop(col, axis = 1)
    tree_test = tree_test.drop(col, axis = 1)

tree_test

,store_nbr,family,const,trend,onpromotion,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)",dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3000888,0,0,1.0,1689.0,0,1.0,0.0,0.0,0.0,0.0,0.0,-0.693281,-0.720667,0.999250,0.038722,-0.746972,0.664855,0.077386,-0.997001,0.635432,0.772157,1.224647e-16,-1.000000,-2.449294e-16,1.000000,46.80,47.57,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.0,16,8,2017,2,0.333333,0.333333,0.351852,0.074074
3002670,0,0,1.0,1690.0,0,0.0,1.0,0.0,0.0,0.0,0.0,-0.705584,-0.708627,0.999991,0.004304,-0.711657,0.702527,0.008607,-0.999963,0.699458,0.714673,-6.824241e-02,-0.997669,1.361666e-01,0.990686,47.07,46.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,17,8,2017,3,0.333333,0.333333,0.351852,0.074074
3004452,0,0,1.0,1691.0,0,0.0,0.0,1.0,0.0,0.0,0.0,-0.717677,-0.696376,0.999546,-0.030120,-0.674444,0.738326,-0.060213,-0.998186,0.758306,0.651899,-1.361666e-01,-0.990686,2.697968e-01,0.962917,48.59,47.07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,18,8,2017,4,0.333333,0.333333,0.351852,0.074074
3006234,0,0,1.0,1692.0,0,0.0,0.0,0.0,1.0,0.0,0.0,-0.729558,-0.683919,0.997917,-0.064508,-0.635432,0.772157,-0.128748,-0.991677,0.811539,0.584298,-2.034560e-01,-0.979084,3.984011e-01,0.917211,48.19,48.59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,19,8,2017,5,0.333333,0.333333,0.351852,0.074074
3008016,0,0,1.0,1693.0,0,0.0,0.0,0.0,0.0,1.0,0.0,-0.741222,-0.671260,0.995105,-0.098820,-0.594727,0.803928,-0.196673,-0.980469,0.858764,0.512371,-2.697968e-01,-0.962917,5.195840e-01,0.854419,47.79,48.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,20,8,2017,6,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3022271,53,32,1.0,1700.0,0,0.0,0.0,0.0,0.0,1.0,0.0,-0.816538,-0.577292,0.942761,-0.333469,-0.271958,0.962309,-0.628763,-0.777597,0.997917,-0.064508,-6.825531e-01,-0.730836,9.976688e-01,0.068242,46.82,47.23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,27,8,2017,6,0.333333,0.148148,0.351852,0.111111
3024053,53,32,1.0,1701.0,0,0.0,0.0,0.0,0.0,0.0,1.0,-0.826354,-0.563151,0.930724,-0.365723,-0.221922,0.975065,-0.680773,-0.732494,0.988678,-0.150055,-7.308360e-01,-0.682553,9.976688e-01,-0.068242,46.40,46.82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,28,8,2017,0,0.333333,0.148148,0.351852,0.111111
3025835,53,32,1.0,1702.0,0,0.0,0.0,0.0,0.0,0.0,0.0,-0.835925,-0.548843,0.917584,-0.397543,-0.171293,0.985220,-0.729558,-0.683919,0.972118,-0.234491,-7.757113e-01,-0.631088,9.790841e-01,-0.203456,46.46,46.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,29,8,2017,1,0.333333,0.148148,0.351852,0.111111
3027617,53,32,1.0,1703.0,0,1.0,0.0,0.0,0.0,0.0,0.0,-0.845249,-0.534373,0.903356,-0.428892,-0.120208,0.992749,-0.774884,-0.632103,0.948362,-0.317191,-8.169699e-01,-0.576680,9.422609e-01,-0.334880,45.96,46.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,30,8,2017,2,0.333333,0.148148,0.351852,0.111111
3029399,53,32,1.0,1704.0,0,0.0,1.0,0.0,0.0,0.0,0.0,-0.854322,-0.519744,0.888057,-0.459733,-0.068802,0.997630,-0.816538,-0.577292,0.917584,-0.397543,-8.544194e-01,-0.519584,8.878852e-01,-0.460065,47.26,45.96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0.0,31,8,2017,3,0.333333,0.148148,0.351852,0.111111

In [19]:
tree_x = treet.drop('sales', axis = 1)
tree_x

,store_nbr,family,const,trend,onpromotion,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)",dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0,0,1.0,1.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,93.14,94.88,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0.0,1,1,2013,1,0.333333,0.333333,0.351852,0.074074
1782,0,0,1.0,2.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.017213,0.999852,0.034422,0.999407,0.051620,0.998667,0.068802,0.997630,0.085965,0.996298,0.069756,0.997564,0.139173,0.990268,93.14,93.14,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,2,1,2013,2,0.333333,0.333333,0.351852,0.074074
3564,0,0,1.0,3.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.034422,0.999407,0.068802,0.997630,0.103102,0.994671,0.137279,0.990532,0.171293,0.985220,0.139173,0.990268,0.275637,0.961262,92.97,93.14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,3,1,2013,3,0.333333,0.333333,0.351852,0.074074
5346,0,0,1.0,4.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.051620,0.998667,0.103102,0.994671,0.154309,0.988023,0.205104,0.978740,0.255353,0.966848,0.207912,0.978148,0.406737,0.913545,93.12,92.97,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,4,1,2013,4,0.333333,0.333333,0.351852,0.074074
7128,0,0,1.0,5.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.068802,0.997630,0.137279,0.990532,0.205104,0.978740,0.271958,0.962309,0.337523,0.941317,0.275637,0.961262,0.529919,0.848048,93.15,93.12,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,5,1,2013,5,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993759,53,32,1.0,1684.0,0,0.0,0.0,1.0,0.0,0.0,0.0,-0.628763,-0.777597,0.977848,0.209315,-0.891981,0.452072,0.409356,-0.912375,0.255353,0.966848,0.334880,-0.942261,-0.631088,0.775711,48.81,48.54,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,11,8,2017,4,0.333333,0.148148,0.351852,0.111111
2995541,53,32,1.0,1685.0,4,0.0,0.0,0.0,1.0,0.0,0.0,-0.642055,-0.766659,0.984474,0.175531,-0.867456,0.497513,0.345612,-0.938377,0.337523,0.941317,0.269797,-0.962917,-0.519584,0.854419,48.40,48.81,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,12,8,2017,5,0.333333,0.148148,0.351852,0.111111
2997323,53,32,1.0,1686.0,0,0.0,0.0,0.0,0.0,1.0,0.0,-0.655156,-0.755493,0.989932,0.141540,-0.840618,0.541628,0.280231,-0.959933,0.417194,0.908818,0.203456,-0.979084,-0.398401,0.917211,48.00,48.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,13,8,2017,6,0.333333,0.148148,0.351852,0.111111
2999105,53,32,1.0,1687.0,0,0.0,0.0,0.0,0.0,0.0,1.0,-0.668064,-0.744104,0.994218,0.107381,-0.811539,0.584298,0.213521,-0.976938,0.493776,0.869589,0.136167,-0.990686,-0.269797,0.962917,47.59,48.00,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,14,8,2017,0,0.333333,0.148148,0.351852,0.111111
3000887,53,32,1.0,1688.0,0,0.0,0.0,0.0,0.0,0.0,0.0,-0.680773,-0.732494,0.997325,0.073095,-0.780296,0.625411,0.145799,-0.989314,0.566702,0.823923,0.068242,-0.997669,-0.136167,0.990686,47.57,47.59,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0.0,15,8,2017,1,0.333333,0.148148,0.351852,0.111111

In [20]:
tree_y = np.log1p(treet.sales)
tree_y

id
0          0.000000
1782       1.098612
3564       1.386294
5346       1.386294
7128       1.791759
             ...
2993759    3.212093
2995541    2.882508
2997323    3.044523
2999105    2.890372
3000887    2.833213
Name: sales, Length: 3008016, dtype: float32

In [21]:
tree_x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3008016 entries, 0 to 3000887
Data columns (total 67 columns):
 #   Column                   Dtype
---  ------                   -----
 0   store_nbr                int8
 1   family                   int8
 2   const                    float64
 3   trend                    float64
 4   onpromotion              uint32
 5   s(2,7)                   float64
 6   s(3,7)                   float64
 7   s(4,7)                   float64
 8   s(5,7)                   float64
 9   s(6,7)                   float64
 10  s(7,7)                   float64
 11  sin(1,freq=YE-DEC)       float64
 12  cos(1,freq=YE-DEC)       float64
 13  sin(2,freq=YE-DEC)       float64
 14  cos(2,freq=YE-DEC)       float64
 15  sin(3,freq=YE-DEC)       float64
 16  cos(3,freq=YE-DEC)       float64
 17  sin(4,freq=YE-DEC)       float64
 18  cos(4,freq=YE-DEC)       float64
 19  sin(5,freq=YE-DEC)       float64
 20  cos(5,freq=YE-DEC)       float64
 21  sin(1,freq=QE-DEC)       float64
 22  cos(1,freq=QE-DEC)       float64
 23  sin(2,freq=QE-DEC)       float64
 24  cos(2,freq=QE-DEC)       float64
 25  dcoilwtico               float64
 26  dcoilwtico_lag           float64
 27  is_national_holiday      int32
 28  is_regional_holiday      int32
 29  is_local_holiday         int32
 30  holiday_type_Additional  int32
 31  holiday_type_Bridge      int32
 32  holiday_type_Event       int32
 33  holiday_type_Holiday     int32
 34  holiday_type_Transfer    int32
 35  holiday_type_Work Day    int32
 36  holiday_transferred      int32
 37  is_holiday_lead          int32
 38  is_holiday               int32
 39  is_holiday_lag           int32
 40  is_christmas_lead(2)     int32
 41  is_christmas_lead(1)     int32
 42  is_christmas             int32
 43  is_christmas_lag(1)      int32
 44  is_christmas_lag(2)      int32
 45  is_christmas_lag(3)      int32
 46  is_new_year_lead(3)      int64
 47  is_new_year_lead(2)      int64
 48  is_new_year_lead(1)      int64
 49  is_new_year              int64
 50  is_new_year_lag(1)       int64
 51  is_new_year_lag(2)       int64
 52  is_payday_15             int64
 53  is_payday_end            int64
 54  is_payday_lead           int64
 55  is_payday                int64
 56  is_payday_lag            int64
 57  earthquake_impact        int64
 58  earthquake_decay         float64
 59  day                      int32
 60  month                    int32
 61  year                     int32
 62  dayofweek                int32
 63  city_freq                float64
 64  type_freq                category
 65  state_freq               float64
 66  cluster_freq             float64
dtypes: category(1), float64(28), int32(23), int64(12), int8(2), uint32(1)
memory usage: 1.2 GB

In [22]:
tree_x.type_freq = tree_x.type_freq.astype(float)
tree_x

,store_nbr,family,const,trend,onpromotion,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)",dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0,0,1.0,1.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,93.14,94.88,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0.0,1,1,2013,1,0.333333,0.333333,0.351852,0.074074
1782,0,0,1.0,2.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.017213,0.999852,0.034422,0.999407,0.051620,0.998667,0.068802,0.997630,0.085965,0.996298,0.069756,0.997564,0.139173,0.990268,93.14,93.14,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,2,1,2013,2,0.333333,0.333333,0.351852,0.074074
3564,0,0,1.0,3.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.034422,0.999407,0.068802,0.997630,0.103102,0.994671,0.137279,0.990532,0.171293,0.985220,0.139173,0.990268,0.275637,0.961262,92.97,93.14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,3,1,2013,3,0.333333,0.333333,0.351852,0.074074
5346,0,0,1.0,4.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.051620,0.998667,0.103102,0.994671,0.154309,0.988023,0.205104,0.978740,0.255353,0.966848,0.207912,0.978148,0.406737,0.913545,93.12,92.97,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,4,1,2013,4,0.333333,0.333333,0.351852,0.074074
7128,0,0,1.0,5.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.068802,0.997630,0.137279,0.990532,0.205104,0.978740,0.271958,0.962309,0.337523,0.941317,0.275637,0.961262,0.529919,0.848048,93.15,93.12,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,5,1,2013,5,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993759,53,32,1.0,1684.0,0,0.0,0.0,1.0,0.0,0.0,0.0,-0.628763,-0.777597,0.977848,0.209315,-0.891981,0.452072,0.409356,-0.912375,0.255353,0.966848,0.334880,-0.942261,-0.631088,0.775711,48.81,48.54,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,11,8,2017,4,0.333333,0.148148,0.351852,0.111111
2995541,53,32,1.0,1685.0,4,0.0,0.0,0.0,1.0,0.0,0.0,-0.642055,-0.766659,0.984474,0.175531,-0.867456,0.497513,0.345612,-0.938377,0.337523,0.941317,0.269797,-0.962917,-0.519584,0.854419,48.40,48.81,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,12,8,2017,5,0.333333,0.148148,0.351852,0.111111
2997323,53,32,1.0,1686.0,0,0.0,0.0,0.0,0.0,1.0,0.0,-0.655156,-0.755493,0.989932,0.141540,-0.840618,0.541628,0.280231,-0.959933,0.417194,0.908818,0.203456,-0.979084,-0.398401,0.917211,48.00,48.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,13,8,2017,6,0.333333,0.148148,0.351852,0.111111
2999105,53,32,1.0,1687.0,0,0.0,0.0,0.0,0.0,0.0,1.0,-0.668064,-0.744104,0.994218,0.107381,-0.811539,0.584298,0.213521,-0.976938,0.493776,0.869589,0.136167,-0.990686,-0.269797,0.962917,47.59,48.00,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,14,8,2017,0,0.333333,0.148148,0.351852,0.111111
3000887,53,32,1.0,1688.0,0,0.0,0.0,0.0,0.0,0.0,0.0,-0.680773,-0.732494,0.997325,0.073095,-0.780296,0.625411,0.145799,-0.989314,0.566702,0.823923,0.068242,-0.997669,-0.136167,0.990686,47.57,47.59,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0.0,15,8,2017,1,0.333333,0.148148,0.351852,0.111111

In [23]:
tree_test.type_freq = tree_test.type_freq.astype(float)
tree_test

,store_nbr,family,const,trend,onpromotion,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)",dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3000888,0,0,1.0,1689.0,0,1.0,0.0,0.0,0.0,0.0,0.0,-0.693281,-0.720667,0.999250,0.038722,-0.746972,0.664855,0.077386,-0.997001,0.635432,0.772157,1.224647e-16,-1.000000,-2.449294e-16,1.000000,46.80,47.57,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.0,16,8,2017,2,0.333333,0.333333,0.351852,0.074074
3002670,0,0,1.0,1690.0,0,0.0,1.0,0.0,0.0,0.0,0.0,-0.705584,-0.708627,0.999991,0.004304,-0.711657,0.702527,0.008607,-0.999963,0.699458,0.714673,-6.824241e-02,-0.997669,1.361666e-01,0.990686,47.07,46.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,17,8,2017,3,0.333333,0.333333,0.351852,0.074074
3004452,0,0,1.0,1691.0,0,0.0,0.0,1.0,0.0,0.0,0.0,-0.717677,-0.696376,0.999546,-0.030120,-0.674444,0.738326,-0.060213,-0.998186,0.758306,0.651899,-1.361666e-01,-0.990686,2.697968e-01,0.962917,48.59,47.07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,18,8,2017,4,0.333333,0.333333,0.351852,0.074074
3006234,0,0,1.0,1692.0,0,0.0,0.0,0.0,1.0,0.0,0.0,-0.729558,-0.683919,0.997917,-0.064508,-0.635432,0.772157,-0.128748,-0.991677,0.811539,0.584298,-2.034560e-01,-0.979084,3.984011e-01,0.917211,48.19,48.59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,19,8,2017,5,0.333333,0.333333,0.351852,0.074074
3008016,0,0,1.0,1693.0,0,0.0,0.0,0.0,0.0,1.0,0.0,-0.741222,-0.671260,0.995105,-0.098820,-0.594727,0.803928,-0.196673,-0.980469,0.858764,0.512371,-2.697968e-01,-0.962917,5.195840e-01,0.854419,47.79,48.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,20,8,2017,6,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3022271,53,32,1.0,1700.0,0,0.0,0.0,0.0,0.0,1.0,0.0,-0.816538,-0.577292,0.942761,-0.333469,-0.271958,0.962309,-0.628763,-0.777597,0.997917,-0.064508,-6.825531e-01,-0.730836,9.976688e-01,0.068242,46.82,47.23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,27,8,2017,6,0.333333,0.148148,0.351852,0.111111
3024053,53,32,1.0,1701.0,0,0.0,0.0,0.0,0.0,0.0,1.0,-0.826354,-0.563151,0.930724,-0.365723,-0.221922,0.975065,-0.680773,-0.732494,0.988678,-0.150055,-7.308360e-01,-0.682553,9.976688e-01,-0.068242,46.40,46.82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,28,8,2017,0,0.333333,0.148148,0.351852,0.111111
3025835,53,32,1.0,1702.0,0,0.0,0.0,0.0,0.0,0.0,0.0,-0.835925,-0.548843,0.917584,-0.397543,-0.171293,0.985220,-0.729558,-0.683919,0.972118,-0.234491,-7.757113e-01,-0.631088,9.790841e-01,-0.203456,46.46,46.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,29,8,2017,1,0.333333,0.148148,0.351852,0.111111
3027617,53,32,1.0,1703.0,0,1.0,0.0,0.0,0.0,0.0,0.0,-0.845249,-0.534373,0.903356,-0.428892,-0.120208,0.992749,-0.774884,-0.632103,0.948362,-0.317191,-8.169699e-01,-0.576680,9.422609e-01,-0.334880,45.96,46.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,30,8,2017,2,0.333333,0.148148,0.351852,0.111111
3029399,53,32,1.0,1704.0,0,0.0,1.0,0.0,0.0,0.0,0.0,-0.854322,-0.519744,0.888057,-0.459733,-0.068802,0.997630,-0.816538,-0.577292,0.917584,-0.397543,-8.544194e-01,-0.519584,8.878852e-01,-0.460065,47.26,45.96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0.0,31,8,2017,3,0.333333,0.148148,0.351852,0.111111

In [24]:
# Prepare the data for both models
lin_df = pd.read_csv("det_train.csv",
                     parse_dates = ['date']
                    )
lin_df['date'] = lin_df.date.dt.to_period('D')
lin_df = lin_df.set_index('date').drop('is_new_year', axis = 1)
lin_df

,const,trend,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)"
date,,,,,,,,,,,,,,,,,,,,,,
2013-01-01,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
2013-01-02,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.017213,0.999852,0.034422,0.999407,0.051620,0.998667,0.068802,0.997630,0.085965,0.996298,0.069756,0.997564,0.139173,0.990268
2013-01-03,1.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.034422,0.999407,0.068802,0.997630,0.103102,0.994671,0.137279,0.990532,0.171293,0.985220,0.139173,0.990268,0.275637,0.961262
2013-01-04,1.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.051620,0.998667,0.103102,0.994671,0.154309,0.988023,0.205104,0.978740,0.255353,0.966848,0.207912,0.978148,0.406737,0.913545
2013-01-05,1.0,5.0,0.0,0.0,0.0,1.0,0.0,0.0,0.068802,0.997630,0.137279,0.990532,0.205104,0.978740,0.271958,0.962309,0.337523,0.941317,0.275637,0.961262,0.529919,0.848048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-11,1.0,1684.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.628763,-0.777597,0.977848,0.209315,-0.891981,0.452072,0.409356,-0.912375,0.255353,0.966848,0.334880,-0.942261,-0.631088,0.775711
2017-08-12,1.0,1685.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.642055,-0.766659,0.984474,0.175531,-0.867456,0.497513,0.345612,-0.938377,0.337523,0.941317,0.269797,-0.962917,-0.519584,0.854419
2017-08-13,1.0,1686.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.655156,-0.755493,0.989932,0.141540,-0.840618,0.541628,0.280231,-0.959933,0.417194,0.908818,0.203456,-0.979084,-0.398401,0.917211
2017-08-14,1.0,1687.0,0.0,0.0,0.0,0.0,0.0,1.0,-0.668064,-0.744104,0.994218,0.107381,-0.811539,0.584298,0.213521,-0.976938,0.493776,0.869589,0.136167,-0.990686,-0.269797,0.962917
2017-08-15,1.0,1688.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.680773,-0.732494,0.997325,0.073095,-0.780296,0.625411,0.145799,-0.989314,0.566702,0.823923,0.068242,-0.997669,-0.136167,0.990686

In [25]:
lin_test = pd.read_csv('det_test.csv',
                       parse_dates = ['date']
                      )
lin_test['date'] = lin_test.date.dt.to_period('D')
lin_test = lin_test.set_index('date').drop('is_new_year', axis = 1)
lin_test

,const,trend,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)"
date,,,,,,,,,,,,,,,,,,,,,,
2017-08-16,1,1689,1,0,0,0,0,0,-0.693281,-0.720667,0.999250,0.038722,-0.746972,0.664855,0.077386,-0.997001,0.635432,0.772157,1.220000e-16,-1.000000,-2.450000e-16,1.000000
2017-08-17,1,1690,0,1,0,0,0,0,-0.705584,-0.708627,0.999991,0.004304,-0.711657,0.702527,0.008607,-0.999963,0.699458,0.714673,-6.824241e-02,-0.997669,1.361666e-01,0.990686
2017-08-18,1,1691,0,0,1,0,0,0,-0.717677,-0.696376,0.999546,-0.030120,-0.674444,0.738326,-0.060213,-0.998186,0.758306,0.651899,-1.361666e-01,-0.990686,2.697968e-01,0.962917
2017-08-19,1,1692,0,0,0,1,0,0,-0.729558,-0.683919,0.997917,-0.064508,-0.635432,0.772157,-0.128748,-0.991677,0.811539,0.584298,-2.034560e-01,-0.979084,3.984011e-01,0.917211
2017-08-20,1,1693,0,0,0,0,1,0,-0.741222,-0.671260,0.995105,-0.098820,-0.594727,0.803928,-0.196673,-0.980469,0.858764,0.512371,-2.697968e-01,-0.962917,5.195840e-01,0.854419
2017-08-21,1,1694,0,0,0,0,0,1,-0.752667,-0.658402,0.991114,-0.133015,-0.552435,0.833556,-0.263665,-0.964614,0.899631,0.436651,-3.348796e-01,-0.942261,6.310879e-01,0.775711
2017-08-22,1,1695,0,0,0,0,0,0,-0.763889,-0.645348,0.985948,-0.167052,-0.508671,0.860961,-0.329408,-0.944188,0.933837,0.357698,-3.984011e-01,-0.917211,7.308360e-01,0.682553
2017-08-23,1,1696,1,0,0,0,0,0,-0.774884,-0.632103,0.979614,-0.200891,-0.463550,0.886071,-0.393590,-0.919286,0.961130,0.276097,-4.600650e-01,-0.887885,8.169699e-01,0.576680
2017-08-24,1,1697,0,1,0,0,0,0,-0.785650,-0.618671,0.972118,-0.234491,-0.417194,0.908818,-0.455907,-0.890028,0.981306,0.192452,-5.195840e-01,-0.854419,8.878852e-01,0.460065
2017-08-25,1,1698,0,0,1,0,0,0,-0.796183,-0.605056,0.963471,-0.267814,-0.369725,0.929141,-0.516062,-0.856551,0.994218,0.107381,-5.766803e-01,-0.816970,9.422609e-01,0.334880
2017-08-26,1,1699,0,0,0,1,0,0,-0.806480,-0.591261,0.953681,-0.300820,-0.321270,0.946988,-0.573772,-0.819015,0.999769,0.021516,-6.310879e-01,-0.775711,9.790841e-01,0.203456
2017-08-27,1,1700,0,0,0,0,1,0,-0.816538,-0.577292,0.942761,-0.333469,-0.271958,0.962309,-0.628763,-0.777597,0.997917,-0.064508,-6.825531e-01,-0.730836,9.976688e-01,0.068242
2017-08-28,1,1701,0,0,0,0,0,1,-0.826354,-0.563151,0.930724,-0.365723,-0.221922,0.975065,-0.680773,-0.732494,0.988678,-0.150055,-7.308360e-01,-0.682553,9.976688e-01,-0.068242
2017-08-29,1,1702,0,0,0,0,0,0,-0.835925,-0.548843,0.917584,-0.397543,-0.171293,0.985220,-0.729558,-0.683919,0.972118,-0.234491,-7.757113e-01,-0.631088,9.790841e-01,-0.203456
2017-08-30,1,1703,1,0,0,0,0,0,-0.845249,-0.534373,0.903356,-0.428892,-0.120208,0.992749,-0.774884,-0.632103,0.948362,-0.317191,-8.169699e-01,-0.576680,9.422609e-01,-0.334880
2017-08-31,1,1704,0,1,0,0,0,0,-0.854322,-0.519744,0.888057,-0.459733,-0.068802,0.997630,-0.816538,-0.577292,0.917584,-0.397543,-8.544194e-01,-0.519584,8.878852e-01,-0.460065

In [26]:
lin_y = train_df.sales.to_frame()
lin_y

                                     sales
store_nbr family     date
1         AUTOMOTIVE 2013-01-01   0.000000
                     2013-01-02   2.000000
                     2013-01-03   3.000000
                     2013-01-04   3.000000
                     2013-01-05   5.000000
...                                    ...
9         SEAFOOD    2017-08-11  23.830999
                     2017-08-12  16.859001
                     2017-08-13  20.000000
                     2017-08-14  17.000000
                     2017-08-15  16.000000

[3008016 rows x 1 columns]

In [27]:
lin_y = lin_y.unstack(['store_nbr', 'family'])
lin_y

                sales                                                \
store_nbr           1
family     AUTOMOTIVE BABY CARE BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01        0.0       0.0    0.0       0.0   0.0     0.000000
2013-01-02        2.0       0.0    2.0    1091.0   0.0   470.652008
2013-01-03        3.0       0.0    0.0     919.0   0.0   310.654999
2013-01-04        3.0       0.0    3.0     953.0   0.0   198.365997
2013-01-05        5.0       0.0    3.0    1160.0   0.0   301.057007
...               ...       ...    ...       ...   ...          ...
2017-08-11        1.0       0.0    1.0    1006.0   0.0   145.606995
2017-08-12        6.0       0.0    3.0    1659.0   0.0   243.220001
2017-08-13        1.0       0.0    1.0     803.0   0.0   136.679001
2017-08-14        1.0       0.0    6.0    2201.0   0.0   346.037994
2017-08-15        4.0       0.0    4.0    1942.0   0.0   329.541016

                                                                        \
store_nbr
family     CELEBRATION CLEANING  DAIRY        DELI   EGGS FROZEN FOODS
date
2013-01-01         0.0      0.0    0.0    0.000000    0.0     0.000000
2013-01-02         0.0   1060.0  579.0  164.069000  246.0   131.000000
2013-01-03         0.0    836.0  453.0  151.582001  203.0    87.043999
2013-01-04         0.0    827.0  460.0  131.410995  171.0    65.000000
2013-01-05         0.0    811.0  464.0  118.612999  177.0    70.000000
...                ...      ...    ...         ...    ...          ...
2017-08-11         4.0    341.0  343.0   64.302002   86.0    61.000000
2017-08-12         3.0    351.0  526.0   99.487999  113.0   107.793999
2017-08-13         1.0    169.0  266.0   47.770000   60.0    50.000000
2017-08-14         4.0    571.0  699.0  154.578003  170.0   110.000000
2017-08-15        21.0    703.0  602.0  116.402000  131.0    89.000000

                                                             \
store_nbr
family     GROCERY I GROCERY II HARDWARE HOME AND KITCHEN I
date
2013-01-01       0.0        0.0      0.0                0.0
2013-01-02    2652.0       31.0      3.0                0.0
2013-01-03    2121.0       12.0      1.0                0.0
2013-01-04    2056.0       15.0      7.0                0.0
2013-01-05    2216.0       30.0      1.0                0.0
...              ...        ...      ...                ...
2017-08-11    1270.0        9.0      1.0               27.0
2017-08-12    1630.0       19.0      0.0               17.0
2017-08-13     952.0        6.0      1.0               13.0
2017-08-14    2407.0       20.0      0.0               50.0
2017-08-15    2508.0       13.0      3.0               30.0

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01                 0.0             0.0       0.0        0.0
2013-01-02                 0.0             0.0       0.0        0.0
2013-01-03                 0.0             2.0       0.0        0.0
2013-01-04                 0.0             0.0       0.0        0.0
2013-01-05                 0.0             0.0       0.0        0.0
...                        ...             ...       ...        ...
2017-08-11                14.0             0.0      74.0        3.0
2017-08-12                31.0             0.0     116.0        9.0
2017-08-13                 8.0             0.0      61.0        7.0
2017-08-14                31.0             0.0     161.0       17.0
2017-08-15                33.0             0.0     156.0        9.0

                                                                            \
store_nbr
family     LAWN AND GARDEN LINGERIE LIQUOR,WINE,BEER MAGAZINES       MEATS
date
2013-01-01             0.0      0.0              0.0       0.0    0.000000
2013-01-02            10.0     13.0             67.0       0.0  369.101013
2013-01-03             0.0     15.0             66.0       0.0  272.319000
2013-01-04             7.0     24.0            102.0       0.0  454.171997
2013-01-05            10.0     20.0            159.0       0.0  328.940002
...                    ...      ...              ...       ...         ...
2017-08-11            15.0      1.0             67.0       4.0  385.994019
2017-08-12            10.0      8.0             90.0       6.0  211.755997
2017-08-13             8.0      3.0             35.0       4.0   88.181999
2017-08-14            27.0     21.0            100.0       8.0  192.763000
2017-08-15            17.0      4.0             94.0       3.0  274.175995

                                                                           \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS     POULTRY
date
2013-01-01           0.0          0.0                     0.0    0.000000
2013-01-02         194.0          0.0                     0.0  247.296997
2013-01-03         153.0          0.0                     0.0  187.278000
2013-01-04          88.0          0.0                     0.0  258.023010
2013-01-05         141.0          0.0                     0.0  212.333008
...                  ...          ...                     ...         ...
2017-08-11          53.0          5.0                     3.0  259.118011
2017-08-12         227.0          3.0                     6.0  217.664001
2017-08-13          45.0          2.0                     0.0  115.758003
2017-08-14         159.0          3.0                     6.0  270.046997
2017-08-15         173.0          3.0                    21.0  234.891998

                                                                              \
store_nbr
family     PREPARED FOODS      PRODUCE SCHOOL AND OFFICE SUPPLIES    SEAFOOD
date
2013-01-01       0.000000     0.000000                        0.0   0.000000
2013-01-02      47.000000     0.000000                        0.0  38.028999
2013-01-03      63.000000     0.000000                        0.0  17.366001
2013-01-04      67.000000     0.000000                        0.0  29.907001
2013-01-05      66.000000     0.000000                        0.0  24.841999
...                   ...          ...                        ...        ...
2017-08-11      24.963001  1115.333984                        0.0  19.424000
2017-08-12      48.057999  1762.493042                        0.0  20.150000
2017-08-13      20.346001   986.669006                        0.0  11.378000
2017-08-14      72.003998  2611.754883                        0.0  14.129000
2017-08-15      42.822998  2240.229980                        0.0  22.487000

                                                                     \
store_nbr          10
family     AUTOMOTIVE BABY CARE BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01        0.0       0.0    0.0       0.0   0.0          0.0
2013-01-02        3.0       0.0    6.0     396.0   0.0        151.0
2013-01-03        2.0       0.0    3.0     399.0   0.0        129.0
2013-01-04        2.0       0.0    4.0     460.0   0.0        105.0
2013-01-05        0.0       0.0    3.0     624.0   0.0        112.0
...               ...       ...    ...       ...   ...          ...
2017-08-11        2.0       0.0    2.0    1459.0   0.0         76.0
2017-08-12        2.0       0.0    3.0    1332.0   0.0        113.0
2017-08-13        0.0       0.0    5.0    1526.0   0.0        119.0
2017-08-14        1.0       0.0    6.0    1129.0   0.0         82.0
2017-08-15        4.0       0.0    4.0    1608.0   0.0        112.0

                                                                             \
store_nbr
family     CELEBRATION CLEANING  DAIRY   DELI   EGGS FROZEN FOODS GROCERY I
date
2013-01-01         0.0      0.0    0.0    0.0    0.0     0.000000       0.0
2013-01-02         0.0   1110.0  101.0  276.0   57.0    41.164001    2579.0
2013-01-03         0.0    970.0  113.0  269.0   38.0    14.470000    1984.0
2013-01-04         0.0    669.0   66.0   92.0   22.0    10.691000    1565.0
2013-01-05         0.0   1093.0   88.0  194.0   43.0    13.891000    2544.0
...                ...      ...    ...    ...    ...          ...       ...
2017-08-11         5.0    532.0  251.0  269.0   23.0    36.000000    2349.0
2017-08-12         5.0    676.0  255.0  276.0   17.0    28.000000    2629.0
2017-08-13         6.0    670.0  270.0  251.0   62.0    42.000000    2834.0
2017-08-14         3.0    710.0  253.0  313.0  122.0    38.000000    2625.0
2017-08-15         2.0    731.0  328.0  175.0   40.0    49.000000    2679.0

                                                                       \
store_nbr
family     GROCERY II HARDWARE HOME AND KITCHEN I HOME AND KITCHEN II
date
2013-01-01        0.0      0.0                0.0                 0.0
2013-01-02        8.0      2.0                0.0                 0.0
2013-01-03        1.0      0.0                0.0                 0.0
2013-01-04        2.0      0.0                0.0                 0.0
2013-01-05        5.0      3.0                0.0                 0.0
...               ...      ...                ...                 ...
2017-08-11        2.0      0.0                9.0                 8.0
2017-08-12        4.0      0.0                5.0                15.0
2017-08-13       13.0      0.0               11.0                13.0
2017-08-14        0.0      1.0               11.0                 9.0
2017-08-15        5.0      1.0                5.0                12.0

                                                                          \
store_nbr
family     HOME APPLIANCES HOME CARE LADIESWEAR LAWN AND GARDEN LINGERIE
date
2013-01-01             0.0       0.0        0.0             0.0      0.0
2013-01-02             0.0       0.0        0.0             0.0      4.0
2013-01-03             0.0       0.0        0.0             0.0      5.0
2013-01-04             0.0       0.0        0.0             0.0      0.0
2013-01-05             0.0       0.0        0.0             0.0      3.0
...                    ...       ...        ...             ...      ...
2017-08-11             1.0     128.0        2.0             0.0      4.0
2017-08-12             0.0     140.0        8.0             0.0      0.0
2017-08-13             0.0     163.0        2.0             0.0      1.0
2017-08-14             0.0     156.0        2.0             0.0      2.0
2017-08-15             0.0     193.0       13.0             0.0      1.0

                                                                              \
store_nbr
family     LIQUOR,WINE,BEER MAGAZINES       MEATS PERSONAL CARE PET SUPPLIES
date
2013-01-01              0.0       0.0    0.000000           0.0          0.0
2013-01-02              6.0       0.0  291.140015         223.0          0.0
2013-01-03              2.0       0.0  279.742981         169.0          0.0
2013-01-04              8.0       0.0  139.166000         119.0          0.0
2013-01-05             26.0       0.0  247.298004         270.0          0.0
...                     ...       ...         ...           ...          ...
2017-08-11             14.0       1.0  155.992004         193.0          2.0
2017-08-12             49.0       0.0  165.199997         151.0          0.0
2017-08-13              8.0       1.0  156.281998         150.0          1.0
2017-08-14             11.0       0.0  217.770996         155.0          0.0
2017-08-15             14.0       1.0  235.604004         176.0          2.0

                                                                           \
store_nbr
family     PLAYERS AND ELECTRONICS     POULTRY PREPARED FOODS     PRODUCE
date
2013-01-01                     0.0    0.000000            0.0    0.000000
2013-01-02                     0.0  146.783997           26.0    0.000000
2013-01-03                     0.0  148.317001           10.0    0.000000
2013-01-04                     0.0  111.158997            4.0    0.000000
2013-01-05                     0.0  135.596008            3.0    0.000000
...                            ...         ...            ...         ...
2017-08-11                     3.0  169.417999           10.0  224.768997
2017-08-12                     5.0  146.996002           37.0  251.612000
2017-08-13                     3.0  201.742004           13.0  248.518005
2017-08-14                     3.0  133.710007           27.0  220.259995
2017-08-15                     2.0  102.077003           26.0  256.911011

                                                                           \
store_nbr                                             11
family     SCHOOL AND OFFICE SUPPLIES SEAFOOD AUTOMOTIVE BABY CARE BEAUTY
date
2013-01-01                        0.0     0.0        0.0       0.0    0.0
2013-01-02                        0.0     3.0       12.0       0.0    7.0
2013-01-03                        0.0    13.0        8.0       0.0    3.0
2013-01-04                        0.0     2.0        5.0       0.0    1.0
2013-01-05                        0.0     2.0        7.0       0.0   10.0
...                               ...     ...        ...       ...    ...
2017-08-11                        0.0     1.0       10.0       0.0    4.0
2017-08-12                        9.0     0.0       11.0       0.0    2.0
2017-08-13                        3.0     0.0        6.0       0.0    2.0
2017-08-14                        5.0     1.0        2.0       1.0    6.0
2017-08-15                       18.0    11.0        6.0       0.0    7.0

                                                                     \
store_nbr
family     BEVERAGES BOOKS BREAD/BAKERY CELEBRATION CLEANING  DAIRY
date
2013-01-01       0.0   0.0          0.0         0.0      0.0    0.0
2013-01-02    3443.0   0.0        763.0         0.0   3260.0  296.0
2013-01-03    1911.0   0.0        658.0         0.0   2282.0  173.0
2013-01-04    2585.0   0.0        580.0         0.0   2067.0  192.0
2013-01-05    2352.0   0.0        646.0         0.0   2890.0  260.0
...              ...   ...          ...         ...      ...    ...
2017-08-11    5182.0   0.0        634.0        35.0   1572.0  608.0
2017-08-12    4323.0   0.0        582.0        20.0   1453.0  527.0
2017-08-13    4741.0   0.0        582.0        16.0   1649.0  569.0
2017-08-14    4544.0   0.0        583.0        11.0   1808.0  603.0
2017-08-15    4128.0   0.0       2080.0         8.0   1892.0  611.0

                                                                             \
store_nbr
family            DELI   EGGS FROZEN FOODS    GROCERY I GROCERY II HARDWARE
date
2013-01-01    0.000000    0.0     0.000000     0.000000        0.0      0.0
2013-01-02  527.294983  140.0    57.771000  7736.000000       15.0      3.0
2013-01-03  322.415009   74.0    40.714001  5172.000000        5.0      1.0
2013-01-04  316.786011   39.0    53.899002  4678.000000       11.0      1.0
2013-01-05  395.424988   67.0    42.841000  6107.000000       17.0      0.0
...                ...    ...          ...          ...        ...      ...
2017-08-11  486.824005  163.0   116.834999  6551.155762       25.0      0.0
2017-08-12  447.316010  170.0   138.000000  6205.757812       27.0      1.0
2017-08-13  501.876007  338.0   129.416992  6471.546875       29.0      0.0
2017-08-14  489.079987  275.0    48.000000  7380.539062       14.0      0.0
2017-08-15  489.812012  438.0    65.000000  7209.727051       14.0      1.0

                                                                             \
store_nbr
family     HOME AND KITCHEN I HOME AND KITCHEN II HOME APPLIANCES HOME CARE
date
2013-01-01                0.0                 0.0             0.0       0.0
2013-01-02                0.0                 0.0             0.0       0.0
2013-01-03                0.0                 0.0             0.0       0.0
2013-01-04                0.0                 0.0             0.0       0.0
2013-01-05                0.0                 0.0             0.0       0.0
...                       ...                 ...             ...       ...
2017-08-11               47.0                10.0             0.0     428.0
2017-08-12               37.0                13.0             0.0     402.0
2017-08-13               35.0                12.0             0.0     444.0
2017-08-14               13.0                11.0             0.0     532.0
2017-08-15               23.0                14.0             0.0     466.0

                                                                           \
store_nbr
family     LADIESWEAR LAWN AND GARDEN LINGERIE LIQUOR,WINE,BEER MAGAZINES
date
2013-01-01        0.0             0.0      0.0              0.0       0.0
2013-01-02        0.0             0.0     20.0             29.0       0.0
2013-01-03        0.0             0.0     17.0             19.0       0.0
2013-01-04        0.0             0.0      7.0             32.0       0.0
2013-01-05        0.0             2.0      9.0             92.0       0.0
...               ...             ...      ...              ...       ...
2017-08-11        9.0             1.0      6.0             60.0       1.0
2017-08-12        7.0             6.0     10.0             91.0       2.0
2017-08-13        4.0             3.0      7.0             18.0       1.0
2017-08-14        3.0             4.0      6.0             27.0       3.0
2017-08-15       16.0             5.0     11.0             12.0       4.0

                                                                           \
store_nbr
family           MEATS PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS
date
2013-01-01    0.000000           0.0          0.0                     0.0
2013-01-02  832.541016         604.0          0.0                     0.0
2013-01-03  677.962036         441.0          0.0                     0.0
2013-01-04  711.788025         373.0          0.0                     0.0
2013-01-05  819.054993         515.0          0.0                     0.0
...                ...           ...          ...                     ...
2017-08-11  660.140015         320.0          1.0                    14.0
2017-08-12  526.533997         348.0          3.0                    31.0
2017-08-13  652.184998         426.0          2.0                    20.0
2017-08-14  474.139008         373.0          5.0                     7.0
2017-08-15  829.919006         401.0          0.0                    20.0

                                                                               \
store_nbr
family         POULTRY PREPARED FOODS      PRODUCE SCHOOL AND OFFICE SUPPLIES
date
2013-01-01    0.000000       0.000000     0.000000                        0.0
2013-01-02  548.031006      31.000000     0.000000                        0.0
2013-01-03  526.114014      13.000000     0.000000                        0.0
2013-01-04  494.525024      22.000000     0.000000                        0.0
2013-01-05  493.727997      35.000000     0.000000                        0.0
...                ...            ...          ...                        ...
2017-08-11  560.169983     101.866997  1449.668945                       32.0
2017-08-12  368.710999      88.723999  1280.458008                       26.0
2017-08-13  489.114990      78.925003  1290.197021                       13.0
2017-08-14  244.968994     130.225006  1239.467041                       26.0
2017-08-15  526.458984     111.556000  2309.767090                       25.0

                                                                             \
store_nbr                  12
family     SEAFOOD AUTOMOTIVE BABY CARE BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01     0.0        0.0       0.0    0.0       0.0   0.0          0.0
2013-01-02     5.0        4.0       0.0    1.0     682.0   0.0        337.0
2013-01-03    12.0        4.0       0.0    0.0     632.0   0.0        206.0
2013-01-04     2.0        5.0       0.0    0.0     445.0   0.0        156.0
2013-01-05     3.0        7.0       0.0    1.0     801.0   0.0        248.0
...            ...        ...       ...    ...       ...   ...          ...

In [28]:
# Rmove all columns fed to Linear regression from XGboost dataset
lincol = lin_df.columns.to_list()
lincol

['const',
 'trend',
 's(2,7)',
 's(3,7)',
 's(4,7)',
 's(5,7)',
 's(6,7)',
 's(7,7)',
 'sin(1,freq=YE-DEC)',
 'cos(1,freq=YE-DEC)',
 'sin(2,freq=YE-DEC)',
 'cos(2,freq=YE-DEC)',
 'sin(3,freq=YE-DEC)',
 'cos(3,freq=YE-DEC)',
 'sin(4,freq=YE-DEC)',
 'cos(4,freq=YE-DEC)',
 'sin(5,freq=YE-DEC)',
 'cos(5,freq=YE-DEC)',
 'sin(1,freq=QE-DEC)',
 'cos(1,freq=QE-DEC)',
 'sin(2,freq=QE-DEC)',
 'cos(2,freq=QE-DEC)']

In [29]:
xg_df = tree_x.drop(lincol, axis = 1)
xg_df

,store_nbr,family,onpromotion,dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,93.14,94.88,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0.0,1,1,2013,1,0.333333,0.333333,0.351852,0.074074
1782,0,0,0,93.14,93.14,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,2,1,2013,2,0.333333,0.333333,0.351852,0.074074
3564,0,0,0,92.97,93.14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,3,1,2013,3,0.333333,0.333333,0.351852,0.074074
5346,0,0,0,93.12,92.97,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,4,1,2013,4,0.333333,0.333333,0.351852,0.074074
7128,0,0,0,93.15,93.12,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,5,1,2013,5,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993759,53,32,0,48.81,48.54,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,11,8,2017,4,0.333333,0.148148,0.351852,0.111111
2995541,53,32,4,48.40,48.81,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,12,8,2017,5,0.333333,0.148148,0.351852,0.111111
2997323,53,32,0,48.00,48.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,13,8,2017,6,0.333333,0.148148,0.351852,0.111111
2999105,53,32,0,47.59,48.00,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,14,8,2017,0,0.333333,0.148148,0.351852,0.111111
3000887,53,32,0,47.57,47.59,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0.0,15,8,2017,1,0.333333,0.148148,0.351852,0.111111

In [30]:
tree_y

id
0          0.000000
1782       1.098612
3564       1.386294
5346       1.386294
7128       1.791759
             ...
2993759    3.212093
2995541    2.882508
2997323    3.044523
2999105    2.890372
3000887    2.833213
Name: sales, Length: 3008016, dtype: float32

In [31]:
xg_test = tree_test.drop(lincol, axis = 1)
xg_test

,store_nbr,family,onpromotion,dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3000888,0,0,0,46.80,47.57,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.0,16,8,2017,2,0.333333,0.333333,0.351852,0.074074
3002670,0,0,0,47.07,46.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,17,8,2017,3,0.333333,0.333333,0.351852,0.074074
3004452,0,0,0,48.59,47.07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,18,8,2017,4,0.333333,0.333333,0.351852,0.074074
3006234,0,0,0,48.19,48.59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,19,8,2017,5,0.333333,0.333333,0.351852,0.074074
3008016,0,0,0,47.79,48.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,20,8,2017,6,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3022271,53,32,0,46.82,47.23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,27,8,2017,6,0.333333,0.148148,0.351852,0.111111
3024053,53,32,0,46.40,46.82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,28,8,2017,0,0.333333,0.148148,0.351852,0.111111
3025835,53,32,0,46.46,46.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,29,8,2017,1,0.333333,0.148148,0.351852,0.111111
3027617,53,32,0,45.96,46.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,30,8,2017,2,0.333333,0.148148,0.351852,0.111111
3029399,53,32,0,47.26,45.96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0.0,31,8,2017,3,0.333333,0.148148,0.351852,0.111111

In [32]:
# Function to minus lin_y from lin_y_pred
def linear_model(lin_y, lin_y_pred, index, col, df):
    """
    This model helps create a residual even when data fed to the linear model and data fed to the tree model have different indexes.
    lin_y is the training target for the linear model
    lin_y_pred is the prediction of the linear model
    index is the index that would be used to create dataframe for the linear model's prediction
    col is the columns for the dataframe of the linear model's prediction
    df is the dataframe that would be used to reorder the dataframe of the residual of the linear model's predition 
    and the true y values so that there is no disparity in values when feeding with the xgboost model. 
    """
    lin_pred_df = pd.DataFrame(lin_y_pred,
                               index = index.index,
                               columns = col.columns)
    residuals = lin_y - lin_pred_df
    resid_long = residuals.stack(['store_nbr', 'family'])
    resid_long = resid_long.reorder_levels(['store_nbr', 'family', 'date']).sort_index()
    resid_long = resid_long.loc[df.index]
    # Change resid_long to have the same index as our tree model
    x_tr = df[['id']].merge(resid_long, left_index = True, right_index = True, how = 'outer')
    x_tr = x_tr.reset_index().set_index('id')
    return x_tr

## MODELLING

Like has been said above, a hybrid model will be created using LinearRegression and Xgboost Regressor

In [33]:
# Instantiate linear model
lin_model = LinearRegression(fit_intercept = False)
lin_model

LinearRegression(fit_intercept=False)

In [34]:
lin_model.fit(lin_df, lin_y)

LinearRegression(fit_intercept=False)

In [35]:
lin_y_pred = lin_model.predict(lin_df)
lin_y_pred

array([[ 2.30140421e+00,  0.00000000e+00,  1.74857998e+00, ...,
         4.12963723e+02, -8.94686899e+00,  1.25731839e+01],
       [ 1.97210686e+00,  0.00000000e+00,  1.75080234e+00, ...,
        -1.20311558e+02, -9.97716624e+00,  1.16483677e+01],
       [ 1.51468431e+00,  0.00000000e+00,  1.67036411e+00, ...,
        -1.39028699e+02, -1.08880426e+01,  1.50304287e+01],
       ...,
       [ 2.92155842e+00,  0.00000000e+00,  2.34916872e+00, ...,
         2.25080042e+03,  3.70511618e+01,  2.40213708e+01],
       [ 4.78476657e+00,  0.00000000e+00,  3.73203289e+00, ...,
         1.80784948e+03,  3.33277347e+01,  1.32461035e+01],
       [ 5.33200072e+00,  0.00000000e+00,  3.66311509e+00, ...,
         2.22640815e+03,  3.43943661e+01,  1.27031959e+01]])

In [36]:
lin_pred_df = pd.DataFrame(lin_y_pred,
                               index = lin_y.index,
                               columns = lin_y.columns)
lin_pred_df

                sales                                                          \
store_nbr           1
family     AUTOMOTIVE BABY CARE    BEAUTY    BEVERAGES     BOOKS BREAD/BAKERY
date
2013-01-01   2.301404       0.0  1.748580   920.430339 -0.011133   258.306580
2013-01-02   1.972107       0.0  1.750802  1116.828061  0.009581   323.890938
2013-01-03   1.514684       0.0  1.670364   853.141031 -0.053724   268.913709
2013-01-04   2.258371       0.0  1.473094  1014.524736 -0.021453   277.336012
2013-01-05   2.186655       0.0  1.827303  1116.894107 -0.030535   267.734194
...               ...       ...       ...          ...       ...          ...
2017-08-11   5.369707       0.0  3.457267  2288.572536  0.282266   404.764055
2017-08-12   5.257718       0.0  3.833044  2383.865624  0.272186   394.102063
2017-08-13   2.921558       0.0  2.349169  1345.752389  0.204126   189.600211
2017-08-14   4.784767       0.0  3.732033  2269.166257  0.273131   419.781412
2017-08-15   5.332001       0.0  3.663115  2229.438425  0.284270   394.688550

                                                                        \
store_nbr
family     CELEBRATION    CLEANING       DAIRY        DELI        EGGS
date
2013-01-01   -0.891600  673.741023  477.809260  108.767776  138.411833
2013-01-02    0.271600  818.455719  605.566971  119.027755  167.946040
2013-01-03    0.582094  663.297000  438.260156   97.486532  124.575495
2013-01-04    2.589477  708.424952  496.278548  130.138392  155.644735
2013-01-05   -2.121595  591.611479  530.850057  113.892779  168.708230
...                ...         ...         ...         ...         ...
2017-08-11   20.237534  701.858027  776.782630  153.744374  137.770407
2017-08-12   15.163821  582.402116  811.813640  137.386901  150.135717
2017-08-13    8.735227  224.616476  423.750259   62.277591   61.881377
2017-08-14   19.695158  661.554870  781.100322  143.293824  136.184040
2017-08-15   15.413126  677.754867  762.016841  134.027789  122.694178

                                                                              \
store_nbr
family     FROZEN FOODS    GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01   281.172005  1965.614747  33.590141  1.451183           3.591806
2013-01-02   267.305829  2305.991325  35.935794  1.506870           5.880218
2013-01-03   230.949069  1757.980680  30.804804  1.422131           9.993582
2013-01-04   252.895319  1934.105176  28.647664  1.383192           9.346404
2013-01-05   225.618472  1846.979098  26.631060  1.589218           4.196146
...                 ...          ...        ...       ...                ...
2017-08-11   153.003099  2575.458989  19.939987  1.788454          32.534690
2017-08-12   132.606043  2486.389672  18.247817  2.001582          27.098217
2017-08-13    37.236306  1183.909270   5.249801  0.830145          16.512989
2017-08-14    93.740264  2536.515389  17.709594  1.614419          24.157766
2017-08-15   113.359328  2562.119806  22.158747  1.883694          26.267598

                                                                       \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES   HOME CARE LADIESWEAR
date
2013-01-01           -0.869734        0.145702   11.380805   3.940670
2013-01-02           -1.061320        0.211251   22.910926   4.063523
2013-01-03           -1.973632        0.238931    1.211329   2.639040
2013-01-04           -2.247771        0.167402    5.184309   2.033174
2013-01-05           -1.865093        0.212384   16.440845   3.552439
...                        ...             ...         ...        ...
2017-08-11           24.999229        0.221152  192.443761  14.649140
2017-08-12           25.360521        0.251706  202.823644  16.082361
2017-08-13           17.496344        0.087554  140.359506  10.125541
2017-08-14           27.149049        0.301242  204.773311  16.932747
2017-08-15           27.872195        0.253301  202.437319  16.452077

                                                                              \
store_nbr
family     LAWN AND GARDEN   LINGERIE LIQUOR,WINE,BEER MAGAZINES       MEATS
date
2013-01-01        3.154128   9.634562       114.964915 -1.781642  267.564424
2013-01-02        7.940227  11.099294       129.673147 -1.280471  299.333580
2013-01-03        1.861126  10.257319       125.661312 -1.666641  263.174276
2013-01-04        5.280108   9.681754       177.483480 -1.169861  621.625711
2013-01-05        2.944508   8.580338       167.017252 -0.562219  262.800212
...                    ...        ...              ...       ...         ...
2017-08-11       15.837408   4.389572       163.326979  7.454830  609.215312
2017-08-12       13.421153   3.284724       154.477243  8.011845  249.430554
2017-08-13       10.183512  -0.779686        10.697960  5.360830   93.482007
2017-08-14       12.734906   3.657167        73.124968  6.796629  260.161209
2017-08-15       13.498998   4.074397        87.882901  6.750534  255.465482

                                                                           \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS     POULTRY
date
2013-01-01    116.159629     0.704995                0.659443  231.804265
2013-01-02    126.535127     0.801856                1.386724  280.297174
2013-01-03    105.978627     0.248580                0.704450  208.653825
2013-01-04     98.928452     0.304661                0.397279  413.280533
2013-01-05    126.634476     1.247861                0.149791  231.119433
...                  ...          ...                     ...         ...
2017-08-11    144.669556     6.226232               10.821656  472.536156
2017-08-12    171.941641     7.166545               10.609163  290.223103
2017-08-13     92.132652     4.921465                7.729537  148.773629
2017-08-14    175.682127     6.640199               11.166642  321.014768
2017-08-15    171.216813     6.656201               11.092323  291.064830

                                                                              \
store_nbr
family     PREPARED FOODS      PRODUCE SCHOOL AND OFFICE SUPPLIES    SEAFOOD
date
2013-01-01      65.910624   -69.529587                  -0.088074  19.524204
2013-01-02      79.937110  1019.995315                  -0.064860  26.171853
2013-01-03      70.839885   -63.175620                  -0.133203  18.214824
2013-01-04      81.035873    13.880021                  -0.121562  35.009129
2013-01-05      75.075560    75.630615                  -0.129640  23.346796
...                   ...          ...                        ...        ...
2017-08-11      95.050004  2711.319805                   0.281193  38.868988
2017-08-12      88.955790  2758.458834                   0.285646  27.010329
2017-08-13      41.758897  2020.982493                   0.241503  12.832282
2017-08-14      79.454509  2752.265908                   0.306333  21.932387
2017-08-15      81.669322  2641.658118                   0.368354  23.987483

                                                                           \
store_nbr          10
family     AUTOMOTIVE BABY CARE    BEAUTY    BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   3.387988  0.007095  1.167922   596.438273   0.0   103.860919
2013-01-02   3.279779  0.013367  0.949905   466.803969   0.0    90.319679
2013-01-03   3.028000 -0.078702  0.854518   437.100702   0.0    83.455832
2013-01-04   3.249304 -0.073983  0.827549   453.144895   0.0    75.593902
2013-01-05   4.234388  0.057008  1.744438   855.039508   0.0   125.210527
...               ...       ...       ...          ...   ...          ...
2017-08-11   2.439119  0.017223  1.544529  1128.209012   0.0    63.685586
2017-08-12   3.483113  0.136769  2.450379  1537.126730   0.0   113.578574
2017-08-13   3.758175  0.087956  2.376134  1555.943356   0.0   131.364647
2017-08-14   2.637702 -0.037561  1.956615  1300.779537   0.0   106.402404
2017-08-15   2.551557 -0.044098  1.937800  1262.913430   0.0    97.376170

                                                                        \
store_nbr
family     CELEBRATION     CLEANING       DAIRY        DELI       EGGS
date
2013-01-01   -0.081788   958.324202  165.000867  200.119977  45.440317
2013-01-02   -0.018729   834.795558  148.240367  176.475823  40.112094
2013-01-03    0.055639   815.541408  108.446078  183.031155  36.894683
2013-01-04    0.216741   764.704858   95.738320  175.244794  33.032136
2013-01-05    3.206897  1105.848087  212.280769  244.696513  51.666561
...                ...          ...         ...         ...        ...
2017-08-11    4.501003   613.907636  255.139193  246.183436  31.490925
2017-08-12    7.437690   962.222632  374.407159  316.454612  50.425191
2017-08-13    5.192967   886.207493  411.032030  343.820954  66.305714
2017-08-14    3.903835   764.964197  340.899213  288.702961  62.109104
2017-08-15    4.322100   758.670389  327.494875  274.932553  43.653470

                                                                              \
store_nbr
family     FROZEN FOODS    GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01   139.835597  2266.075338   6.624446  0.513994           3.849096
2013-01-02   125.729899  1954.871236   6.218190  0.557357           3.963635
2013-01-03   113.761296  1829.533587   6.058977  0.529206           3.334792
2013-01-04   105.453373  1677.406340   6.858634  0.469324           4.391063
2013-01-05   133.129459  2807.175777   9.735877  0.801037           8.638666
...                 ...          ...        ...       ...                ...
2017-08-11    48.295429  2098.977413   5.335495  0.577502          11.213313
2017-08-12    80.813989  3249.165741   8.359806  0.907120          15.404510
2017-08-13    57.183492  3220.500888   4.121785  0.783836          12.214877
2017-08-14    50.758677  2731.343525   2.984041  0.643434          10.155236
2017-08-15    45.860993  2616.049957   3.887186  0.571100          10.309994

                                                                       \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES   HOME CARE LADIESWEAR
date
2013-01-01            1.344018        0.251955   43.053054  -1.498056
2013-01-02            0.400123        0.237745   17.942128  -1.736889
2013-01-03            0.327063        0.198822   11.442031  -1.486409
2013-01-04            0.302025        0.230783    0.616075  -1.522274
2013-01-05            3.291588        0.263082   65.595746   2.087841
...                        ...             ...         ...        ...
2017-08-11            7.966177        0.030463  183.421468   4.504875
2017-08-12           10.904184        0.062820  249.305653   7.979435
2017-08-13            9.914766        0.132731  244.517534   8.190472
2017-08-14            8.607817        0.032741  221.011352   5.332707
2017-08-15            8.807999        0.044016  225.720723   5.416522

                                                                             \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES       MEATS
date
2013-01-01       -0.020445  4.182334        23.076062 -0.155524  230.344532
2013-01-02       -0.017829  3.734340        21.295563 -0.158046  204.700167
2013-01-03        0.009823  3.902389        23.172462 -0.178834  230.296609
2013-01-04       -0.020382  3.518510        26.689538 -0.211614  177.476418
2013-01-05       -0.017127  4.976743        36.252493  0.075529  245.215379
...                    ...       ...              ...       ...         ...
2017-08-11        0.025269  0.522178        19.383240  0.472556  104.876217
2017-08-12        0.027408  2.064076        29.527874  0.756739  172.245275
2017-08-13        0.020931  2.087113         4.471234  0.655435  174.966922
2017-08-14        0.010035  1.408606         8.266482  0.533786  167.018297
2017-08-15        0.011426  1.550605        10.953551  0.525260  160.504619

                                                                           \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS     POULTRY
date
2013-01-01    190.752364     0.031871                0.536588  203.477066
2013-01-02    165.464692     0.022304                0.199619  175.846395
2013-01-03    157.608601    -0.128741                0.191914  182.556915
2013-01-04    138.657882    -0.106583                0.247557  174.859679
2013-01-05    239.081684     0.138660                1.470359  254.932085
...                  ...          ...                     ...         ...
2017-08-11    144.753944     0.716417                4.576396  132.587762
2017-08-12    246.263683     0.965785                5.791798  214.427184
2017-08-13    238.152828     0.965487                5.398292  212.715945
2017-08-14    197.673888     0.781937                4.844265  150.211841
2017-08-15    196.146146     0.821701                4.899555  151.913988

                                                                            \
store_nbr
family     PREPARED FOODS     PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       5.732196   68.955382                  -1.190689  2.897931
2013-01-02       3.535297    8.604028                  -1.295300  2.549348
2013-01-03       4.084106    1.798562                  -1.479513  3.062159
2013-01-04       3.393558   -6.567535                  -1.332068  2.360385
2013-01-05      13.693797   43.989643                  -0.966440  3.556021
...                   ...         ...                        ...       ...
2017-08-11      30.029530  247.181574                   2.234371  1.894967
2017-08-12      40.382710  298.036568                   2.717756  3.095539
2017-08-13      38.650825  312.662066                   2.770143  3.307857
2017-08-14      33.658230  276.327872                   2.971160  2.983911
2017-08-15      33.984297  316.678269                   3.457362  2.729856

                                                                           \
store_nbr          11
family     AUTOMOTIVE BABY CARE    BEAUTY    BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   3.483058 -0.154017  2.235711  2123.866500   0.0   496.732833
2013-01-02   4.054140 -0.205819  2.146189  1902.449404   0.0   452.955206
2013-01-03   3.286129 -0.226165  1.952312  2083.098915   0.0   525.031176
2013-01-04   3.569935 -0.200536  1.489720  2629.122989   0.0   455.883960
2013-01-05   5.958976 -0.074940  3.724877  3166.182466   0.0   545.770577
...               ...       ...       ...          ...   ...          ...
2017-08-11   7.394342  0.438229  6.448315  5033.742823   0.0   569.800578
2017-08-12   9.693525  0.567018  8.703507  5581.514941   0.0   658.575592
2017-08-13   9.979935  0.480325  9.745593  5728.060942   0.0   786.842137
2017-08-14   7.634660  0.547526  7.507813  4770.388960   0.0   629.238291
2017-08-15   7.465222  0.478834  7.470043  4561.724978   0.0   624.542376

                                                                         \
store_nbr
family     CELEBRATION     CLEANING       DAIRY        DELI        EGGS
date
2013-01-01   -0.303528  1869.192078  231.648067  291.721384  123.987727
2013-01-02    0.627838  1763.661831  209.955014  250.881466  106.332596
2013-01-03    0.716819  1655.313081  167.121577  280.517057   95.408305
2013-01-04    2.884964  1691.079822  163.802992  274.543361   84.547909
2013-01-05    9.137122  2190.442610  331.371674  349.205528  116.537004
...                ...          ...         ...         ...         ...
2017-08-11   19.617246  1818.331360  611.848721  525.021471  148.234310
2017-08-12   25.860326  2325.030077  781.032000  601.159388  180.630703
2017-08-13   18.740106  2561.532318  943.441443  694.164666  235.187863
2017-08-14   16.186825  2134.146956  703.374922  552.534630  252.713069
2017-08-15   16.050080  2012.672262  690.767542  548.355396  186.081536

                                                                              \
store_nbr
family     FROZEN FOODS    GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01   221.938041  5217.730512  20.524769  0.688950          13.045755
2013-01-02   205.695539  4672.403601  20.908049  0.500702          14.685265
2013-01-03   190.193865  4415.233272  22.359480  0.679262          13.803148
2013-01-04   184.695591  4258.832056  23.966257  0.667950          15.983711
2013-01-05   214.986495  5875.751269  27.700804  0.798636          25.712750
...                 ...          ...        ...       ...                ...
2017-08-11   118.221629  6606.098169  26.323876  0.819458          42.116615
2017-08-12   155.131223  8271.684068  30.271452  0.954396          52.068287
2017-08-13   140.648845  9288.232509  22.911164  1.064354          47.828810
2017-08-14   102.945499  7547.139488  17.824056  0.775812          37.703877
2017-08-15   101.765567  7238.299608  19.676419  0.865993          38.883016

                                                                       \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES   HOME CARE LADIESWEAR
date
2013-01-01            0.986237        0.405256   54.488818  -0.864116
2013-01-02            0.613354        0.440392   38.471597  -1.099044
2013-01-03            0.410422        0.400156   17.080894  -1.106279
2013-01-04           -0.181668        0.335353   -4.674205   0.320877
2013-01-05            6.194518        0.436881  100.562240   1.833938
...                        ...             ...         ...        ...
2017-08-11           19.289738        0.148652  548.345992  15.296090
2017-08-12           25.593001        0.258426  654.027348  16.764561
2017-08-13           27.308573        0.471850  724.782343  18.306144
2017-08-14           21.920119        0.303457  623.177531  14.589516
2017-08-15           21.231774        0.232878  610.869139  13.923109

                                                                              \
store_nbr
family     LAWN AND GARDEN   LINGERIE LIQUOR,WINE,BEER MAGAZINES       MEATS
date
2013-01-01        0.752077  11.707868        59.475770 -1.174952  533.289721
2013-01-02        0.529585  11.157664        69.695364 -1.269426  495.102466
2013-01-03        0.503102  11.446591        75.320194 -1.165168  707.905554
2013-01-04        0.833881  10.925331        86.528917 -1.272166  451.455306
2013-01-05        1.813203  14.240383       104.154581 -0.129799  534.973756
...                    ...        ...              ...       ...         ...
2017-08-11        2.852193   7.979456        76.664856  3.214631  531.803472
2017-08-12        3.878514  11.260630        96.062625  4.341113  612.746669
2017-08-13        3.747664  11.784247        18.855399  4.231070  697.610181
2017-08-14        2.343815   8.541909        34.347178  3.270316  643.476431
2017-08-15        2.622341   8.721633        35.524100  3.244236  626.785872

                                                                           \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS     POULTRY
date
2013-01-01    316.009068    -0.406534                0.095268  662.039956
2013-01-02    298.506248    -0.332309                0.328607  603.629992
2013-01-03    264.079165    -0.393381                0.103977  631.276271
2013-01-04    238.148607    -0.501162               -0.173286  687.727278
2013-01-05    388.437398    -0.107942                3.136047  682.778974
...                  ...          ...                     ...         ...
2017-08-11    388.821886     2.267020               16.675784  506.080786
2017-08-12    541.645023     2.660974               20.024778  507.471091
2017-08-13    648.055638     2.648632               19.975015  561.993509
2017-08-14    484.785034     2.499697               17.792255  288.138470
2017-08-15    471.746033     2.348592               16.700878  428.399848

                                                                              \
store_nbr
family     PREPARED FOODS      PRODUCE SCHOOL AND OFFICE SUPPLIES    SEAFOOD
date
2013-01-01       3.401454   386.009305                  -5.419006   5.555941

In [37]:
lin_pred_df.stack(['store_nbr', 'family']).reorder_levels(['store_nbr', 'family', 'date']).sort_index()

C:\Users\USER\AppData\Local\Temp\ipykernel_880\389358559.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  lin_pred_df.stack(['store_nbr', 'family']).reorder_levels(['store_nbr', 'family', 'date']).sort_index()

                                     sales
store_nbr family     date
1         AUTOMOTIVE 2013-01-01   2.301404
                     2013-01-02   1.972107
                     2013-01-03   1.514684
                     2013-01-04   2.258371
                     2013-01-05   2.186655
...                                    ...
9         SEAFOOD    2017-08-11  10.330447
                     2017-08-12  19.166984
                     2017-08-13  24.021371
                     2017-08-14  13.246103
                     2017-08-15  12.703196

[3008016 rows x 1 columns]

In [38]:
x_tr = linear_model(lin_y = lin_y, lin_y_pred = lin_y_pred, index = lin_y, col = lin_y, df = train_df)
x_tr

C:\Users\USER\AppData\Local\Temp\ipykernel_880\2583430939.py:16: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  resid_long = residuals.stack(['store_nbr', 'family'])

        store_nbr      family        date      sales
id
0               1  AUTOMOTIVE  2013-01-01  -2.301404
1782            1  AUTOMOTIVE  2013-01-02   0.027893
3564            1  AUTOMOTIVE  2013-01-03   1.485316
5346            1  AUTOMOTIVE  2013-01-04   0.741629
7128            1  AUTOMOTIVE  2013-01-05   2.813345
...           ...         ...         ...        ...
2993759         9     SEAFOOD  2017-08-11  13.500553
2995541         9     SEAFOOD  2017-08-12  -2.307983
2997323         9     SEAFOOD  2017-08-13  -4.021371
2999105         9     SEAFOOD  2017-08-14   3.753897
3000887         9     SEAFOOD  2017-08-15   3.296804

[3008016 rows x 4 columns]

In [39]:
scoring(lin_y, lin_pred_df)

MAE: 87.37026, RMSE: 353.26798, R^2:0.38032

In [40]:
xg_y = x_tr.sales.to_frame()
xg_y

             sales
id
0        -2.301404
1782      0.027893
3564      1.485316
5346      0.741629
7128      2.813345
...            ...
2993759  13.500553
2995541  -2.307983
2997323  -4.021371
2999105   3.753897
3000887   3.296804

[3008016 rows x 1 columns]

In [43]:
# Intantiate XGmodel and train
xg_mod = xg.XGBRegressor(
    random_state = 42,
    n_estimators = 1500,
    max_depth = 6,
    subsample= 0.8,
    colsample_bytree = 0.8,
    gamma = 0.3,
    reg_alpha = 0.1,
    reg_lambda = 1.0,
    tree_method = 'hist',
    objective = 'reg:squarederror',
    early_stopping_rounds = 50,
    eval_metric = 'rmse',
    n_jobs = -1,
    verbosity = 1
)
xg_mod

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=50,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1500, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

In [44]:
# Train the Xgb model
split = 2918915
xg_mod.fit(xg_df.iloc[:split], xg_y.iloc[:split],
           eval_set = [(xg_df.iloc[split:], xg_y[split:])],
           verbose = True)

[0]	validation_0-rmse:370.93246
[1]	validation_0-rmse:364.52450
[2]	validation_0-rmse:358.28776
[3]	validation_0-rmse:355.34053
[4]	validation_0-rmse:349.34975
[5]	validation_0-rmse:346.89530
[6]	validation_0-rmse:344.59867
[7]	validation_0-rmse:342.62229
[8]	validation_0-rmse:339.84374
[9]	validation_0-rmse:339.07448
[10]	validation_0-rmse:337.15252
[11]	validation_0-rmse:336.56046
[12]	validation_0-rmse:336.26481
[13]	validation_0-rmse:331.80390
[14]	validation_0-rmse:325.31251
[15]	validation_0-rmse:319.35854
[16]	validation_0-rmse:318.24555
[17]	validation_0-rmse:317.42916
[18]	validation_0-rmse:316.89807
[19]	validation_0-rmse:316.59471
[20]	validation_0-rmse:316.30877
[21]	validation_0-rmse:316.02612
[22]	validation_0-rmse:315.84499
[23]	validation_0-rmse:314.89828
[24]	validation_0-rmse:313.01364
[25]	validation_0-rmse:312.83212
[26]	validation_0-rmse:311.02187
[27]	validation_0-rmse:309.19657
[28]	validation_0-rmse:309.10306
[29]	validation_0-rmse:309.25130
[30]	validation_0-rmse:303.33613
[31]	validation_0-rmse:302.15008
[32]	validation_0-rmse:301.98796
[33]	validation_0-rmse:301.73228
[34]	validation_0-rmse:301.07296
[35]	validation_0-rmse:300.82938
[36]	validation_0-rmse:300.79440
[37]	validation_0-rmse:300.47286
[38]	validation_0-rmse:299.75637
[39]	validation_0-rmse:301.57877
[40]	validation_0-rmse:301.46069
[41]	validation_0-rmse:301.21023
[42]	validation_0-rmse:300.73619
[43]	validation_0-rmse:298.34755
[44]	validation_0-rmse:297.97408
[45]	validation_0-rmse:297.47265
[46]	validation_0-rmse:296.79434
[47]	validation_0-rmse:296.49167
[48]	validation_0-rmse:295.95118
[49]	validation_0-rmse:296.45404
[50]	validation_0-rmse:295.92378
[51]	validation_0-rmse:296.02546
[52]	validation_0-rmse:295.95303
[53]	validation_0-rmse:295.88957
[54]	validation_0-rmse:295.67528
[55]	validation_0-rmse:294.98804
[56]	validation_0-rmse:294.49838
[57]	validation_0-rmse:289.16163
[58]	validation_0-rmse:289.14800
[59]	validation_0-rmse:289.96413
[60]	validation_0-rmse:290.27367
[61]	validation_0-rmse:290.11245
[62]	validation_0-rmse:289.91071
[63]	validation_0-rmse:290.23793
[64]	validation_0-rmse:290.14478
[65]	validation_0-rmse:289.61815
[66]	validation_0-rmse:289.20886
[67]	validation_0-rmse:288.66321
[68]	validation_0-rmse:287.36488
[69]	validation_0-rmse:287.69937
[70]	validation_0-rmse:287.94687
[71]	validation_0-rmse:287.51736
[72]	validation_0-rmse:287.28102
[73]	validation_0-rmse:287.09850
[74]	validation_0-rmse:286.29184
[75]	validation_0-rmse:286.24705
[76]	validation_0-rmse:285.72097
[77]	validation_0-rmse:285.45343
[78]	validation_0-rmse:284.73061
[79]	validation_0-rmse:283.81931
[80]	validation_0-rmse:283.72496
[81]	validation_0-rmse:283.91840
[82]	validation_0-rmse:283.83578
[83]	validation_0-rmse:283.48248
[84]	validation_0-rmse:283.45783
[85]	validation_0-rmse:283.22031
[86]	validation_0-rmse:283.04357
[87]	validation_0-rmse:282.66766
[88]	validation_0-rmse:284.57870
[89]	validation_0-rmse:284.89409
[90]	validation_0-rmse:284.62388
[91]	validation_0-rmse:284.64000
[92]	validation_0-rmse:284.36691
[93]	validation_0-rmse:283.94924
[94]	validation_0-rmse:283.36520
[95]	validation_0-rmse:283.24331
[96]	validation_0-rmse:283.21008
[97]	validation_0-rmse:282.75488
[98]	validation_0-rmse:282.63737
[99]	validation_0-rmse:286.21138
[100]	validation_0-rmse:284.54655
[101]	validation_0-rmse:284.43022
[102]	validation_0-rmse:284.55711
[103]	validation_0-rmse:284.35798
[104]	validation_0-rmse:281.44050
[105]	validation_0-rmse:281.37186
[106]	validation_0-rmse:281.41028
[107]	validation_0-rmse:283.11747
[108]	validation_0-rmse:283.03723
[109]	validation_0-rmse:282.98742
[110]	validation_0-rmse:283.19293
[111]	validation_0-rmse:283.07796
[112]	validation_0-rmse:281.62428
[113]	validation_0-rmse:281.53174
[114]	validation_0-rmse:281.73508
[115]	validation_0-rmse:281.53398
[116]	validation_0-rmse:281.53678
[117]	validation_0-rmse:281.51214
[118]	validation_0-rmse:281.22764
[119]	validation_0-rmse:281.08955
[120]	validation_0-rmse:281.17856
[121]	validation_0-rmse:279.95527
[122]	validation_0-rmse:279.87787
[123]	validation_0-rmse:279.93295
[124]	validation_0-rmse:279.72247
[125]	validation_0-rmse:279.68266
[126]	validation_0-rmse:279.51246
[127]	validation_0-rmse:280.51653
[128]	validation_0-rmse:280.23570
[129]	validation_0-rmse:280.20641
[130]	validation_0-rmse:280.23346
[131]	validation_0-rmse:280.09660
[132]	validation_0-rmse:280.08252
[133]	validation_0-rmse:280.02864
[134]	validation_0-rmse:279.92544
[135]	validation_0-rmse:280.01635
[136]	validation_0-rmse:279.64899
[137]	validation_0-rmse:279.65167
[138]	validation_0-rmse:279.46041
[139]	validation_0-rmse:279.45900
[140]	validation_0-rmse:279.36090
[141]	validation_0-rmse:279.50085
[142]	validation_0-rmse:280.01095
[143]	validation_0-rmse:280.20183
[144]	validation_0-rmse:280.20952
[145]	validation_0-rmse:280.21145
[146]	validation_0-rmse:280.15011
[147]	validation_0-rmse:280.09562
[148]	validation_0-rmse:280.07832
[149]	validation_0-rmse:280.08365
[150]	validation_0-rmse:279.95452
[151]	validation_0-rmse:280.17221
[152]	validation_0-rmse:280.07958
[153]	validation_0-rmse:279.99785
[154]	validation_0-rmse:279.82670
[155]	validation_0-rmse:279.45556
[156]	validation_0-rmse:279.40116
[157]	validation_0-rmse:278.95834
[158]	validation_0-rmse:280.93661
[159]	validation_0-rmse:280.88686
[160]	validation_0-rmse:280.87407
[161]	validation_0-rmse:279.91921
[162]	validation_0-rmse:279.79102
[163]	validation_0-rmse:279.84990
[164]	validation_0-rmse:279.78015
[165]	validation_0-rmse:279.82201
[166]	validation_0-rmse:279.76826
[167]	validation_0-rmse:279.56691
[168]	validation_0-rmse:279.33919
[169]	validation_0-rmse:279.28373
[170]	validation_0-rmse:279.12489
[171]	validation_0-rmse:279.08616
[172]	validation_0-rmse:279.05176
[173]	validation_0-rmse:278.95190
[174]	validation_0-rmse:277.83256
[175]	validation_0-rmse:278.48484
[176]	validation_0-rmse:278.84905
[177]	validation_0-rmse:278.68467
[178]	validation_0-rmse:278.69726
[179]	validation_0-rmse:278.52206
[180]	validation_0-rmse:278.14420
[181]	validation_0-rmse:277.69926
[182]	validation_0-rmse:277.51750
[183]	validation_0-rmse:277.51566
[184]	validation_0-rmse:277.05119
[185]	validation_0-rmse:276.37813
[186]	validation_0-rmse:276.55406
[187]	validation_0-rmse:276.52208
[188]	validation_0-rmse:276.18149
[189]	validation_0-rmse:275.96336
[190]	validation_0-rmse:275.97352
[191]	validation_0-rmse:275.98137
[192]	validation_0-rmse:275.60908
[193]	validation_0-rmse:275.47211
[194]	validation_0-rmse:275.35570
[195]	validation_0-rmse:275.33530
[196]	validation_0-rmse:275.27124
[197]	validation_0-rmse:275.08555
[198]	validation_0-rmse:275.49581
[199]	validation_0-rmse:275.49248
[200]	validation_0-rmse:275.46270
[201]	validation_0-rmse:275.69626
[202]	validation_0-rmse:275.09740
[203]	validation_0-rmse:275.23769
[204]	validation_0-rmse:275.18177
[205]	validation_0-rmse:274.63966
[206]	validation_0-rmse:274.69955
[207]	validation_0-rmse:274.68578
[208]	validation_0-rmse:274.65334
[209]	validation_0-rmse:274.32526
[210]	validation_0-rmse:274.45801
[211]	validation_0-rmse:274.63611
[212]	validation_0-rmse:274.44227
[213]	validation_0-rmse:274.37283
[214]	validation_0-rmse:274.36865
[215]	validation_0-rmse:274.28467
[216]	validation_0-rmse:274.08688
[217]	validation_0-rmse:274.57625
[218]	validation_0-rmse:274.52922
[219]	validation_0-rmse:274.49242
[220]	validation_0-rmse:274.46240
[221]	validation_0-rmse:274.46144
[222]	validation_0-rmse:274.50651
[223]	validation_0-rmse:274.51365
[224]	validation_0-rmse:274.19144
[225]	validation_0-rmse:273.78135
[226]	validation_0-rmse:273.73758
[227]	validation_0-rmse:273.64919
[228]	validation_0-rmse:273.93760
[229]	validation_0-rmse:273.24229
[230]	validation_0-rmse:273.16502
[231]	validation_0-rmse:272.84699
[232]	validation_0-rmse:272.82574
[233]	validation_0-rmse:272.86084
[234]	validation_0-rmse:272.60010
[235]	validation_0-rmse:272.56263
[236]	validation_0-rmse:272.59668
[237]	validation_0-rmse:273.35985
[238]	validation_0-rmse:273.36300
[239]	validation_0-rmse:273.33207
[240]	validation_0-rmse:273.22487
[241]	validation_0-rmse:273.29662
[242]	validation_0-rmse:272.90036
[243]	validation_0-rmse:272.83617
[244]	validation_0-rmse:272.78085
[245]	validation_0-rmse:272.97503
[246]	validation_0-rmse:272.96909
[247]	validation_0-rmse:272.89829
[248]	validation_0-rmse:272.95822
[249]	validation_0-rmse:272.34130
[250]	validation_0-rmse:272.32605
[251]	validation_0-rmse:272.27810
[252]	validation_0-rmse:272.53781
[253]	validation_0-rmse:272.50513
[254]	validation_0-rmse:272.48837
[255]	validation_0-rmse:272.50418
[256]	validation_0-rmse:272.53245
[257]	validation_0-rmse:272.77581
[258]	validation_0-rmse:272.08933
[259]	validation_0-rmse:272.03939
[260]	validation_0-rmse:271.94933
[261]	validation_0-rmse:271.79643
[262]	validation_0-rmse:271.59354
[263]	validation_0-rmse:271.50303
[264]	validation_0-rmse:271.46087
[265]	validation_0-rmse:271.39607
[266]	validation_0-rmse:271.36615
[267]	validation_0-rmse:271.42041
[268]	validation_0-rmse:271.40830
[269]	validation_0-rmse:271.32750
[270]	validation_0-rmse:271.28638
[271]	validation_0-rmse:271.33992
[272]	validation_0-rmse:271.13608
[273]	validation_0-rmse:271.17626
[274]	validation_0-rmse:270.88176
[275]	validation_0-rmse:270.78744
[276]	validation_0-rmse:270.25524
[277]	validation_0-rmse:270.20087
[278]	validation_0-rmse:269.85465
[279]	validation_0-rmse:269.75975
[280]	validation_0-rmse:269.74471
[281]	validation_0-rmse:269.73914
[282]	validation_0-rmse:269.71019
[283]	validation_0-rmse:269.64037
[284]	validation_0-rmse:269.65678
[285]	validation_0-rmse:269.58614
[286]	validation_0-rmse:269.60306
[287]	validation_0-rmse:269.67845
[288]	validation_0-rmse:269.68173
[289]	validation_0-rmse:269.62451
[290]	validation_0-rmse:269.84404
[291]	validation_0-rmse:269.34962
[292]	validation_0-rmse:269.27978
[293]	validation_0-rmse:269.26296
[294]	validation_0-rmse:269.16957
[295]	validation_0-rmse:269.23087
[296]	validation_0-rmse:269.16806
[297]	validation_0-rmse:269.19703
[298]	validation_0-rmse:269.18802
[299]	validation_0-rmse:268.87801
[300]	validation_0-rmse:268.83149
[301]	validation_0-rmse:268.80677
[302]	validation_0-rmse:268.59820
[303]	validation_0-rmse:268.69975
[304]	validation_0-rmse:268.58849
[305]	validation_0-rmse:268.57624
[306]	validation_0-rmse:268.49028
[307]	validation_0-rmse:268.46240
[308]	validation_0-rmse:268.38410
[309]	validation_0-rmse:268.57468
[310]	validation_0-rmse:268.54100
[311]	validation_0-rmse:268.44254
[312]	validation_0-rmse:268.48353
[313]	validation_0-rmse:268.41259
[314]	validation_0-rmse:268.41014
[315]	validation_0-rmse:268.51856
[316]	validation_0-rmse:268.33347
[317]	validation_0-rmse:268.24748
[318]	validation_0-rmse:268.24365
[319]	validation_0-rmse:268.19602
[320]	validation_0-rmse:268.19124
[321]	validation_0-rmse:268.17975
[322]	validation_0-rmse:268.23405
[323]	validation_0-rmse:268.31334
[324]	validation_0-rmse:268.12123
[325]	validation_0-rmse:268.09496
[326]	validation_0-rmse:268.33130
[327]	validation_0-rmse:268.32593
[328]	validation_0-rmse:268.05163
[329]	validation_0-rmse:267.72443
[330]	validation_0-rmse:267.73396
[331]	validation_0-rmse:267.70224
[332]	validation_0-rmse:267.66163
[333]	validation_0-rmse:267.77997
[334]	validation_0-rmse:267.83796
[335]	validation_0-rmse:267.68054
[336]	validation_0-rmse:267.70889
[337]	validation_0-rmse:267.65053
[338]	validation_0-rmse:267.67784
[339]	validation_0-rmse:267.34629
[340]	validation_0-rmse:267.08437
[341]	validation_0-rmse:267.04990
[342]	validation_0-rmse:266.98087
[343]	validation_0-rmse:266.87858
[344]	validation_0-rmse:266.91188
[345]	validation_0-rmse:266.88735
[346]	validation_0-rmse:266.85567
[347]	validation_0-rmse:266.99511
[348]	validation_0-rmse:266.86276
[349]	validation_0-rmse:266.86015
[350]	validation_0-rmse:266.86003
[351]	validation_0-rmse:266.46442
[352]	validation_0-rmse:266.46938
[353]	validation_0-rmse:266.43313
[354]	validation_0-rmse:266.30228
[355]	validation_0-rmse:266.28327
[356]	validation_0-rmse:266.27048
[357]	validation_0-rmse:266.25780
[358]	validation_0-rmse:266.24734
[359]	validation_0-rmse:266.21416
[360]	validation_0-rmse:266.19029
[361]	validation_0-rmse:266.11379
[362]	validation_0-rmse:266.30070
[363]	validation_0-rmse:266.28609
[364]	validation_0-rmse:266.32869
[365]	validation_0-rmse:266.15805
[366]	validation_0-rmse:266.13993
[367]	validation_0-rmse:265.95926
[368]	validation_0-rmse:266.15058
[369]	validation_0-rmse:265.96243
[370]	validation_0-rmse:265.90606
[371]	validation_0-rmse:265.89563
[372]	validation_0-rmse:265.86353
[373]	validation_0-rmse:265.90176
[374]	validation_0-rmse:265.84025
[375]	validation_0-rmse:265.87498
[376]	validation_0-rmse:265.92602
[377]	validation_0-rmse:265.93847
[378]	validation_0-rmse:265.85447
[379]	validation_0-rmse:265.85276
[380]	validation_0-rmse:265.82519
[381]	validation_0-rmse:265.81757
[382]	validation_0-rmse:265.84858
[383]	validation_0-rmse:265.69958
[384]	validation_0-rmse:265.58149
[385]	validation_0-rmse:265.43301
[386]	validation_0-rmse:265.74373
[387]	validation_0-rmse:265.71843
[388]	validation_0-rmse:266.06962
[389]	validation_0-rmse:265.98657
[390]	validation_0-rmse:265.98551
[391]	validation_0-rmse:265.94663
[392]	validation_0-rmse:265.90947
[393]	validation_0-rmse:265.91509
[394]	validation_0-rmse:265.86304
[395]	validation_0-rmse:265.83900
[396]	validation_0-rmse:265.79195
[397]	validation_0-rmse:265.79317
[398]	validation_0-rmse:265.56866
[399]	validation_0-rmse:265.35181
[400]	validation_0-rmse:265.33445
[401]	validation_0-rmse:265.29143
[402]	validation_0-rmse:265.12311
[403]	validation_0-rmse:265.10358
[404]	validation_0-rmse:265.00300
[405]	validation_0-rmse:264.94361
[406]	validation_0-rmse:264.96141
[407]	validation_0-rmse:264.91872
[408]	validation_0-rmse:264.95014
[409]	validation_0-rmse:265.03991
[410]	validation_0-rmse:265.06282
[411]	validation_0-rmse:264.98913
[412]	validation_0-rmse:265.03819
[413]	validation_0-rmse:265.02716
[414]	validation_0-rmse:264.90039
[415]	validation_0-rmse:264.89445
[416]	validation_0-rmse:264.87260
[417]	validation_0-rmse:264.79359
[418]	validation_0-rmse:264.74072
[419]	validation_0-rmse:264.73156
[420]	validation_0-rmse:264.61357
[421]	validation_0-rmse:264.67445
[422]	validation_0-rmse:264.70279
[423]	validation_0-rmse:264.59807
[424]	validation_0-rmse:264.42579
[425]	validation_0-rmse:264.46299
[426]	validation_0-rmse:264.39014
[427]	validation_0-rmse:264.40723
[428]	validation_0-rmse:264.35724
[429]	validation_0-rmse:264.37837
[430]	validation_0-rmse:264.33966
[431]	validation_0-rmse:264.34291
[432]	validation_0-rmse:264.30271
[433]	validation_0-rmse:264.29617
[434]	validation_0-rmse:264.40622
[435]	validation_0-rmse:264.36495
[436]	validation_0-rmse:263.97058
[437]	validation_0-rmse:263.94073
[438]	validation_0-rmse:263.94620
[439]	validation_0-rmse:263.79787
[440]	validation_0-rmse:263.85074
[441]	validation_0-rmse:263.86746
[442]	validation_0-rmse:263.86908
[443]	validation_0-rmse:263.78403
[444]	validation_0-rmse:263.72153
[445]	validation_0-rmse:263.75288
[446]	validation_0-rmse:263.70948
[447]	validation_0-rmse:263.71821
[448]	validation_0-rmse:263.57801
[449]	validation_0-rmse:263.62911
[450]	validation_0-rmse:263.68353
[451]	validation_0-rmse:263.66331
[452]	validation_0-rmse:263.67558
[453]	validation_0-rmse:263.63337
[454]	validation_0-rmse:263.55213
[455]	validation_0-rmse:263.98841
[456]	validation_0-rmse:263.12117
[457]	validation_0-rmse:263.07127
[458]	validation_0-rmse:263.28668
[459]	validation_0-rmse:263.18980
[460]	validation_0-rmse:263.23192
[461]	validation_0-rmse:263.27434
[462]	validation_0-rmse:263.27649
[463]	validation_0-rmse:264.49841
[464]	validation_0-rmse:264.46471
[465]	validation_0-rmse:264.47471
[466]	validation_0-rmse:264.49886
[467]	validation_0-rmse:264.45050
[468]	validation_0-rmse:264.45300
[469]	validation_0-rmse:264.46636
[470]	validation_0-rmse:264.46517
[471]	validation_0-rmse:264.47962
[472]	validation_0-rmse:264.48438
[473]	validation_0-rmse:264.41642
[474]	validation_0-rmse:264.47349
[475]	validation_0-rmse:264.47635
[476]	validation_0-rmse:264.45644
[477]	validation_0-rmse:264.43689
[478]	validation_0-rmse:264.38308
[479]	validation_0-rmse:264.40691
[480]	validation_0-rmse:264.32122
[481]	validation_0-rmse:264.31801
[482]	validation_0-rmse:264.31495
[483]	validation_0-rmse:265.05676
[484]	validation_0-rmse:265.02461
[485]	validation_0-rmse:265.02652
[486]	validation_0-rmse:265.00098
[487]	validation_0-rmse:265.06269
[488]	validation_0-rmse:265.08234
[489]	validation_0-rmse:265.11736
[490]	validation_0-rmse:265.18546
[491]	validation_0-rmse:265.27242
[492]	validation_0-rmse:265.18151
[493]	validation_0-rmse:265.42995
[494]	validation_0-rmse:265.43364
[495]	validation_0-rmse:265.10604
[496]	validation_0-rmse:265.01640
[497]	validation_0-rmse:265.04609
[498]	validation_0-rmse:264.96731
[499]	validation_0-rmse:264.95604
[500]	validation_0-rmse:264.89058
[501]	validation_0-rmse:264.86049
[502]	validation_0-rmse:264.81344
[503]	validation_0-rmse:265.34152
[504]	validation_0-rmse:265.33425
[505]	validation_0-rmse:265.33108
[506]	validation_0-rmse:265.37567
[507]	validation_0-rmse:265.41512

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=50,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1500, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

In [46]:
# Intantiate XGmodel and train
xg_model = xg.XGBRegressor(
    random_state = 42,
    n_estimators = 448,
    max_depth = 6,
    subsample= 0.8,
    colsample_bytree = 0.8,
    gamma = 0.3,
    reg_alpha = 0.1,
    reg_lambda = 1.0,
    tree_method = 'hist',
    objective = 'reg:squarederror',
    n_jobs = -1,
    verbosity = 1
)
xg_model

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=448, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

In [47]:
xg_model.fit(xg_df, xg_y)

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=448, n_jobs=-1,
             num_parallel_tree=None, random_state=42, ...)

In [48]:
xg_pred = xg_model.predict(xg_df)
xg_pred

array([ 18.292913, -76.46892 , -23.67076 , ...,  22.426315, -16.459198,
       -26.131474], dtype=float32)

In [49]:
xgp_df = pd.DataFrame(xg_pred, index = xg_y.index, columns = ['XGB_pred'])

In [50]:
xgp_df

           XGB_pred
id
0         18.292913
1782     -76.468918
3564     -23.670759
5346     -56.840210
7128     -38.687386
...             ...
2993759   56.250439
2995541 -299.336609
2997323   22.426315
2999105  -16.459198
3000887  -26.131474

[3008016 rows x 1 columns]

In [51]:
def wide_to_long(df, df2):
    long = df.stack(['store_nbr', 'family']) 
    long = long.reorder_levels(['store_nbr', 'family', 'date']).sort_index()
    long = long.loc[df2.index]

    # Change long to have the same index as our tree model
    tr = df2[['id']].merge(long, left_index = True, right_index = True, how = 'outer')
    tr = tr.reset_index().set_index('id')
    tr['LIN_pred'] = tr.sales
    linp_df = tr.LIN_pred.to_frame()
    return linp_df

In [52]:
linp_df = wide_to_long(lin_pred_df, train_df)
linp_df

C:\Users\USER\AppData\Local\Temp\ipykernel_880\2168376627.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  long = df.stack(['store_nbr', 'family'])

          LIN_pred
id
0         2.301404
1782      1.972107
3564      1.514684
5346      2.258371
7128      2.186655
...            ...
2993759  10.330447
2995541  19.166984
2997323  24.021371
2999105  13.246103
3000887  12.703196

[3008016 rows x 1 columns]

In [53]:
sub = pd.DataFrame()
sub['sales']= xgp_df['XGB_pred'] + linp_df['LIN_pred']
sub

              sales
id
0         20.594318
1782     -74.496811
3564     -22.156075
5346     -54.581839
7128     -36.500730
...             ...
2993759   66.580885
2995541 -280.169625
2997323   46.447686
2999105   -3.213094
3000887  -13.428278

[3008016 rows x 1 columns]

In [54]:
scoring(tree_y, sub)

MAE: 373.12573, RMSE: 1129.17381, R^2:-175461.34375

In [55]:
# Create the prediction
lin_p = lin_model.predict(lin_test)
xg_p = xg_model.predict(xg_test)
# make xg_p a dataframe
xgr_sub = pd.DataFrame(xg_p, index = xg_test.index, columns = ['XGB_pred'])
xgr_sub

           XGB_pred
id
3000888   20.847168
3002670   33.964916
3004452   23.592819
3006234  -31.327726
3008016 -110.200699
...             ...
3022271   10.942481
3024053  -20.161854
3025835  -19.287447
3027617  -22.637669
3029399   -7.312384

[28512 rows x 1 columns]

In [56]:
lin_sub = wide_to_long(df = pd.DataFrame(lin_p,
                                    index = lin_test.index,
                                    columns = lin_y.columns), df2 = test_df)
lin_sub

C:\Users\USER\AppData\Local\Temp\ipykernel_880\2168376627.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  long = df.stack(['store_nbr', 'family'])

          LIN_pred
id
3000888   4.969832
3002670   4.478898
3004452   5.188625
3006234   5.082703
3008016   2.754747
...            ...
3022271  25.166465
3024053  14.343206
3025835  13.747100
3027617  12.764019
3029399  16.089263

[28512 rows x 1 columns]

In [57]:
subm = pd.DataFrame()
subm['sales']= xgr_sub['XGB_pred'] + lin_sub['LIN_pred']
subm

              sales
id
3000888   25.817000
3002670   38.443814
3004452   28.781445
3006234  -26.245023
3008016 -107.445952
...             ...
3022271   36.108946
3024053   -5.818648
3025835   -5.540347
3027617   -9.873650
3029399    8.776879

[28512 rows x 1 columns]

In [58]:
subm.to_csv('submislog.csv', index = True)

### LOG-TRANSFORMATION

Converting our targets into logged transformed values to improve the score of our XGB model in this hybrid cofiguration

> Using Logtransformed targets to trian our model for improvements

In [59]:
lin_df

,const,trend,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)"
date,,,,,,,,,,,,,,,,,,,,,,
2013-01-01,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000
2013-01-02,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.017213,0.999852,0.034422,0.999407,0.051620,0.998667,0.068802,0.997630,0.085965,0.996298,0.069756,0.997564,0.139173,0.990268
2013-01-03,1.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.034422,0.999407,0.068802,0.997630,0.103102,0.994671,0.137279,0.990532,0.171293,0.985220,0.139173,0.990268,0.275637,0.961262
2013-01-04,1.0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.051620,0.998667,0.103102,0.994671,0.154309,0.988023,0.205104,0.978740,0.255353,0.966848,0.207912,0.978148,0.406737,0.913545
2013-01-05,1.0,5.0,0.0,0.0,0.0,1.0,0.0,0.0,0.068802,0.997630,0.137279,0.990532,0.205104,0.978740,0.271958,0.962309,0.337523,0.941317,0.275637,0.961262,0.529919,0.848048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-11,1.0,1684.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.628763,-0.777597,0.977848,0.209315,-0.891981,0.452072,0.409356,-0.912375,0.255353,0.966848,0.334880,-0.942261,-0.631088,0.775711
2017-08-12,1.0,1685.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.642055,-0.766659,0.984474,0.175531,-0.867456,0.497513,0.345612,-0.938377,0.337523,0.941317,0.269797,-0.962917,-0.519584,0.854419
2017-08-13,1.0,1686.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.655156,-0.755493,0.989932,0.141540,-0.840618,0.541628,0.280231,-0.959933,0.417194,0.908818,0.203456,-0.979084,-0.398401,0.917211
2017-08-14,1.0,1687.0,0.0,0.0,0.0,0.0,0.0,1.0,-0.668064,-0.744104,0.994218,0.107381,-0.811539,0.584298,0.213521,-0.976938,0.493776,0.869589,0.136167,-0.990686,-0.269797,0.962917
2017-08-15,1.0,1688.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.680773,-0.732494,0.997325,0.073095,-0.780296,0.625411,0.145799,-0.989314,0.566702,0.823923,0.068242,-0.997669,-0.136167,0.990686

In [60]:
lin_test

,const,trend,"s(2,7)","s(3,7)","s(4,7)","s(5,7)","s(6,7)","s(7,7)","sin(1,freq=YE-DEC)","cos(1,freq=YE-DEC)","sin(2,freq=YE-DEC)","cos(2,freq=YE-DEC)","sin(3,freq=YE-DEC)","cos(3,freq=YE-DEC)","sin(4,freq=YE-DEC)","cos(4,freq=YE-DEC)","sin(5,freq=YE-DEC)","cos(5,freq=YE-DEC)","sin(1,freq=QE-DEC)","cos(1,freq=QE-DEC)","sin(2,freq=QE-DEC)","cos(2,freq=QE-DEC)"
date,,,,,,,,,,,,,,,,,,,,,,
2017-08-16,1,1689,1,0,0,0,0,0,-0.693281,-0.720667,0.999250,0.038722,-0.746972,0.664855,0.077386,-0.997001,0.635432,0.772157,1.220000e-16,-1.000000,-2.450000e-16,1.000000
2017-08-17,1,1690,0,1,0,0,0,0,-0.705584,-0.708627,0.999991,0.004304,-0.711657,0.702527,0.008607,-0.999963,0.699458,0.714673,-6.824241e-02,-0.997669,1.361666e-01,0.990686
2017-08-18,1,1691,0,0,1,0,0,0,-0.717677,-0.696376,0.999546,-0.030120,-0.674444,0.738326,-0.060213,-0.998186,0.758306,0.651899,-1.361666e-01,-0.990686,2.697968e-01,0.962917
2017-08-19,1,1692,0,0,0,1,0,0,-0.729558,-0.683919,0.997917,-0.064508,-0.635432,0.772157,-0.128748,-0.991677,0.811539,0.584298,-2.034560e-01,-0.979084,3.984011e-01,0.917211
2017-08-20,1,1693,0,0,0,0,1,0,-0.741222,-0.671260,0.995105,-0.098820,-0.594727,0.803928,-0.196673,-0.980469,0.858764,0.512371,-2.697968e-01,-0.962917,5.195840e-01,0.854419
2017-08-21,1,1694,0,0,0,0,0,1,-0.752667,-0.658402,0.991114,-0.133015,-0.552435,0.833556,-0.263665,-0.964614,0.899631,0.436651,-3.348796e-01,-0.942261,6.310879e-01,0.775711
2017-08-22,1,1695,0,0,0,0,0,0,-0.763889,-0.645348,0.985948,-0.167052,-0.508671,0.860961,-0.329408,-0.944188,0.933837,0.357698,-3.984011e-01,-0.917211,7.308360e-01,0.682553
2017-08-23,1,1696,1,0,0,0,0,0,-0.774884,-0.632103,0.979614,-0.200891,-0.463550,0.886071,-0.393590,-0.919286,0.961130,0.276097,-4.600650e-01,-0.887885,8.169699e-01,0.576680
2017-08-24,1,1697,0,1,0,0,0,0,-0.785650,-0.618671,0.972118,-0.234491,-0.417194,0.908818,-0.455907,-0.890028,0.981306,0.192452,-5.195840e-01,-0.854419,8.878852e-01,0.460065
2017-08-25,1,1698,0,0,1,0,0,0,-0.796183,-0.605056,0.963471,-0.267814,-0.369725,0.929141,-0.516062,-0.856551,0.994218,0.107381,-5.766803e-01,-0.816970,9.422609e-01,0.334880
2017-08-26,1,1699,0,0,0,1,0,0,-0.806480,-0.591261,0.953681,-0.300820,-0.321270,0.946988,-0.573772,-0.819015,0.999769,0.021516,-6.310879e-01,-0.775711,9.790841e-01,0.203456
2017-08-27,1,1700,0,0,0,0,1,0,-0.816538,-0.577292,0.942761,-0.333469,-0.271958,0.962309,-0.628763,-0.777597,0.997917,-0.064508,-6.825531e-01,-0.730836,9.976688e-01,0.068242
2017-08-28,1,1701,0,0,0,0,0,1,-0.826354,-0.563151,0.930724,-0.365723,-0.221922,0.975065,-0.680773,-0.732494,0.988678,-0.150055,-7.308360e-01,-0.682553,9.976688e-01,-0.068242
2017-08-29,1,1702,0,0,0,0,0,0,-0.835925,-0.548843,0.917584,-0.397543,-0.171293,0.985220,-0.729558,-0.683919,0.972118,-0.234491,-7.757113e-01,-0.631088,9.790841e-01,-0.203456
2017-08-30,1,1703,1,0,0,0,0,0,-0.845249,-0.534373,0.903356,-0.428892,-0.120208,0.992749,-0.774884,-0.632103,0.948362,-0.317191,-8.169699e-01,-0.576680,9.422609e-01,-0.334880
2017-08-31,1,1704,0,1,0,0,0,0,-0.854322,-0.519744,0.888057,-0.459733,-0.068802,0.997630,-0.816538,-0.577292,0.917584,-0.397543,-8.544194e-01,-0.519584,8.878852e-01,-0.460065

In [61]:
lin_y

                sales                                                \
store_nbr           1
family     AUTOMOTIVE BABY CARE BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01        0.0       0.0    0.0       0.0   0.0     0.000000
2013-01-02        2.0       0.0    2.0    1091.0   0.0   470.652008
2013-01-03        3.0       0.0    0.0     919.0   0.0   310.654999
2013-01-04        3.0       0.0    3.0     953.0   0.0   198.365997
2013-01-05        5.0       0.0    3.0    1160.0   0.0   301.057007
...               ...       ...    ...       ...   ...          ...
2017-08-11        1.0       0.0    1.0    1006.0   0.0   145.606995
2017-08-12        6.0       0.0    3.0    1659.0   0.0   243.220001
2017-08-13        1.0       0.0    1.0     803.0   0.0   136.679001
2017-08-14        1.0       0.0    6.0    2201.0   0.0   346.037994
2017-08-15        4.0       0.0    4.0    1942.0   0.0   329.541016

                                                                        \
store_nbr
family     CELEBRATION CLEANING  DAIRY        DELI   EGGS FROZEN FOODS
date
2013-01-01         0.0      0.0    0.0    0.000000    0.0     0.000000
2013-01-02         0.0   1060.0  579.0  164.069000  246.0   131.000000
2013-01-03         0.0    836.0  453.0  151.582001  203.0    87.043999
2013-01-04         0.0    827.0  460.0  131.410995  171.0    65.000000
2013-01-05         0.0    811.0  464.0  118.612999  177.0    70.000000
...                ...      ...    ...         ...    ...          ...
2017-08-11         4.0    341.0  343.0   64.302002   86.0    61.000000
2017-08-12         3.0    351.0  526.0   99.487999  113.0   107.793999
2017-08-13         1.0    169.0  266.0   47.770000   60.0    50.000000
2017-08-14         4.0    571.0  699.0  154.578003  170.0   110.000000
2017-08-15        21.0    703.0  602.0  116.402000  131.0    89.000000

                                                             \
store_nbr
family     GROCERY I GROCERY II HARDWARE HOME AND KITCHEN I
date
2013-01-01       0.0        0.0      0.0                0.0
2013-01-02    2652.0       31.0      3.0                0.0
2013-01-03    2121.0       12.0      1.0                0.0
2013-01-04    2056.0       15.0      7.0                0.0
2013-01-05    2216.0       30.0      1.0                0.0
...              ...        ...      ...                ...
2017-08-11    1270.0        9.0      1.0               27.0
2017-08-12    1630.0       19.0      0.0               17.0
2017-08-13     952.0        6.0      1.0               13.0
2017-08-14    2407.0       20.0      0.0               50.0
2017-08-15    2508.0       13.0      3.0               30.0

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01                 0.0             0.0       0.0        0.0
2013-01-02                 0.0             0.0       0.0        0.0
2013-01-03                 0.0             2.0       0.0        0.0
2013-01-04                 0.0             0.0       0.0        0.0
2013-01-05                 0.0             0.0       0.0        0.0
...                        ...             ...       ...        ...
2017-08-11                14.0             0.0      74.0        3.0
2017-08-12                31.0             0.0     116.0        9.0
2017-08-13                 8.0             0.0      61.0        7.0
2017-08-14                31.0             0.0     161.0       17.0
2017-08-15                33.0             0.0     156.0        9.0

                                                                            \
store_nbr
family     LAWN AND GARDEN LINGERIE LIQUOR,WINE,BEER MAGAZINES       MEATS
date
2013-01-01             0.0      0.0              0.0       0.0    0.000000
2013-01-02            10.0     13.0             67.0       0.0  369.101013
2013-01-03             0.0     15.0             66.0       0.0  272.319000
2013-01-04             7.0     24.0            102.0       0.0  454.171997
2013-01-05            10.0     20.0            159.0       0.0  328.940002
...                    ...      ...              ...       ...         ...
2017-08-11            15.0      1.0             67.0       4.0  385.994019
2017-08-12            10.0      8.0             90.0       6.0  211.755997
2017-08-13             8.0      3.0             35.0       4.0   88.181999
2017-08-14            27.0     21.0            100.0       8.0  192.763000
2017-08-15            17.0      4.0             94.0       3.0  274.175995

                                                                           \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS     POULTRY
date
2013-01-01           0.0          0.0                     0.0    0.000000
2013-01-02         194.0          0.0                     0.0  247.296997
2013-01-03         153.0          0.0                     0.0  187.278000
2013-01-04          88.0          0.0                     0.0  258.023010
2013-01-05         141.0          0.0                     0.0  212.333008
...                  ...          ...                     ...         ...
2017-08-11          53.0          5.0                     3.0  259.118011
2017-08-12         227.0          3.0                     6.0  217.664001
2017-08-13          45.0          2.0                     0.0  115.758003
2017-08-14         159.0          3.0                     6.0  270.046997
2017-08-15         173.0          3.0                    21.0  234.891998

                                                                              \
store_nbr
family     PREPARED FOODS      PRODUCE SCHOOL AND OFFICE SUPPLIES    SEAFOOD
date
2013-01-01       0.000000     0.000000                        0.0   0.000000
2013-01-02      47.000000     0.000000                        0.0  38.028999
2013-01-03      63.000000     0.000000                        0.0  17.366001
2013-01-04      67.000000     0.000000                        0.0  29.907001
2013-01-05      66.000000     0.000000                        0.0  24.841999
...                   ...          ...                        ...        ...
2017-08-11      24.963001  1115.333984                        0.0  19.424000
2017-08-12      48.057999  1762.493042                        0.0  20.150000
2017-08-13      20.346001   986.669006                        0.0  11.378000
2017-08-14      72.003998  2611.754883                        0.0  14.129000
2017-08-15      42.822998  2240.229980                        0.0  22.487000

                                                                     \
store_nbr          10
family     AUTOMOTIVE BABY CARE BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01        0.0       0.0    0.0       0.0   0.0          0.0
2013-01-02        3.0       0.0    6.0     396.0   0.0        151.0
2013-01-03        2.0       0.0    3.0     399.0   0.0        129.0
2013-01-04        2.0       0.0    4.0     460.0   0.0        105.0
2013-01-05        0.0       0.0    3.0     624.0   0.0        112.0
...               ...       ...    ...       ...   ...          ...
2017-08-11        2.0       0.0    2.0    1459.0   0.0         76.0
2017-08-12        2.0       0.0    3.0    1332.0   0.0        113.0
2017-08-13        0.0       0.0    5.0    1526.0   0.0        119.0
2017-08-14        1.0       0.0    6.0    1129.0   0.0         82.0
2017-08-15        4.0       0.0    4.0    1608.0   0.0        112.0

                                                                             \
store_nbr
family     CELEBRATION CLEANING  DAIRY   DELI   EGGS FROZEN FOODS GROCERY I
date
2013-01-01         0.0      0.0    0.0    0.0    0.0     0.000000       0.0
2013-01-02         0.0   1110.0  101.0  276.0   57.0    41.164001    2579.0
2013-01-03         0.0    970.0  113.0  269.0   38.0    14.470000    1984.0
2013-01-04         0.0    669.0   66.0   92.0   22.0    10.691000    1565.0
2013-01-05         0.0   1093.0   88.0  194.0   43.0    13.891000    2544.0
...                ...      ...    ...    ...    ...          ...       ...
2017-08-11         5.0    532.0  251.0  269.0   23.0    36.000000    2349.0
2017-08-12         5.0    676.0  255.0  276.0   17.0    28.000000    2629.0
2017-08-13         6.0    670.0  270.0  251.0   62.0    42.000000    2834.0
2017-08-14         3.0    710.0  253.0  313.0  122.0    38.000000    2625.0
2017-08-15         2.0    731.0  328.0  175.0   40.0    49.000000    2679.0

                                                                       \
store_nbr
family     GROCERY II HARDWARE HOME AND KITCHEN I HOME AND KITCHEN II
date
2013-01-01        0.0      0.0                0.0                 0.0
2013-01-02        8.0      2.0                0.0                 0.0
2013-01-03        1.0      0.0                0.0                 0.0
2013-01-04        2.0      0.0                0.0                 0.0
2013-01-05        5.0      3.0                0.0                 0.0
...               ...      ...                ...                 ...
2017-08-11        2.0      0.0                9.0                 8.0
2017-08-12        4.0      0.0                5.0                15.0
2017-08-13       13.0      0.0               11.0                13.0
2017-08-14        0.0      1.0               11.0                 9.0
2017-08-15        5.0      1.0                5.0                12.0

                                                                          \
store_nbr
family     HOME APPLIANCES HOME CARE LADIESWEAR LAWN AND GARDEN LINGERIE
date
2013-01-01             0.0       0.0        0.0             0.0      0.0
2013-01-02             0.0       0.0        0.0             0.0      4.0
2013-01-03             0.0       0.0        0.0             0.0      5.0
2013-01-04             0.0       0.0        0.0             0.0      0.0
2013-01-05             0.0       0.0        0.0             0.0      3.0
...                    ...       ...        ...             ...      ...
2017-08-11             1.0     128.0        2.0             0.0      4.0
2017-08-12             0.0     140.0        8.0             0.0      0.0
2017-08-13             0.0     163.0        2.0             0.0      1.0
2017-08-14             0.0     156.0        2.0             0.0      2.0
2017-08-15             0.0     193.0       13.0             0.0      1.0

                                                                              \
store_nbr
family     LIQUOR,WINE,BEER MAGAZINES       MEATS PERSONAL CARE PET SUPPLIES
date
2013-01-01              0.0       0.0    0.000000           0.0          0.0
2013-01-02              6.0       0.0  291.140015         223.0          0.0
2013-01-03              2.0       0.0  279.742981         169.0          0.0
2013-01-04              8.0       0.0  139.166000         119.0          0.0
2013-01-05             26.0       0.0  247.298004         270.0          0.0
...                     ...       ...         ...           ...          ...
2017-08-11             14.0       1.0  155.992004         193.0          2.0
2017-08-12             49.0       0.0  165.199997         151.0          0.0
2017-08-13              8.0       1.0  156.281998         150.0          1.0
2017-08-14             11.0       0.0  217.770996         155.0          0.0
2017-08-15             14.0       1.0  235.604004         176.0          2.0

                                                                           \
store_nbr
family     PLAYERS AND ELECTRONICS     POULTRY PREPARED FOODS     PRODUCE
date
2013-01-01                     0.0    0.000000            0.0    0.000000
2013-01-02                     0.0  146.783997           26.0    0.000000
2013-01-03                     0.0  148.317001           10.0    0.000000
2013-01-04                     0.0  111.158997            4.0    0.000000
2013-01-05                     0.0  135.596008            3.0    0.000000
...                            ...         ...            ...         ...
2017-08-11                     3.0  169.417999           10.0  224.768997
2017-08-12                     5.0  146.996002           37.0  251.612000
2017-08-13                     3.0  201.742004           13.0  248.518005
2017-08-14                     3.0  133.710007           27.0  220.259995
2017-08-15                     2.0  102.077003           26.0  256.911011

                                                                           \
store_nbr                                             11
family     SCHOOL AND OFFICE SUPPLIES SEAFOOD AUTOMOTIVE BABY CARE BEAUTY
date
2013-01-01                        0.0     0.0        0.0       0.0    0.0
2013-01-02                        0.0     3.0       12.0       0.0    7.0
2013-01-03                        0.0    13.0        8.0       0.0    3.0
2013-01-04                        0.0     2.0        5.0       0.0    1.0
2013-01-05                        0.0     2.0        7.0       0.0   10.0
...                               ...     ...        ...       ...    ...
2017-08-11                        0.0     1.0       10.0       0.0    4.0
2017-08-12                        9.0     0.0       11.0       0.0    2.0
2017-08-13                        3.0     0.0        6.0       0.0    2.0
2017-08-14                        5.0     1.0        2.0       1.0    6.0
2017-08-15                       18.0    11.0        6.0       0.0    7.0

                                                                     \
store_nbr
family     BEVERAGES BOOKS BREAD/BAKERY CELEBRATION CLEANING  DAIRY
date
2013-01-01       0.0   0.0          0.0         0.0      0.0    0.0
2013-01-02    3443.0   0.0        763.0         0.0   3260.0  296.0
2013-01-03    1911.0   0.0        658.0         0.0   2282.0  173.0
2013-01-04    2585.0   0.0        580.0         0.0   2067.0  192.0
2013-01-05    2352.0   0.0        646.0         0.0   2890.0  260.0
...              ...   ...          ...         ...      ...    ...
2017-08-11    5182.0   0.0        634.0        35.0   1572.0  608.0
2017-08-12    4323.0   0.0        582.0        20.0   1453.0  527.0
2017-08-13    4741.0   0.0        582.0        16.0   1649.0  569.0
2017-08-14    4544.0   0.0        583.0        11.0   1808.0  603.0
2017-08-15    4128.0   0.0       2080.0         8.0   1892.0  611.0

                                                                             \
store_nbr
family            DELI   EGGS FROZEN FOODS    GROCERY I GROCERY II HARDWARE
date
2013-01-01    0.000000    0.0     0.000000     0.000000        0.0      0.0
2013-01-02  527.294983  140.0    57.771000  7736.000000       15.0      3.0
2013-01-03  322.415009   74.0    40.714001  5172.000000        5.0      1.0
2013-01-04  316.786011   39.0    53.899002  4678.000000       11.0      1.0
2013-01-05  395.424988   67.0    42.841000  6107.000000       17.0      0.0
...                ...    ...          ...          ...        ...      ...
2017-08-11  486.824005  163.0   116.834999  6551.155762       25.0      0.0
2017-08-12  447.316010  170.0   138.000000  6205.757812       27.0      1.0
2017-08-13  501.876007  338.0   129.416992  6471.546875       29.0      0.0
2017-08-14  489.079987  275.0    48.000000  7380.539062       14.0      0.0
2017-08-15  489.812012  438.0    65.000000  7209.727051       14.0      1.0

                                                                             \
store_nbr
family     HOME AND KITCHEN I HOME AND KITCHEN II HOME APPLIANCES HOME CARE
date
2013-01-01                0.0                 0.0             0.0       0.0
2013-01-02                0.0                 0.0             0.0       0.0
2013-01-03                0.0                 0.0             0.0       0.0
2013-01-04                0.0                 0.0             0.0       0.0
2013-01-05                0.0                 0.0             0.0       0.0
...                       ...                 ...             ...       ...
2017-08-11               47.0                10.0             0.0     428.0
2017-08-12               37.0                13.0             0.0     402.0
2017-08-13               35.0                12.0             0.0     444.0
2017-08-14               13.0                11.0             0.0     532.0
2017-08-15               23.0                14.0             0.0     466.0

                                                                           \
store_nbr
family     LADIESWEAR LAWN AND GARDEN LINGERIE LIQUOR,WINE,BEER MAGAZINES
date
2013-01-01        0.0             0.0      0.0              0.0       0.0
2013-01-02        0.0             0.0     20.0             29.0       0.0
2013-01-03        0.0             0.0     17.0             19.0       0.0
2013-01-04        0.0             0.0      7.0             32.0       0.0
2013-01-05        0.0             2.0      9.0             92.0       0.0
...               ...             ...      ...              ...       ...
2017-08-11        9.0             1.0      6.0             60.0       1.0
2017-08-12        7.0             6.0     10.0             91.0       2.0
2017-08-13        4.0             3.0      7.0             18.0       1.0
2017-08-14        3.0             4.0      6.0             27.0       3.0
2017-08-15       16.0             5.0     11.0             12.0       4.0

                                                                           \
store_nbr
family           MEATS PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS
date
2013-01-01    0.000000           0.0          0.0                     0.0
2013-01-02  832.541016         604.0          0.0                     0.0
2013-01-03  677.962036         441.0          0.0                     0.0
2013-01-04  711.788025         373.0          0.0                     0.0
2013-01-05  819.054993         515.0          0.0                     0.0
...                ...           ...          ...                     ...
2017-08-11  660.140015         320.0          1.0                    14.0
2017-08-12  526.533997         348.0          3.0                    31.0
2017-08-13  652.184998         426.0          2.0                    20.0
2017-08-14  474.139008         373.0          5.0                     7.0
2017-08-15  829.919006         401.0          0.0                    20.0

                                                                               \
store_nbr
family         POULTRY PREPARED FOODS      PRODUCE SCHOOL AND OFFICE SUPPLIES
date
2013-01-01    0.000000       0.000000     0.000000                        0.0
2013-01-02  548.031006      31.000000     0.000000                        0.0
2013-01-03  526.114014      13.000000     0.000000                        0.0
2013-01-04  494.525024      22.000000     0.000000                        0.0
2013-01-05  493.727997      35.000000     0.000000                        0.0
...                ...            ...          ...                        ...
2017-08-11  560.169983     101.866997  1449.668945                       32.0
2017-08-12  368.710999      88.723999  1280.458008                       26.0
2017-08-13  489.114990      78.925003  1290.197021                       13.0
2017-08-14  244.968994     130.225006  1239.467041                       26.0
2017-08-15  526.458984     111.556000  2309.767090                       25.0

                                                                             \
store_nbr                  12
family     SEAFOOD AUTOMOTIVE BABY CARE BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01     0.0        0.0       0.0    0.0       0.0   0.0          0.0
2013-01-02     5.0        4.0       0.0    1.0     682.0   0.0        337.0
2013-01-03    12.0        4.0       0.0    0.0     632.0   0.0        206.0
2013-01-04     2.0        5.0       0.0    0.0     445.0   0.0        156.0
2013-01-05     3.0        7.0       0.0    1.0     801.0   0.0        248.0
...            ...        ...       ...    ...       ...   ...          ...

In [62]:
xg_df

,store_nbr,family,onpromotion,dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,93.14,94.88,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0.0,1,1,2013,1,0.333333,0.333333,0.351852,0.074074
1782,0,0,0,93.14,93.14,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,2,1,2013,2,0.333333,0.333333,0.351852,0.074074
3564,0,0,0,92.97,93.14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,3,1,2013,3,0.333333,0.333333,0.351852,0.074074
5346,0,0,0,93.12,92.97,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,4,1,2013,4,0.333333,0.333333,0.351852,0.074074
7128,0,0,0,93.15,93.12,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,5,1,2013,5,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993759,53,32,0,48.81,48.54,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,11,8,2017,4,0.333333,0.148148,0.351852,0.111111
2995541,53,32,4,48.40,48.81,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,12,8,2017,5,0.333333,0.148148,0.351852,0.111111
2997323,53,32,0,48.00,48.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,13,8,2017,6,0.333333,0.148148,0.351852,0.111111
2999105,53,32,0,47.59,48.00,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,14,8,2017,0,0.333333,0.148148,0.351852,0.111111
3000887,53,32,0,47.57,47.59,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0.0,15,8,2017,1,0.333333,0.148148,0.351852,0.111111

In [63]:
xg_test

,store_nbr,family,onpromotion,dcoilwtico,dcoilwtico_lag,is_national_holiday,is_regional_holiday,is_local_holiday,holiday_type_Additional,holiday_type_Bridge,holiday_type_Event,holiday_type_Holiday,holiday_type_Transfer,holiday_type_Work Day,holiday_transferred,is_holiday_lead,is_holiday,is_holiday_lag,is_christmas_lead(2),is_christmas_lead(1),is_christmas,is_christmas_lag(1),is_christmas_lag(2),is_christmas_lag(3),is_new_year_lead(3),is_new_year_lead(2),is_new_year_lead(1),is_new_year,is_new_year_lag(1),is_new_year_lag(2),is_payday_15,is_payday_end,is_payday_lead,is_payday,is_payday_lag,earthquake_impact,earthquake_decay,day,month,year,dayofweek,city_freq,type_freq,state_freq,cluster_freq
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3000888,0,0,0,46.80,47.57,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.0,16,8,2017,2,0.333333,0.333333,0.351852,0.074074
3002670,0,0,0,47.07,46.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,17,8,2017,3,0.333333,0.333333,0.351852,0.074074
3004452,0,0,0,48.59,47.07,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,18,8,2017,4,0.333333,0.333333,0.351852,0.074074
3006234,0,0,0,48.19,48.59,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,19,8,2017,5,0.333333,0.333333,0.351852,0.074074
3008016,0,0,0,47.79,48.19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,20,8,2017,6,0.333333,0.333333,0.351852,0.074074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3022271,53,32,0,46.82,47.23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,27,8,2017,6,0.333333,0.148148,0.351852,0.111111
3024053,53,32,0,46.40,46.82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,28,8,2017,0,0.333333,0.148148,0.351852,0.111111
3025835,53,32,0,46.46,46.40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,29,8,2017,1,0.333333,0.148148,0.351852,0.111111
3027617,53,32,0,45.96,46.46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.0,30,8,2017,2,0.333333,0.148148,0.351852,0.111111
3029399,53,32,0,47.26,45.96,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0.0,31,8,2017,3,0.333333,0.148148,0.351852,0.111111

In [64]:
lin_logy = np.log1p(lin_y)
lin_logy

                sales                                                   \
store_nbr           1
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   0.000000       0.0  0.000000  0.000000   0.0     0.000000
2013-01-02   1.098612       0.0  1.098612  6.995766   0.0     6.156241
2013-01-03   1.386294       0.0  0.000000  6.824374   0.0     5.741897
2013-01-04   1.386294       0.0  1.386294  6.860664   0.0     5.295142
2013-01-05   1.791759       0.0  1.386294  7.057037   0.0     5.710616
...               ...       ...       ...       ...   ...          ...
2017-08-11   0.693147       0.0  0.693147  6.914731   0.0     4.987755
2017-08-12   1.945910       0.0  1.386294  7.414573   0.0     5.498069
2017-08-13   0.693147       0.0  0.693147  6.689599   0.0     4.924925
2017-08-14   0.693147       0.0  1.945910  7.697121   0.0     5.849434
2017-08-15   1.609438       0.0  1.609438  7.571989   0.0     5.800731

                                                                             \
store_nbr
family     CELEBRATION  CLEANING     DAIRY      DELI      EGGS FROZEN FOODS
date
2013-01-01    0.000000  0.000000  0.000000  0.000000  0.000000     0.000000
2013-01-02    0.000000  6.966967  6.363028  5.106364  5.509388     4.882802
2013-01-03    0.000000  6.729824  6.118097  5.027702  5.318120     4.477837
2013-01-04    0.000000  6.719013  6.133398  4.885911  5.147494     4.189655
2013-01-05    0.000000  6.699501  6.142037  4.784262  5.181784     4.262680
...                ...       ...       ...       ...       ...          ...
2017-08-11    1.609438  5.834811  5.840641  4.179023  4.465908     4.127134
2017-08-12    1.386294  5.863631  6.267200  4.610038  4.736198     4.689456
2017-08-13    0.693147  5.135798  5.587249  3.887115  4.110874     3.931826
2017-08-14    1.609438  6.349139  6.551080  5.047147  5.141664     4.709530
2017-08-15    3.091043  6.556778  6.401917  4.765604  4.882802     4.499810

                                                              \
store_nbr
family     GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01  0.000000   0.000000  0.000000           0.000000
2013-01-02  7.883446   3.465736  1.386294           0.000000
2013-01-03  7.660114   2.564949  0.693147           0.000000
2013-01-04  7.629004   2.772589  2.079442           0.000000
2013-01-05  7.703910   3.433987  0.693147           0.000000
...              ...        ...       ...                ...
2017-08-11  7.147559   2.302585  0.693147           3.332205
2017-08-12  7.396949   2.995732  0.000000           2.890372
2017-08-13  6.859615   1.945910  0.693147           2.639057
2017-08-14  7.786552   3.044523  0.000000           3.931826
2017-08-15  7.827640   2.639057  1.386294           3.433987

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01            0.000000        0.000000  0.000000   0.000000
2013-01-02            0.000000        0.000000  0.000000   0.000000
2013-01-03            0.000000        1.098612  0.000000   0.000000
2013-01-04            0.000000        0.000000  0.000000   0.000000
2013-01-05            0.000000        0.000000  0.000000   0.000000
...                        ...             ...       ...        ...
2017-08-11            2.708050        0.000000  4.317488   1.386294
2017-08-12            3.465736        0.000000  4.762174   2.302585
2017-08-13            2.197225        0.000000  4.127134   2.079442
2017-08-14            3.465736        0.000000  5.087596   2.890372
2017-08-15            3.526361        0.000000  5.056246   2.302585

                                                                           \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES     MEATS
date
2013-01-01        0.000000  0.000000         0.000000  0.000000  0.000000
2013-01-02        2.397895  2.639057         4.219508  0.000000  5.913776
2013-01-03        0.000000  2.772589         4.204693  0.000000  5.610640
2013-01-04        2.079442  3.218876         4.634729  0.000000  6.120676
2013-01-05        2.397895  3.044523         5.075174  0.000000  5.798911
...                    ...       ...              ...       ...       ...
2017-08-11        2.772589  0.693147         4.219508  1.609438  5.958409
2017-08-12        2.397895  2.197225         4.510859  1.945910  5.360146
2017-08-13        2.197225  1.386294         3.583519  1.609438  4.490679
2017-08-14        3.332205  3.091043         4.615120  2.197225  5.266636
2017-08-15        2.890372  1.609438         4.553877  1.386294  5.617411

                                                                         \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS   POULTRY
date
2013-01-01      0.000000     0.000000                0.000000  0.000000
2013-01-02      5.273000     0.000000                0.000000  5.514626
2013-01-03      5.036952     0.000000                0.000000  5.237920
2013-01-04      4.488636     0.000000                0.000000  5.556917
2013-01-05      4.955827     0.000000                0.000000  5.362854
...                  ...          ...                     ...       ...
2017-08-11      3.988984     1.791759                1.386294  5.561135
2017-08-12      5.429346     1.386294                1.945910  5.387537
2017-08-13      3.828641     1.098612                0.000000  4.760103
2017-08-14      5.075174     1.386294                1.945910  5.602292
2017-08-15      5.159055     1.386294                3.091043  5.463374

                                                                          \
store_nbr
family     PREPARED FOODS   PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       0.000000  0.000000                        0.0  0.000000
2013-01-02       3.871201  0.000000                        0.0  3.664305
2013-01-03       4.158883  0.000000                        0.0  2.910501
2013-01-04       4.219508  0.000000                        0.0  3.430983
2013-01-05       4.204693  0.000000                        0.0  3.252001
...                   ...       ...                        ...       ...
2017-08-11       3.256672  7.017806                        0.0  3.016711
2017-08-12       3.893003  7.475052                        0.0  3.051640
2017-08-13       3.060864  6.895348                        0.0  2.515921
2017-08-14       4.290514  7.868160                        0.0  2.716614
2017-08-15       3.780159  7.714780                        0.0  3.156447

                                                                        \
store_nbr          10
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   0.000000       0.0  0.000000  0.000000   0.0     0.000000
2013-01-02   1.386294       0.0  1.945910  5.983936   0.0     5.023880
2013-01-03   1.098612       0.0  1.386294  5.991465   0.0     4.867535
2013-01-04   1.098612       0.0  1.609438  6.133398   0.0     4.663439
2013-01-05   0.000000       0.0  1.386294  6.437752   0.0     4.727388
...               ...       ...       ...       ...   ...          ...
2017-08-11   1.098612       0.0  1.098612  7.286192   0.0     4.343805
2017-08-12   1.098612       0.0  1.386294  7.195187   0.0     4.736198
2017-08-13   0.000000       0.0  1.791759  7.331060   0.0     4.787492
2017-08-14   0.693147       0.0  1.945910  7.029973   0.0     4.418840
2017-08-15   1.609438       0.0  1.609438  7.383368   0.0     4.727388

                                                                             \
store_nbr
family     CELEBRATION  CLEANING     DAIRY      DELI      EGGS FROZEN FOODS
date
2013-01-01    0.000000  0.000000  0.000000  0.000000  0.000000     0.000000
2013-01-02    0.000000  7.013016  4.624973  5.624018  4.060443     3.741567
2013-01-03    0.000000  6.878326  4.736198  5.598422  3.663562     2.738903
2013-01-04    0.000000  6.507277  4.204693  4.532599  3.135494     2.458819
2013-01-05    0.000000  6.997596  4.488636  5.273000  3.784190     2.700757
...                ...       ...       ...       ...       ...          ...
2017-08-11    1.791759  6.278522  5.529429  5.598422  3.178054     3.610918
2017-08-12    1.791759  6.517671  5.545177  5.624018  2.890372     3.367296
2017-08-13    1.945910  6.508769  5.602119  5.529429  4.143135     3.761200
2017-08-14    1.386294  6.566672  5.537334  5.749393  4.812184     3.663562
2017-08-15    1.098612  6.595780  5.796058  5.170484  3.713572     3.912023

                                                              \
store_nbr
family     GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01  0.000000   0.000000  0.000000           0.000000
2013-01-02  7.855545   2.197225  1.098612           0.000000
2013-01-03  7.593374   0.693147  0.000000           0.000000
2013-01-04  7.356280   1.098612  0.000000           0.000000
2013-01-05  7.841886   1.791759  1.386294           0.000000
...              ...        ...       ...                ...
2017-08-11  7.762171   1.098612  0.000000           2.302585
2017-08-12  7.874739   1.609438  0.000000           1.791759
2017-08-13  7.949797   2.639057  0.000000           2.484907
2017-08-14  7.873217   0.000000  0.693147           2.484907
2017-08-15  7.893572   1.791759  0.693147           1.791759

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01            0.000000        0.000000  0.000000   0.000000
2013-01-02            0.000000        0.000000  0.000000   0.000000
2013-01-03            0.000000        0.000000  0.000000   0.000000
2013-01-04            0.000000        0.000000  0.000000   0.000000
2013-01-05            0.000000        0.000000  0.000000   0.000000
...                        ...             ...       ...        ...
2017-08-11            2.197225        0.693147  4.859812   1.098612
2017-08-12            2.772589        0.000000  4.948760   2.197225
2017-08-13            2.639057        0.000000  5.099866   1.098612
2017-08-14            2.302585        0.000000  5.056246   1.098612
2017-08-15            2.564949        0.000000  5.267858   2.639057

                                                                           \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES     MEATS
date
2013-01-01             0.0  0.000000         0.000000  0.000000  0.000000
2013-01-02             0.0  1.609438         1.945910  0.000000  5.677233
2013-01-03             0.0  1.791759         1.098612  0.000000  5.637440
2013-01-04             0.0  0.000000         2.197225  0.000000  4.942827
2013-01-05             0.0  1.386294         3.295837  0.000000  5.514630
...                    ...       ...              ...       ...       ...
2017-08-11             0.0  1.609438         2.708050  0.693147  5.056195
2017-08-12             0.0  0.000000         3.912023  0.000000  5.113192
2017-08-13             0.0  0.693147         2.197225  0.693147  5.058040
2017-08-14             0.0  1.098612         2.484907  0.000000  5.388025
2017-08-15             0.0  0.693147         2.708050  0.693147  5.466388

                                                                         \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS   POULTRY
date
2013-01-01      0.000000     0.000000                0.000000  0.000000
2013-01-02      5.411646     0.000000                0.000000  4.995752
2013-01-03      5.135798     0.000000                0.000000  5.006072
2013-01-04      4.787492     0.000000                0.000000  4.719917
2013-01-05      5.602119     0.000000                0.000000  4.917028
...                  ...          ...                     ...       ...
2017-08-11      5.267858     1.098612                1.386294  5.138254
2017-08-12      5.023880     0.000000                1.791759  4.997185
2017-08-13      5.017280     0.693147                1.386294  5.311934
2017-08-14      5.049856     0.000000                1.386294  4.903124
2017-08-15      5.176150     1.098612                1.098612  4.635476

                                                                          \
store_nbr
family     PREPARED FOODS   PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       0.000000  0.000000                   0.000000  0.000000
2013-01-02       3.295837  0.000000                   0.000000  1.386294
2013-01-03       2.397895  0.000000                   0.000000  2.639057
2013-01-04       1.609438  0.000000                   0.000000  1.098612
2013-01-05       1.386294  0.000000                   0.000000  1.098612
...                   ...       ...                        ...       ...
2017-08-11       2.397895  5.419512                   0.000000  0.693147
2017-08-12       3.637586  5.531855                   2.302585  0.000000
2017-08-13       2.639057  5.519531                   1.386294  0.000000
2017-08-14       3.332205  5.399338                   1.791759  0.693147
2017-08-15       3.295837  5.552615                   2.944439  2.484907

                                                                        \
store_nbr          11
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   0.000000  0.000000  0.000000  0.000000   0.0     0.000000
2013-01-02   2.564949  0.000000  2.079442  8.144389   0.0     6.638568
2013-01-03   2.197225  0.000000  1.386294  7.555905   0.0     6.490724
2013-01-04   1.791759  0.000000  0.693147  7.857868   0.0     6.364751
2013-01-05   2.079442  0.000000  2.397895  7.763446   0.0     6.472346
...               ...       ...       ...       ...   ...          ...
2017-08-11   2.397895  0.000000  1.609438  8.553140   0.0     6.453625
2017-08-12   2.484907  0.000000  1.098612  8.371936   0.0     6.368187
2017-08-13   1.945910  0.000000  1.098612  8.464214   0.0     6.368187
2017-08-14   1.098612  0.693147  1.945910  8.421783   0.0     6.369901
2017-08-15   1.945910  0.000000  2.079442  8.325790   0.0     7.640604

                                                                             \
store_nbr
family     CELEBRATION  CLEANING     DAIRY      DELI      EGGS FROZEN FOODS
date
2013-01-01    0.000000  0.000000  0.000000  0.000000  0.000000     0.000000
2013-01-02    0.000000  8.089789  5.693732  6.269655  4.948760     4.073648
2013-01-03    0.000000  7.733246  5.159055  5.778936  4.317488     3.730837
2013-01-04    0.000000  7.634337  5.262690  5.761378  3.688879     4.005495
2013-01-05    0.000000  7.969358  5.564520  5.982487  4.219508     3.780570
...                ...       ...       ...       ...       ...          ...
2017-08-11    3.583519  7.360740  6.411819  6.189955  5.099866     4.769285
2017-08-12    3.044523  7.282073  6.269096  6.105498  5.141664     4.934474
2017-08-13    2.833213  7.408531  6.345636  6.220344  5.826000     4.870737
2017-08-14    2.484907  7.500529  6.403574  6.194569  5.620401     3.891820
2017-08-15    2.197225  7.545918  6.416732  6.196061  6.084499     4.189655

                                                              \
store_nbr
family     GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01  0.000000   0.000000  0.000000           0.000000
2013-01-02  8.953770   2.772589  1.386294           0.000000
2013-01-03  8.551208   1.791759  0.693147           0.000000
2013-01-04  8.450840   2.484907  0.693147           0.000000
2013-01-05  8.717355   2.890372  0.000000           0.000000
...              ...        ...       ...                ...
2017-08-11  8.787549   3.258096  0.000000           3.871201
2017-08-12  8.733394   3.332205  0.693147           3.637586
2017-08-13  8.775325   3.401197  0.000000           3.583519
2017-08-14  8.906737   2.708050  0.000000           2.639057
2017-08-15  8.883325   2.708050  0.693147           3.178054

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01            0.000000             0.0  0.000000   0.000000
2013-01-02            0.000000             0.0  0.000000   0.000000
2013-01-03            0.000000             0.0  0.000000   0.000000
2013-01-04            0.000000             0.0  0.000000   0.000000
2013-01-05            0.000000             0.0  0.000000   0.000000
...                        ...             ...       ...        ...
2017-08-11            2.397895             0.0  6.061457   2.302585
2017-08-12            2.639057             0.0  5.998937   2.079442
2017-08-13            2.564949             0.0  6.098074   1.609438
2017-08-14            2.484907             0.0  6.278522   1.386294
2017-08-15            2.708050             0.0  6.146329   2.833213

                                                                           \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES     MEATS
date
2013-01-01        0.000000  0.000000         0.000000  0.000000  0.000000
2013-01-02        0.000000  3.044523         3.401197  0.000000  6.725683
2013-01-03        0.000000  2.890372         2.995732  0.000000  6.520565
2013-01-04        0.000000  2.079442         3.496508  0.000000  6.569184
2013-01-05        1.098612  2.302585         4.532599  0.000000  6.709372
...                    ...       ...              ...       ...       ...
2017-08-11        0.693147  1.945910         4.110874  0.693147  6.493966
2017-08-12        1.945910  2.397895         4.521789  1.098612  6.268213
2017-08-13        1.386294  2.079442         2.944439  0.693147  6.481860
2017-08-14        1.609438  1.945910         3.332205  1.386294  6.163608
2017-08-15        1.791759  2.484907         2.564949  1.609438  6.722532

                                                                         \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS   POULTRY
date
2013-01-01      0.000000     0.000000                0.000000  0.000000
2013-01-02      6.405229     0.000000                0.000000  6.308155
2013-01-03      6.091310     0.000000                0.000000  6.267417
2013-01-04      5.924256     0.000000                0.000000  6.205618
2013-01-05      6.246107     0.000000                0.000000  6.204008
...                  ...          ...                     ...       ...
2017-08-11      5.771441     0.693147                2.708050  6.330024
2017-08-12      5.855072     1.386294                3.465736  5.912722
2017-08-13      6.056784     1.098612                3.044523  6.194640
2017-08-14      5.924256     1.791759                2.079442  5.505206
2017-08-15      5.996452     0.000000                3.044523  6.268071

                                                                          \
store_nbr
family     PREPARED FOODS   PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       0.000000  0.000000                   0.000000  0.000000
2013-01-02       3.465736  0.000000                   0.000000  1.791759
2013-01-03       2.639057  0.000000                   0.000000  2.564949
2013-01-04       3.135494  0.000000                   0.000000  1.098612
2013-01-05       3.583519  0.000000                   0.000000  1.386294
...                   ...       ...                        ...       ...
2017-08-11       4.633437  7.279780                   3.496508  2.397895
2017-08-12       4.496738  7.155754                   3.295837  2.302585
2017-08-13       4.381089  7.163325                   2.639057  2.397895
2017-08-14       4.876914  7.123243                   3.295837  1.386294
2017-08-15       4.723451  7.745335                   3.258096  1.386294

                                                                        \
store_nbr          12
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   0.000000       0.0  0.000000  0.000000   0.0     0.000000

In [65]:
hy_model1 = LinearRegression(fit_intercept = False)
hy_model1

LinearRegression(fit_intercept=False)

In [66]:
hy_model1.fit(lin_df, lin_logy)

LinearRegression(fit_intercept=False)

In [67]:
lin_pred2 = hy_model1.predict(lin_df)
lin_pred2

array([[ 0.95840347,  0.        ,  0.85253809, ...,  0.16981633,
        -0.43012353,  2.36712762],
       [ 0.88461497,  0.        ,  0.84891017, ..., -0.14450666,
        -0.47924095,  2.28592312],
       [ 0.79187101,  0.        ,  0.82978261, ..., -0.17937007,
        -0.57996993,  2.46960819],
       ...,
       [ 1.08188696,  0.        ,  0.99912476, ...,  8.65488071,
         2.81992479,  3.02625072],
       [ 1.65139111,  0.        ,  1.45761445, ...,  8.50188052,
         2.58302764,  2.50432089],
       [ 1.76246104,  0.        ,  1.4634371 , ...,  8.73363466,
         2.58586898,  2.49026729]])

In [68]:
lin_log = pd.DataFrame(lin_pred2, 
                       index = lin_y.index,
                       columns = lin_y.columns)
lin_log

                sales                                                       \
store_nbr           1
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES     BOOKS BREAD/BAKERY
date
2013-01-01   0.958403       0.0  0.852538  6.332169 -0.032880     5.197308
2013-01-02   0.884615       0.0  0.848910  6.465697 -0.021505     5.388785
2013-01-03   0.791871       0.0  0.829783  6.330986 -0.050694     5.262294
2013-01-04   0.941098       0.0  0.741516  6.423942 -0.030269     5.275723
2013-01-05   0.979852       0.0  0.861188  6.576870 -0.042080     5.316707
...               ...       ...       ...       ...       ...          ...
2017-08-11   1.745989       0.0  1.390432  7.668896  0.160767     5.894940
2017-08-12   1.771963       0.0  1.516423  7.800540  0.146853     5.920342
2017-08-13   1.081887       0.0  0.999125  6.883784  0.121466     5.028355
2017-08-14   1.651391       0.0  1.457614  7.716865  0.151030     5.983006
2017-08-15   1.762461       0.0  1.463437  7.654016  0.163336     5.891104

                                                                             \
store_nbr
family     CELEBRATION  CLEANING     DAIRY      DELI      EGGS FROZEN FOODS
date
2013-01-01    0.037920  6.077504  5.728300  4.383820  4.626408     4.785803
2013-01-02    0.122829  6.286517  5.925602  4.481361  4.829275     4.937762
2013-01-03    0.154678  6.097024  5.695997  4.322196  4.540770     4.740935
2013-01-04    0.223620  6.154661  5.782771  4.554327  4.763218     4.937539
2013-01-05   -0.015531  6.060233  5.909753  4.504994  4.901438     4.905150
...                ...       ...       ...       ...       ...          ...
2017-08-11    3.199416  6.427640  6.565479  4.938626  4.835129     4.888810
2017-08-12    2.944433  6.315134  6.679416  4.878128  4.958058     4.870089
2017-08-13    2.199782  5.374651  5.823084  4.011781  4.173007     3.873727
2017-08-14    2.909494  6.420876  6.629609  4.910669  4.863006     4.538583
2017-08-15    3.001436  6.418808  6.571481  4.824047  4.752762     4.568078

                                                              \
store_nbr
family     GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01  7.036838   3.245397  0.671416           0.358947
2013-01-02  7.198011   3.333269  0.690784           0.516419
2013-01-03  6.991874   3.170780  0.667065           0.554556
2013-01-04  7.063388   3.023399  0.653237           0.598415
2013-01-05  7.129399   3.032880  0.718607           0.485437
...              ...        ...       ...                ...
2017-08-11  7.720821   2.826691  0.847408           3.469452
2017-08-12  7.768584   2.839524  0.915538           3.326540
2017-08-13  6.891444   1.879455  0.449211           2.506456
2017-08-14  7.774895   2.806201  0.787029           3.153690
2017-08-15  7.745358   2.977987  0.872632           3.283763

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01            0.045154        0.091147  0.168288   0.229931
2013-01-02            0.033187        0.132378  0.255903   0.251746
2013-01-03            0.020587        0.140981  0.108780   0.168992
2013-01-04           -0.011290        0.118259  0.087653   0.103260
2013-01-05            0.016627        0.127903  0.194085   0.227651
...                        ...             ...       ...        ...
2017-08-11            3.449553        0.137675  5.985755   2.910066
2017-08-12            3.457395        0.139233  6.076685   3.018100
2017-08-13            2.901897        0.043581  5.531458   2.488490
2017-08-14            3.569040        0.171524  6.082470   3.046423
2017-08-15            3.622133        0.146317  6.059789   3.020697

                                                                           \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES     MEATS
date
2013-01-01        1.353241  2.131746         3.959345 -0.380237  5.251926
2013-01-02        1.853031  2.310276         4.187101 -0.301762  5.380583
2013-01-03        1.165329  2.182673         4.155041 -0.363278  5.268318
2013-01-04        1.506438  2.099052         4.540379 -0.289059  6.097816
2013-01-05        1.289595  2.024746         4.513329 -0.217757  5.325473
...                    ...       ...              ...       ...       ...
2017-08-11        2.664863  1.399333         5.281812  2.116606  6.248845
2017-08-12        2.437251  1.324221         5.250145  2.177330  5.461352
2017-08-13        2.067173  0.465633         1.305051  1.703912  4.588841
2017-08-14        2.434391  1.284815         4.533359  2.032049  5.493853
2017-08-15        2.512049  1.374229         4.642599  2.019602  5.457927

                                                                         \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS   POULTRY
date
2013-01-01      4.411950     0.063901                0.057832  4.990072
2013-01-02      4.511060     0.090174                0.145527  5.174033
2013-01-03      4.367243     0.012247                0.055847  4.931050
2013-01-04      4.304914     0.024534               -0.004182  5.488007
2013-01-05      4.570570     0.160241                0.017930  5.076472
...                  ...          ...                     ...       ...
2017-08-11      4.888682     2.005702                2.519690  6.072102
2017-08-12      5.143672     2.133127                2.537979  5.647692
2017-08-13      4.313359     1.727554                2.085029  4.871652
2017-08-14      5.141062     2.064881                2.584176  5.766424
2017-08-15      5.092546     2.057372                2.586268  5.623806

                                                                          \
store_nbr
family     PREPARED FOODS   PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       3.918874  0.726727                  -0.036222  2.826712
2013-01-02       4.086340  1.153682                  -0.019123  3.074013
2013-01-03       3.997656  0.799368                  -0.055258  2.782634
2013-01-04       4.111598  1.035410                  -0.060995  3.313154
2013-01-05       4.095025  1.160220                  -0.058546  3.016119
...                   ...       ...                        ...       ...
2017-08-11       4.452902  8.970829                   0.157615  3.587096
2017-08-12       4.424931  9.059702                   0.166964  3.277001
2017-08-13       3.633185  8.801285                   0.136826  2.558731
2017-08-14       4.310911  8.614294                   0.176053  3.070318
2017-08-15       4.316120  8.597793                   0.208271  3.148049

                                                                        \
store_nbr          10
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   1.223763  0.004245  0.618680  5.868232   0.0     4.368384
2013-01-02   1.185173  0.008158  0.509040  5.693380   0.0     4.235128
2013-01-03   1.153438 -0.028220  0.456520  5.672173   0.0     4.175757
2013-01-04   1.187006 -0.016353  0.463189  5.742387   0.0     4.089618
2013-01-05   1.450900  0.002926  0.806364  6.244117   0.0     4.597102
...               ...       ...       ...       ...   ...          ...
2017-08-11   1.025642  0.049638  0.754599  6.950882   0.0     4.186523
2017-08-12   1.300576  0.062560  1.090021  7.444716   0.0     4.685624
2017-08-13   1.360143  0.056100  1.078267  7.395404   0.0     4.771881
2017-08-14   1.103116  0.008505  0.939174  7.191931   0.0     4.632470
2017-08-15   1.053302  0.014504  0.936917  7.120349   0.0     4.541430

                                                                             \
store_nbr
family     CELEBRATION  CLEANING     DAIRY      DELI      EGGS FROZEN FOODS
date
2013-01-01   -0.034537  6.367189  4.622984  4.951149  3.525577     3.632721
2013-01-02   -0.045442  6.231600  4.512057  4.834502  3.392046     3.359699
2013-01-03   -0.003690  6.211875  4.387305  4.872360  3.304575     3.278412
2013-01-04    0.059794  6.166270  4.324713  4.825354  3.190436     3.238655
2013-01-05    0.491121  6.673826  4.868574  5.188889  3.707491     3.959277
...                ...       ...       ...       ...       ...          ...
2017-08-11    1.598000  6.287509  5.485921  5.386864  3.289483     3.688899
2017-08-12    2.010859  6.786737  6.031488  5.742268  3.805842     4.441581
2017-08-13    1.732382  6.658044  6.083271  5.787513  4.048701     4.084984
2017-08-14    1.426105  6.568804  5.900218  5.644663  4.012201     3.777419
2017-08-15    1.533728  6.508156  5.830970  5.568741  3.654071     3.840884

                                                              \
store_nbr
family     GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01  7.208220   1.523001  0.296062           0.334413
2013-01-02  7.056125   1.373253  0.322772           0.314345
2013-01-03  7.015055   1.402043  0.305395           0.310898
2013-01-04  6.958000   1.612612  0.281930           0.420426
2013-01-05  7.504927   2.145507  0.444168           0.775677
...              ...        ...       ...                ...
2017-08-11  7.521829   1.445293  0.331775           2.576624
2017-08-12  8.059133   1.997014  0.491885           2.911396
2017-08-13  7.990609   1.332029  0.443589           2.719624
2017-08-14  7.876019   1.005848  0.354913           2.526976
2017-08-15  7.808581   1.227857  0.317936           2.507301

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01            0.185845        0.169348  0.321717  -0.385075
2013-01-02            0.074006        0.157890  0.181540  -0.418526
2013-01-03            0.059869        0.135067  0.119074  -0.351320
2013-01-04            0.068017        0.158501  0.012857  -0.355001
2013-01-05            0.441383        0.172132  0.395162   0.159645
...                        ...             ...       ...        ...
2017-08-11            2.201555        0.023693  5.945812   1.571109
2017-08-12            2.557395        0.036812  6.320079   2.041982
2017-08-13            2.454480        0.076194  6.247562   2.049360
2017-08-14            2.303552        0.020349  6.204669   1.699576
2017-08-15            2.329663        0.027776  6.223163   1.729580

                                                                           \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES     MEATS
date
2013-01-01       -0.010315  1.474731         2.124983 -0.111141  5.126624
2013-01-02       -0.008229  1.349715         2.019935 -0.103088  4.981234
2013-01-03       -0.000349  1.406732         2.204928 -0.116359  5.139416
2013-01-04       -0.009625  1.327052         2.661582 -0.133809  4.827236
2013-01-05       -0.007280  1.657259         3.153637  0.005822  5.266110
...                    ...       ...              ...       ...       ...
2017-08-11        0.014975  0.472881         3.016879  0.296080  4.664199
2017-08-12        0.017005  0.813326         3.522504  0.433822  5.089603
2017-08-13        0.013108  0.807511         0.923407  0.388696  5.071021
2017-08-14        0.007373  0.635130         2.088154  0.343340  5.058874
2017-08-15        0.007778  0.673423         2.306273  0.327990  5.015819

                                                                         \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS   POULTRY
date
2013-01-01      4.909359    -0.001669                0.068390  4.870853
2013-01-02      4.748828    -0.005771               -0.032499  4.693019
2013-01-03      4.702865    -0.085058               -0.034169  4.747452
2013-01-04      4.577294    -0.079254               -0.028169  4.717322
2013-01-05      5.206172     0.055851                0.241474  5.212421
...                  ...          ...                     ...       ...
2017-08-11      4.870131     0.406978                1.685918  4.849480
2017-08-12      5.493988     0.543794                1.948714  5.342419
2017-08-13      5.417525     0.543484                1.877317  5.313048
2017-08-14      5.255632     0.451990                1.762935  5.026010
2017-08-15      5.238503     0.469855                1.796945  5.001938

                                                                          \
store_nbr
family     PREPARED FOODS   PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       2.021034  0.201563                  -0.234293  1.058190
2013-01-02       1.917227 -0.040044                  -0.258892  0.946556
2013-01-03       1.943147 -0.084448                  -0.270986  1.087510
2013-01-04       1.922156 -0.140420                  -0.241766  0.884057
2013-01-05       2.417292  0.121600                  -0.204032  1.206602
...                   ...       ...                        ...       ...
2017-08-11       3.351159  6.165768                   0.546920  0.741181
2017-08-12       3.839503  6.397567                   0.608562  1.062785
2017-08-13       3.778404  6.397975                   0.639012  1.045267
2017-08-14       3.567126  6.333174                   0.685310  1.033661
2017-08-15       3.551584  6.479135                   0.754412  0.981879

                                                                        \
store_nbr          11
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date
2013-01-01   1.367346 -0.086445  1.045360  7.178705   0.0     5.834225
2013-01-02   1.444700 -0.101824  1.024439  7.091841   0.0     5.749180
2013-01-03   1.354814 -0.119103  0.995559  7.166806   0.0     5.882622
2013-01-04   1.371801 -0.101936  0.861767  7.360560   0.0     5.776987
2013-01-05   1.739565 -0.044587  1.308279  7.573759   0.0     5.994726
...               ...       ...       ...       ...   ...          ...
2017-08-11   1.999465  0.274512  1.849899  8.456416   0.0     6.233548
2017-08-12   2.355698  0.334127  2.302036  8.654019   0.0     6.435316
2017-08-13   2.377994  0.302981  2.447215  8.614957   0.0     6.568844
2017-08-14   2.053973  0.333131  2.110454  8.434168   0.0     6.390073
2017-08-15   2.041861  0.285812  2.096598  8.346487   0.0     6.362362

                                                                             \
store_nbr
family     CELEBRATION  CLEANING     DAIRY      DELI      EGGS FROZEN FOODS
date
2013-01-01   -0.033963  7.032274  5.141584  5.318726  4.220885     4.322249
2013-01-02    0.030321  6.954903  5.059083  5.195237  4.125626     4.216839
2013-01-03    0.045114  6.908060  4.996063  5.302174  4.062347     4.164111
2013-01-04    0.169257  6.955863  4.999944  5.265953  3.942196     4.194333
2013-01-05    0.455482  7.278314  5.402983  5.525993  4.340935     4.628179
...                ...       ...       ...       ...       ...          ...
2017-08-11    3.228283  7.384532  6.386249  6.172857  4.725606     4.633960
2017-08-12    3.501489  7.693406  6.781312  6.423670  5.117762     5.087081
2017-08-13    3.160929  7.743084  6.955279  6.566603  5.424565     4.954180
2017-08-14    2.969714  7.614918  6.611813  6.316473  5.390189     4.517416
2017-08-15    2.999279  7.529031  6.586772  6.285981  5.044405     4.583716

                                                              \
store_nbr
family     GROCERY I GROCERY II  HARDWARE HOME AND KITCHEN I
date
2013-01-01  7.969839   2.540752  0.382209           0.514535
2013-01-02  7.863859   2.539985  0.291165           0.547678
2013-01-03  7.843098   2.653213  0.371337           0.504011
2013-01-04  7.843655   2.766868  0.362311           0.629966
2013-01-05  8.183496   3.001799  0.449924           0.943400
...              ...        ...       ...                ...
2017-08-11  8.660101   3.123339  0.463269           4.031656
2017-08-12  8.987422   3.364736  0.552512           4.324454
2017-08-13  9.057373   3.012702  0.595826           4.223752
2017-08-14  8.889765   2.698018  0.460402           3.920359
2017-08-15  8.814627   2.800670  0.496573           3.962165

                                                                     \
store_nbr
family     HOME AND KITCHEN II HOME APPLIANCES HOME CARE LADIESWEAR
date
2013-01-01            0.264291        0.235329  0.214731  -0.088688
2013-01-02            0.257535        0.255807  0.181103  -0.136275
2013-01-03            0.240156        0.226406  0.108391  -0.120418
2013-01-04            0.224948        0.184145  0.022856   0.012327
2013-01-05            0.566425        0.253409  0.266591   0.138942
...                        ...             ...       ...        ...
2017-08-11            3.229760        0.091441  7.243881   2.901286
2017-08-12            3.544360        0.165808  7.473245   3.015569
2017-08-13            3.596378        0.285942  7.524795   3.082950
2017-08-14            3.378064        0.191349  7.441603   2.823530
2017-08-15            3.339783        0.150705  7.406483   2.775596

                                                                           \
store_nbr
family     LAWN AND GARDEN  LINGERIE LIQUOR,WINE,BEER MAGAZINES     MEATS
date
2013-01-01        0.384326  2.244877         2.887233 -0.421384  5.885109
2013-01-02        0.382102  2.188851         3.028396 -0.452860  5.809208
2013-01-03        0.391876  2.230481         3.250601 -0.416712  6.139005
2013-01-04        0.501945  2.207375         3.670874 -0.433842  5.756461
2013-01-05        0.827789  2.512791         3.953021 -0.169404  5.966822
...                    ...       ...              ...       ...       ...
2017-08-11        1.032825  2.045432         4.553028  1.329217  6.169473
2017-08-12        1.366954  2.345427         4.841873  1.588239  6.360174
2017-08-13        1.277816  2.333012         1.475602  1.549009  6.451300
2017-08-14        0.850310  2.090690         3.509792  1.367073  6.409011
2017-08-15        0.893058  2.101116         3.596576  1.332722  6.368424

                                                                         \
store_nbr
family     PERSONAL CARE PET SUPPLIES PLAYERS AND ELECTRONICS   POULTRY
date
2013-01-01      5.368208    -0.128317               -0.072000  6.020868
2013-01-02      5.304724    -0.086640               -0.046174  5.884308
2013-01-03      5.226418    -0.132826               -0.085476  5.930072
2013-01-04      5.164527    -0.165322               -0.091852  6.110540
2013-01-05      5.616067    -0.015820                0.152476  6.149452
...                  ...          ...                     ...       ...
2017-08-11      5.840330     1.057300                3.058381  6.119957
2017-08-12      6.286314     1.208163                3.294560  6.154128
2017-08-13      6.466059     1.182992                3.289356  6.233527
2017-08-14      6.160960     1.159207                3.154865  5.685408
2017-08-15      6.103468     1.088356                3.062010  6.009662

                                                                          \
store_nbr
family     PREPARED FOODS   PRODUCE SCHOOL AND OFFICE SUPPLIES   SEAFOOD
date
2013-01-01       2.641330  0.208859                  -0.515299  1.592293
2013-01-02       2.606568 -0.170574                  -0.448233  1.324315
2013-01-03       2.573343 -0.193567                  -0.514853  1.442999
2013-01-04       2.675533 -0.232058                  -0.596046  1.358172
2013-01-05       2.894944 -0.019296                  -0.296799  1.848763
...                   ...       ...                        ...       ...
2017-08-11       4.641173  8.177916                   1.901729  1.984304
2017-08-12       4.845098  8.345624                   2.215601  2.466989
2017-08-13       4.788303  8.364922                   2.526508  2.592214
2017-08-14       4.665168  8.298906                   2.250948  2.285589
2017-08-15       4.664857  8.592529                   2.221016  2.208497

                                                                        \
store_nbr          12
family     AUTOMOTIVE BABY CARE    BEAUTY BEVERAGES BOOKS BREAD/BAKERY
date

In [69]:
scoring(lin_logy, lin_log)

MAE: 0.50530, RMSE: 0.83202, R^2:0.37599

In [70]:
xg_logy = linear_model(lin_y = lin_logy, lin_y_pred = lin_log, index = lin_logy, col = lin_logy, df = train_df)
xg_logy

C:\Users\USER\AppData\Local\Temp\ipykernel_880\2583430939.py:16: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  resid_long = residuals.stack(['store_nbr', 'family'])

        store_nbr      family        date     sales
id
0               1  AUTOMOTIVE  2013-01-01 -0.958403
1782            1  AUTOMOTIVE  2013-01-02  0.213997
3564            1  AUTOMOTIVE  2013-01-03  0.594423
5346            1  AUTOMOTIVE  2013-01-04  0.445196
7128            1  AUTOMOTIVE  2013-01-05  0.811907
...           ...         ...         ...       ...
2993759         9     SEAFOOD  2017-08-11  0.927561
2995541         9     SEAFOOD  2017-08-12  0.020906
2997323         9     SEAFOOD  2017-08-13  0.018272
2999105         9     SEAFOOD  2017-08-14  0.386051
3000887         9     SEAFOOD  2017-08-15  0.342946

[3008016 rows x 4 columns]

In [71]:
xgb_logy = xg_logy.sales.to_frame()
xgb_logy

            sales
id
0       -0.958403
1782     0.213997
3564     0.594423
5346     0.445196
7128     0.811907
...           ...
2993759  0.927561
2995541  0.020906
2997323  0.018272
2999105  0.386051
3000887  0.342946

[3008016 rows x 1 columns]

In [82]:
# Instantiate XGBoost
xg_mod2 = xg.XGBRegressor(
    random_state = 42,
    n_estimator = 1500,
    max_depth = 6,
    subsample = 1.0,
    colsample_bytree = 0.8,
    gamma = 0.3, 
    reg_alpha = 0.1,
    reg_lambda = 1.0,
    tree_method = 'hist',
    objective = 'reg:squarederror',
    eval_metric = 'rmse',
    early_stopping_rounds = 70,
    n_jobs = -1,
    verbosity = 1
)

xg_mod2

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=70,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimator=1500, n_estimators=None,
             n_jobs=-1, num_parallel_tree=None, ...)

In [83]:
# Train the Xgb model on log transformed target
cut = 2918915

xg_mod2.fit(xg_df.iloc[:cut], xgb_logy.iloc[:cut],
           eval_set = [(xg_df.iloc[cut:], xgb_logy[cut:])],
           verbose = True)

C:\Users\USER\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [03:07:26] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0c55ff5f71b100e98-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "n_estimator" } are not used.

  warnings.warn(smsg, UserWarning)

[0]	validation_0-rmse:0.83217
[1]	validation_0-rmse:0.80851
[2]	validation_0-rmse:0.79980
[3]	validation_0-rmse:0.78830
[4]	validation_0-rmse:0.78074
[5]	validation_0-rmse:0.77229
[6]	validation_0-rmse:0.76933
[7]	validation_0-rmse:0.76568
[8]	validation_0-rmse:0.75571
[9]	validation_0-rmse:0.74832
[10]	validation_0-rmse:0.74592
[11]	validation_0-rmse:0.74381
[12]	validation_0-rmse:0.73739
[13]	validation_0-rmse:0.73543
[14]	validation_0-rmse:0.71506
[15]	validation_0-rmse:0.70056
[16]	validation_0-rmse:0.69359
[17]	validation_0-rmse:0.69050
[18]	validation_0-rmse:0.68921
[19]	validation_0-rmse:0.68886
[20]	validation_0-rmse:0.68347
[21]	validation_0-rmse:0.68293
[22]	validation_0-rmse:0.68236
[23]	validation_0-rmse:0.69761
[24]	validation_0-rmse:0.69701
[25]	validation_0-rmse:0.69650
[26]	validation_0-rmse:0.69432
[27]	validation_0-rmse:0.69293
[28]	validation_0-rmse:0.69023
[29]	validation_0-rmse:0.68998
[30]	validation_0-rmse:0.68929
[31]	validation_0-rmse:0.68324
[32]	validation_0-rmse:0.68211
[33]	validation_0-rmse:0.68064
[34]	validation_0-rmse:0.67477
[35]	validation_0-rmse:0.67314
[36]	validation_0-rmse:0.67336
[37]	validation_0-rmse:0.67146
[38]	validation_0-rmse:0.66689
[39]	validation_0-rmse:0.66652
[40]	validation_0-rmse:0.66576
[41]	validation_0-rmse:0.66565
[42]	validation_0-rmse:0.66443
[43]	validation_0-rmse:0.66416
[44]	validation_0-rmse:0.66210
[45]	validation_0-rmse:0.66137
[46]	validation_0-rmse:0.66150
[47]	validation_0-rmse:0.65386
[48]	validation_0-rmse:0.64405
[49]	validation_0-rmse:0.64560
[50]	validation_0-rmse:0.64113
[51]	validation_0-rmse:0.63984
[52]	validation_0-rmse:0.64004
[53]	validation_0-rmse:0.63993
[54]	validation_0-rmse:0.63986
[55]	validation_0-rmse:0.64096
[56]	validation_0-rmse:0.63947
[57]	validation_0-rmse:0.63354
[58]	validation_0-rmse:0.63338
[59]	validation_0-rmse:0.63339
[60]	validation_0-rmse:0.63108
[61]	validation_0-rmse:0.62944
[62]	validation_0-rmse:0.62839
[63]	validation_0-rmse:0.62810
[64]	validation_0-rmse:0.62851
[65]	validation_0-rmse:0.62790
[66]	validation_0-rmse:0.62750
[67]	validation_0-rmse:0.62471
[68]	validation_0-rmse:0.62369
[69]	validation_0-rmse:0.61645
[70]	validation_0-rmse:0.61707
[71]	validation_0-rmse:0.61700
[72]	validation_0-rmse:0.61328
[73]	validation_0-rmse:0.60733
[74]	validation_0-rmse:0.60725
[75]	validation_0-rmse:0.61084
[76]	validation_0-rmse:0.60886
[77]	validation_0-rmse:0.60817
[78]	validation_0-rmse:0.60894
[79]	validation_0-rmse:0.60878
[80]	validation_0-rmse:0.60852
[81]	validation_0-rmse:0.60860
[82]	validation_0-rmse:0.60827
[83]	validation_0-rmse:0.60830
[84]	validation_0-rmse:0.60875
[85]	validation_0-rmse:0.60877
[86]	validation_0-rmse:0.60844
[87]	validation_0-rmse:0.60777
[88]	validation_0-rmse:0.60744
[89]	validation_0-rmse:0.60700
[90]	validation_0-rmse:0.60639
[91]	validation_0-rmse:0.60625
[92]	validation_0-rmse:0.60573
[93]	validation_0-rmse:0.60565
[94]	validation_0-rmse:0.60535
[95]	validation_0-rmse:0.60475
[96]	validation_0-rmse:0.60462
[97]	validation_0-rmse:0.60432
[98]	validation_0-rmse:0.60392
[99]	validation_0-rmse:0.60659

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=70,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimator=1500, n_estimators=None,
             n_jobs=-1, num_parallel_tree=None, ...)

In [84]:
print("Best Iteration: ", xg_mod2.best_iteration)
print("Best Score: ", xg_mod2.best_score)

Best Iteration:  98
Best Score:  0.6039170293379023

In [85]:
# Instantiate XGBoost
xg_mol = xg.XGBRegressor(
    n_estimator = 98,
    learning_rate = 0.05,
    max_depth = 6,
    subsample = 1.0,
    colsample_bytree = 0.8,
    gamma = 0.3, 
    reg_alpha = 0.1,
    reg_lambda = 1.0,
    tree_method = 'hist',
    objective = 'reg:squarederror',
    random_state = 42,
    n_jobs = -1,
    verbosity = 0
)
xg_mol

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimator=98, n_estimators=None, n_jobs=-1,
             num_parallel_tree=None, ...)

In [87]:
xg_mol.fit(xg_df, xgb_logy)

AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=0.3, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimator=98, n_estimators=None, n_jobs=-1,
             num_parallel_tree=None, ...)

In [88]:
xg_pred2 = xg_mol.predict(xg_df)
xg_pred2

array([-1.2728244 ,  0.25569427,  0.16095081, ..., -0.081709  ,
       -0.10242006, -0.10331468], dtype=float32)

In [89]:
xgpr_df = pd.DataFrame(xg_pred2, index = xgb_logy.index, columns = ['XGB_pred'])
xgpr_df

         XGB_pred
id
0       -1.272824
1782     0.255694
3564     0.160951
5346     0.130306
7128     0.092491
...           ...
2993759 -0.017697
2995541  0.026954
2997323 -0.081709
2999105 -0.102420
3000887 -0.103315

[3008016 rows x 1 columns]

In [90]:
linpr_df = wide_to_long(lin_log, train_df)
linpr_df

C:\Users\USER\AppData\Local\Temp\ipykernel_880\2168376627.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  long = df.stack(['store_nbr', 'family'])

         LIN_pred
id
0        0.958403
1782     0.884615
3564     0.791871
5346     0.941098
7128     0.979852
...           ...
2993759  2.284532
2995541  2.861601
2997323  3.026251
2999105  2.504321
3000887  2.490267

[3008016 rows x 1 columns]

In [91]:
subms = pd.DataFrame()
subms['sales']= xgpr_df['XGB_pred'] + linpr_df['LIN_pred']
subms

            sales
id
0       -0.314421
1782     1.140309
3564     0.952822
5346     1.071404
7128     1.072343
...           ...
2993759  2.266834
2995541  2.888555
2997323  2.944542
2999105  2.401901
3000887  2.386953

[3008016 rows x 1 columns]

In [93]:
scoring(tree_y, subms)

MAE: 0.46169, RMSE: 0.71020, R^2:0.93059

In [94]:
# Create the prediction
lin_pr = hy_model1.predict(lin_test)
xg_pr = xg_mol.predict(xg_test)
# make xg_p a dataframe
xgr_subm = pd.DataFrame(xg_pr, index = xg_test.index, columns = ['XGB_pred'])
xgr_subm

         XGB_pred
id
3000888 -0.098235
3002670 -0.106855
3004452 -0.106855
3006234 -0.096995
3008016 -0.080268
...           ...
3022271 -0.121731
3024053 -0.151568
3025835 -0.151568
3027617 -0.141141
3029399 -0.127919

[28512 rows x 1 columns]

In [95]:
lin_subm = wide_to_long(df = pd.DataFrame(lin_p,
                                    index = lin_test.index,
                                    columns = lin_y.columns), df2 = test_df)
lin_subm

C:\Users\USER\AppData\Local\Temp\ipykernel_880\2168376627.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  long = df.stack(['store_nbr', 'family'])

          LIN_pred
id
3000888   4.969832
3002670   4.478898
3004452   5.188625
3006234   5.082703
3008016   2.754747
...            ...
3022271  25.166465
3024053  14.343206
3025835  13.747100
3027617  12.764019
3029399  16.089263

[28512 rows x 1 columns]

In [96]:
submn = pd.DataFrame()
submn['sales']= xgr_subm['XGB_pred'] + lin_subm['LIN_pred']
submn

             sales
id
3000888   4.871597
3002670   4.372043
3004452   5.081770
3006234   4.985708
3008016   2.674479
...            ...
3022271  25.044735
3024053  14.191637
3025835  13.595532
3027617  12.622878
3029399  15.961344

[28512 rows x 1 columns]

In [97]:
submn.to_csv('logsubmis.csv', index = True)